export const CATEGORIES = [
  { id: "noStart",     label: "No Start",              icon: "🔑" },
  { id: "checkEngine", label: "Check Engine Light",    icon: "⚠️" },
  { id: "overheat",   label: "Overheating",            icon: "🌡️" },
  { id: "acNotCold",  label: "A/C Not Cold",           icon: "❄️" },
  { id: "battery",    label: "Battery / Charging",     icon: "🔋" },
  { id: "brakes",     label: "Brakes",                 icon: "🛑" },
  { id: "suspension", label: "Suspension / Noise",     icon: "🔊" },
  { id: "transmission", label: "Transmission",         icon: "⚙️" },
  { id: "roughIdle",    label: "Rough Idle",           icon: "🌀" },
  { id: "misfire",      label: "Misfire",              icon: "⚡" },
  { id: "charging",     label: "Charging System",      icon: "🔌" },
];

// Each tree has a `start` node ID and two maps:
//   nodes   — question nodes  { question, options: [{label, next}] }
//   results — terminal nodes  { title, probability, why, firstChecks, tools, safety, dtcCodes, professionalHelp }

export const TREES = {

  // ─── No Start ───────────────────────────────────────────────────────────────
  noStart: {
    start: "q1",
    nodes: {
      q1: {
        question: "When you turn the key or press Start, what happens?",
        options: [
          { label: "Engine cranks (spins) but won't fire up",               next: "q_crank" },
          { label: "Dim or flickering dash lights — no crank",              next: "result_dead_battery" },
          { label: "One loud single CLUNK, then nothing",                   next: "result_single_click" },
          { label: "Rapid clicking — many fast clicks",                     next: "result_rapid_click" },
          { label: "Completely silent — all lights work fine",              next: "q_security" },
          { label: "Completely silent — no lights either",                  next: "result_no_power" },
        ],
      },
      q_crank: {
        question: "Is the security / immobilizer light flashing or staying on?",
        options: [
          { label: "Yes — security light is flashing or solid",             next: "result_immobilizer" },
          { label: "No — security light is off or normal",                  next: "q_fuel" },
        ],
      },
      q_fuel: {
        question: "Is there confirmed fuel in the tank?",
        options: [
          { label: "Yes — tank is not empty, key is correct",               next: "result_crank_nostart" },
          { label: "Tank may be low or not sure",                           next: "result_check_fuel" },
        ],
      },
      q_security: {
        question: "Is the security / immobilizer indicator light flashing?",
        options: [
          { label: "Yes — security light is flashing",                      next: "result_immobilizer" },
          { label: "No — no security light, just silence",                  next: "result_starter_circuit" },
        ],
      },
    },
    results: {
      result_dead_battery: {
        title: "Weak or dead battery / poor battery connection",
        probability: "Very high",
        why: "Dim dash lights with no crank is the classic sign of a battery without enough power to run the starter motor.",
        firstChecks: ["Check battery terminal connections — shake to feel for looseness", "Look for white or green corrosion on terminals", "Try jump-starting the vehicle", "Test battery voltage (should be 12.4 V or higher when off)"],
        tools: ["Jumper cables or jump pack", "Multimeter"],
        safety: ["Connect red (positive) to positive, black to a chassis ground — not directly to the dead battery negative", "Keep sparks and flames away from the battery", "Wear eye protection"],
        dtcCodes: ["P0562"],
        professionalHelp: "Seek help if the battery won't hold a charge after 30 minutes of driving, if cables get hot, or if terminals show heavy corrosion that won't clean off.",
      },
      result_single_click: {
        title: "Starter, starter relay, or weak battery cable",
        probability: "High",
        why: "One loud click means the starter solenoid engaged but the motor couldn't turn — usually a bad starter, a borderline battery, or a corroded/loose cable.",
        firstChecks: ["Test battery voltage (often borderline — 11.8–12.2 V)", "Check battery cables at both ends for looseness or corrosion", "Try jump-starting — if it starts, the battery or cable is the issue", "If jump doesn't help, have the starter tested"],
        tools: ["Jumper cables or jump pack", "Multimeter"],
        safety: ["Keep clear of the starter and flywheel area during testing"],
        dtcCodes: ["P0615"],
        professionalHelp: "If a jump start doesn't help and the battery tests good, the starter likely needs replacement — most shops can do this same-day.",
      },
      result_rapid_click: {
        title: "Dead or severely weak battery",
        probability: "Very high",
        why: "Rapid clicking is the most recognizable sign of a dead battery. The solenoid tries to engage, voltage collapses, it releases, tries again — over and over.",
        firstChecks: ["Jump-start the vehicle", "Check battery terminal tightness and corrosion", "Test battery voltage (likely below 12 V)", "Drive at least 30 minutes after jump to recharge"],
        tools: ["Jumper cables or jump pack", "Battery tester (optional)"],
        safety: ["Keep flames away from the battery", "Connect cables in correct order: red positive first, black ground last"],
        dtcCodes: ["P0562"],
        professionalHelp: "If the battery repeatedly goes dead, have the alternator tested. A battery older than 4–5 years should be replaced.",
      },
      result_immobilizer: {
        title: "Immobilizer / key transponder not recognized",
        probability: "High",
        why: "A flashing security light means the PCM does not recognize the key — the immobilizer is preventing the engine from starting as a theft deterrent.",
        firstChecks: ["Try a spare programmed key", "Make sure the key fob battery is not dead (push-start cars)", "Ensure key is fully inserted or fob is inside the vehicle", "If no spare works, this requires dealer programming"],
        tools: ["Spare key if available"],
        safety: ["Do not attempt to bypass the immobilizer — this affects vehicle security"],
        dtcCodes: ["P0513"],
        professionalHelp: "If a spare key doesn't work, take the vehicle to a dealer — immobilizer reprogramming requires factory-level tools.",
      },
      result_starter_circuit: {
        title: "Starter relay, neutral safety switch, or ignition switch circuit",
        probability: "Medium to high",
        why: "Complete silence with working lights means power is reaching the dash but not the starter circuit — relay, neutral safety switch, or ignition switch.",
        firstChecks: ["Confirm vehicle is fully in Park (auto) or clutch is fully depressed (manual)", "Check the starter relay and fuse in the underhood fuse box", "Try wiggling the gear selector in Park", "Test for voltage at the starter solenoid terminal with key in Start"],
        tools: ["Multimeter", "Test light"],
        safety: ["Keep clear of engine components during testing"],
        dtcCodes: ["P0512", "P0615"],
        professionalHelp: "If relay and fuses test good, the ignition switch or PCM starter circuit may need professional diagnosis.",
      },
      result_no_power: {
        title: "Complete power loss — main fuse, main cable, or fully dead battery",
        probability: "High",
        why: "No lights, no clicks, nothing at all often means a main fusible link has blown or the battery is completely dead.",
        firstChecks: ["Check the main battery fuse / fusible link under the hood", "Verify battery cable connections at both ends", "Test battery voltage — may be at 0 V", "Try jump-starting"],
        tools: ["Jumper cables", "Multimeter", "Flashlight"],
        safety: ["Do not touch bare cable ends together"],
        dtcCodes: [],
        professionalHelp: "If jump-starting does nothing and cables look intact, have the main fusible links inspected — a blown main fuse requires professional diagnosis.",
      },
      result_crank_nostart: {
        title: "Cranks but won't start — fuel, spark, or sensor issue",
        probability: "Medium",
        why: "If the engine spins freely but won't fire, it needs fuel, spark, and compression. Most crank/no-start cases come down to fuel or ignition.",
        firstChecks: ["Listen for the fuel pump prime hum when the key first turns to ON", "Check for stored DTC codes with an OBD-II scanner", "Test for spark using a spare plug on a plug wire", "Verify no security light is flashing"],
        tools: ["OBD-II scanner", "Spark tester or spare spark plug"],
        safety: ["Do not crank more than 10 seconds at a time — starter overheating risk", "Keep fuel vapors away from ignition sources when testing for spark"],
        dtcCodes: ["P0335", "P0340", "P0513", "P0627"],
        professionalHelp: "If you have spark and a fuel pump prime but still no start, the issue may involve timing or compression — seek professional help.",
      },
      result_check_fuel: {
        title: "Verify fuel level and key first — most overlooked causes",
        probability: "High for simple cause",
        why: "Empty tank and wrong key are both common — always rule them out before deeper diagnosis.",
        firstChecks: ["Add fuel if level is uncertain", "Confirm you have the correct programmed key", "Listen for fuel pump prime sound on key-on"],
        tools: [],
        safety: ["No smoking or sparks near the fuel system"],
        dtcCodes: [],
        professionalHelp: "If fuel and key are confirmed correct and vehicle still won't start, scan for DTC codes next.",
      },
    },
  },

  // ─── Check Engine Light ──────────────────────────────────────────────────────
  checkEngine: {
    start: "q1",
    nodes: {
      q1: {
        question: "Is the check engine light flashing / blinking, or is it steady?",
        options: [
          { label: "Flashing / blinking continuously",                     next: "result_flashing" },
          { label: "Steady on — no flashing",                              next: "q_running" },
        ],
      },
      q_running: {
        question: "How is the vehicle running right now?",
        options: [
          { label: "Rough, shaking, or misfiring",                        next: "q_misfire" },
          { label: "Running normally — no noticeable problem",             next: "result_steady_nosymptom" },
          { label: "Hesitation or poor acceleration",                      next: "result_lean" },
          { label: "Noticeably worse fuel economy",                        next: "result_economy" },
        ],
      },
      q_misfire: {
        question: "When does the rough running happen?",
        options: [
          { label: "All the time — idle and driving",                     next: "result_active_misfire" },
          { label: "Only at idle — smooths out at speed",                  next: "result_idle_misfire" },
          { label: "Only under load or acceleration",                      next: "result_load_misfire" },
        ],
      },
    },
    results: {
      result_flashing: {
        title: "STOP DRIVING — Active misfire is destroying the catalytic converter",
        probability: "High",
        why: "A flashing check engine light means the engine is misfiring badly enough to send unburned fuel into the catalytic converter. This can destroy it within minutes at highway speed.",
        firstChecks: ["Pull over and stop driving as soon as safely possible", "Scan for codes — P030X codes identify which cylinder is misfiring", "Do not drive at highway speed with a flashing CEL"],
        tools: ["OBD-II scanner"],
        safety: ["Do not drive the vehicle hard with a flashing CEL", "A hot catalytic converter is a fire risk if parked near dry grass"],
        dtcCodes: ["P0300", "P0301", "P0302", "P0303", "P0304"],
        professionalHelp: "A flashing CEL is an emergency. If you cannot scan and fix it today, have the vehicle towed.",
      },
      result_steady_nosymptom: {
        title: "Stored code — scan first, diagnose before replacing anything",
        probability: "Scan required",
        why: "A steady check engine light with no symptoms means the PCM detected a fault outside acceptable range — often emissions-related. These need to be scanned before any parts are replaced.",
        firstChecks: ["Scan for DTC codes — auto parts stores (AutoZone, O'Reilly, NAPA) scan for free", "Note all stored and pending codes", "Common silent codes: P0420 (catalyst), P0442/P0455 (EVAP), P0128 (thermostat)"],
        tools: ["OBD-II scanner (or free scan at parts store)"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "P0420 codes are often a $500+ repair — get a second opinion before replacing a catalytic converter. Confirm O2 sensors and exhaust leaks are ruled out first.",
      },
      result_active_misfire: {
        title: "Active misfire — ignition coil, spark plug, or fuel injector",
        probability: "High",
        why: "Rough running at all RPMs with a CEL often points to a failed ignition coil, spark plug, or fuel injector on a specific cylinder.",
        firstChecks: ["Scan for codes — P0301–P0308 identify the misfiring cylinder", "Swap the ignition coil from the misfiring cylinder to another to see if the misfire follows", "Inspect spark plugs for fouling, cracks, or wear", "Check injector if coil and plug test good"],
        tools: ["OBD-II scanner", "Ratchet set", "Torque wrench"],
        safety: ["Allow engine to cool before removing spark plugs"],
        dtcCodes: ["P0300", "P0301", "P0302", "P0303", "P0304", "P0351", "P0352"],
        professionalHelp: "If coil and plug swap doesn't isolate the problem, a compression test or injector test by a shop is the next step.",
      },
      result_idle_misfire: {
        title: "Idle-only misfire — vacuum leak or injector issue",
        probability: "Medium",
        why: "Misfires only at idle often point to a vacuum leak (causes a lean condition at low RPM) or a sticking fuel injector.",
        firstChecks: ["Spray carb cleaner carefully around intake seams at idle — RPM change = vacuum leak", "Check for cracked or disconnected vacuum hoses", "Scan for lean codes (P0171, P0174)", "Clean throttle body and IAC valve"],
        tools: ["Carb cleaner", "OBD-II scanner"],
        safety: ["Keep carb cleaner away from hot exhaust — fire risk"],
        dtcCodes: ["P0300", "P0171", "P0174", "P0505"],
        professionalHelp: "Persistent idle misfire after vacuum check may need a smoke test to find a hidden leak.",
      },
      result_load_misfire: {
        title: "Load/acceleration misfire — fuel delivery or ignition under load",
        probability: "Medium",
        why: "Misfires only under load often point to a fuel delivery problem or failing spark plugs and coils that cannot handle demand at higher RPM.",
        firstChecks: ["Test fuel pressure — a drop under load indicates a pump issue", "Inspect spark plugs for wear", "Check for P0171/P0174 lean codes"],
        tools: ["Fuel pressure gauge", "OBD-II scanner"],
        safety: ["Fuel pressure testing involves pressurized fuel — fire risk"],
        dtcCodes: ["P0300", "P0171", "P0174"],
        professionalHelp: "Load testing fuel pressure and coil performance often requires a shop with live data monitoring.",
      },
      result_lean: {
        title: "Lean condition — vacuum leak, MAF, or fuel delivery",
        probability: "Medium to high",
        why: "Hesitation and poor acceleration with a CEL often means more air than expected — vacuum leak, dirty MAF sensor, or weak fuel delivery.",
        firstChecks: ["Check for vacuum leaks at intake manifold seams and all hoses", "Clean MAF sensor with MAF-safe cleaner", "Scan for P0171 or P0174", "Check air filter condition"],
        tools: ["OBD-II scanner", "MAF sensor cleaner"],
        safety: [],
        dtcCodes: ["P0171", "P0174", "P0101"],
        professionalHelp: "If vacuum leak inspection and MAF cleaning don't resolve lean codes, have fuel pressure tested.",
      },
      result_economy: {
        title: "Scan codes first — several issues cause fuel economy loss",
        probability: "Scan required",
        why: "Poor fuel economy with a CEL can stem from a failing O2 sensor, stuck thermostat, catalyst inefficiency, or a lean/rich condition — codes will tell you where to look.",
        firstChecks: ["Scan for codes — they focus your diagnosis", "Check tire pressure (under-inflation hurts MPG significantly)", "Verify oil is fresh and correct viscosity", "Check air filter"],
        tools: ["OBD-II scanner", "Tire pressure gauge"],
        safety: [],
        dtcCodes: ["P0128", "P0171", "P0420", "P0133"],
        professionalHelp: "If codes point to the catalytic converter, get a second opinion on converter replacement — it's often misdiagnosed.",
      },
    },
  },

  // ─── Overheating ─────────────────────────────────────────────────────────────
  overheat: {
    start: "q_safe",
    nodes: {
      q_safe: {
        question: "Safety check: If the temperature gauge is in the red right now, is the engine off?",
        options: [
          { label: "Yes — I've stopped and the engine is off",             next: "q_when" },
          { label: "Diagnosing a past event — vehicle is cool now",        next: "q_when" },
        ],
      },
      q_when: {
        question: "When does it overheat?",
        options: [
          { label: "At idle only — fine while driving at speed",           next: "q_fan" },
          { label: "While driving — worse at highway speed",               next: "result_driving_overheat" },
          { label: "Both at idle and while driving",                       next: "q_coolant" },
        ],
      },
      q_fan: {
        question: "Do the radiator cooling fans turn on when the engine gets hot?",
        options: [
          { label: "No — fans are not spinning when hot",                  next: "result_fan_failure" },
          { label: "Yes — fans are running",                               next: "result_airflow_blocked" },
          { label: "Not sure",                                             next: "result_check_fan" },
        ],
      },
      q_coolant: {
        question: "When cool — is the coolant level low in the reservoir?",
        options: [
          { label: "Yes — coolant is low or reservoir is empty",           next: "result_low_coolant" },
          { label: "No — coolant level looks normal",                      next: "result_driving_overheat" },
        ],
      },
    },
    results: {
      result_fan_failure: {
        title: "Cooling fan not coming on at idle",
        probability: "High",
        why: "Electric fans are the only airflow source at a standstill. If they don't come on, the engine overheats at idle but stays cool at speed (ram air through the radiator keeps it cool).",
        firstChecks: ["Check the cooling fan fuse and relay in the underhood fuse box", "Turn on A/C — this forces the fan on in most vehicles (good test)", "With engine hot at idle, watch the fan — should turn on around 200–210°F", "Apply 12V directly to fan motor connector to test the motor itself"],
        tools: ["Test light or multimeter", "Fuse puller"],
        safety: ["Keep hands away from fan blades — electric fans can start without warning", "NEVER open the radiator cap when hot — severe steam burn risk"],
        dtcCodes: ["P0480", "P0481"],
        professionalHelp: "A failed fan motor is a straightforward replacement on most vehicles. Wiring or PCM fan control issues require professional diagnosis.",
      },
      result_airflow_blocked: {
        title: "Fans working but still overheating at idle — possible restriction or thermostat",
        probability: "Medium",
        why: "If fans work but the engine still overheats at idle, suspect a blocked radiator (bugs, debris), a partially clogged radiator internally, or a thermostat not fully opening.",
        firstChecks: ["Inspect radiator face for leaves, bugs, or debris blocking airflow", "Feel both radiator hoses — upper and lower should both be hot when engine is hot", "A cold lower hose with a hot upper suggests thermostat stuck closed", "Does the heater blow hot? Cold heater with overheating = low coolant or air pocket"],
        tools: ["Garden hose to flush radiator fins"],
        safety: ["Never open radiator cap while hot"],
        dtcCodes: ["P0128"],
        professionalHelp: "Internal radiator restriction or a head gasket leak requires professional pressure testing.",
      },
      result_check_fan: {
        title: "Verify cooling fan operation — it is the most common idle-overheat cause",
        probability: "High if fans aren't running",
        why: "Confirming whether the fan turns on is the most important first step for idle overheating.",
        firstChecks: ["Start engine, let idle until hot, and watch the fan area", "Turn on A/C — most vehicles force the fan on with A/C", "Check the fan fuse and relay if fans don't activate"],
        tools: ["Test light"],
        safety: ["Keep hands clear of the fan area at all times"],
        dtcCodes: ["P0480"],
        professionalHelp: "If fans run but engine still overheats at idle, further diagnosis is needed.",
      },
      result_driving_overheat: {
        title: "Overheats while driving — thermostat, water pump, or coolant restriction",
        probability: "High",
        why: "Overheating at speed with plenty of airflow points to a restriction in coolant flow: stuck thermostat, failing water pump, blocked radiator, or a coolant leak.",
        firstChecks: ["When cool — check coolant level in reservoir and radiator", "Upper hose hot, lower hose cool = thermostat stuck closed", "Check for coolant leaks under the vehicle", "White exhaust smoke or sweet smell = possible internal leak (head gasket)", "Is the heater blowing cold? = low coolant or air in system"],
        tools: ["Flashlight"],
        safety: ["NEVER open the radiator cap when hot — severe steam burn risk", "Do not drive an overheating engine — head gasket failure is a very expensive repair", "Pull over immediately if the gauge hits red"],
        dtcCodes: ["P0128"],
        professionalHelp: "A water pump failure, internal coolant leak, or blown head gasket all require professional diagnosis. Do not continue driving if the engine overheats.",
      },
      result_low_coolant: {
        title: "Low coolant — find the leak before refilling",
        probability: "High",
        why: "Low coolant creates air pockets that cause hot spots and overheating. Always identify the leak source before simply topping off.",
        firstChecks: ["Look under vehicle for puddles (green, orange, or pink = coolant)", "Inspect radiator hose connections at all ends", "Check radiator cap seal condition", "White exhaust smoke or sweet smell from exhaust = internal leak (head gasket)"],
        tools: ["Flashlight"],
        safety: ["Never add cold coolant to a hot engine — thermal shock can crack the block or head", "Never open the radiator cap while hot"],
        dtcCodes: [],
        professionalHelp: "Persistent unexplained coolant loss without a visible external leak, milky oil, or white smoke requires a professional pressure test — head gasket leaks are serious.",
      },
    },
  },

  // ─── A/C Not Cold ────────────────────────────────────────────────────────────
  acNotCold: {
    start: "q1",
    nodes: {
      q1: {
        question: "Is air coming out of the vents at all?",
        options: [
          { label: "No air from vents at all",                              next: "result_blower" },
          { label: "Weak airflow on all fan speeds",                        next: "result_cabin_filter" },
          { label: "Normal airflow — just not cold",                        next: "q2" },
        ],
      },
      q2: {
        question: "Does the A/C compressor clutch engage? (With A/C on, the center of the compressor pulley should spin.)",
        options: [
          { label: "Yes — compressor is running",                           next: "q3" },
          { label: "No — center hub of pulley does not spin with A/C on",  next: "q_comp_off" },
          { label: "Not sure / can't tell",                                 next: "q3" },
        ],
      },
      q3: {
        question: "When is the A/C weakest?",
        options: [
          { label: "Warm at idle, cooler at highway speed",                 next: "result_condenser_fan" },
          { label: "Never gets cold regardless of speed",                   next: "result_low_refrigerant" },
          { label: "Cold briefly then goes warm",                           next: "result_cycling" },
        ],
      },
      q_comp_off: {
        question: "Has the A/C been serviced recently, or is refrigerant level known?",
        options: [
          { label: "No recent service — could be low on refrigerant",       next: "result_low_refrigerant" },
          { label: "Recently serviced or refrigerant is known to be good",  next: "result_comp_electrical" },
        ],
      },
    },
    results: {
      result_blower: {
        title: "Blower motor or resistor failure — no airflow",
        probability: "High",
        why: "No air from vents means the blower motor isn't running — most often a blown fuse, failed blower resistor, or failed blower motor.",
        firstChecks: ["Check blower motor fuse in the interior fuse box", "Test different fan speeds — if some work but others don't, the blower resistor is likely the issue", "Listen for a hum from the blower area when switching to max fan", "Test for power at the blower motor connector"],
        tools: ["Multimeter", "Test light"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Blower resistors are inexpensive and often DIY-replaceable. A motor that won't run on any speed with power confirmed at the connector needs replacement.",
      },
      result_cabin_filter: {
        title: "Clogged cabin air filter — restricted airflow",
        probability: "High",
        why: "Weak airflow at all fan speeds is the classic symptom of a severely clogged cabin air filter — one of the most overlooked maintenance items.",
        firstChecks: ["Locate the cabin air filter (usually behind the glove box or under the dash)", "If it is dark gray or packed with debris, replace it", "Cabin filters should be replaced every 12,000–15,000 miles or yearly"],
        tools: ["None for inspection — screwdriver on some vehicles"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Straightforward DIY job on most vehicles — under 20 minutes.",
      },
      result_condenser_fan: {
        title: "Condenser fan not running — classic warm-at-idle A/C",
        probability: "High",
        why: "Warm at idle, noticeably cooler at highway speed is the most recognizable A/C symptom. At speed, ram air cools the condenser. At idle, the condenser fan must do that — and it's failing.",
        firstChecks: ["Turn on A/C and look at the fan in front of the radiator (or condenser) — it should be running", "Check the condenser fan fuse and relay", "Apply 12V directly to fan motor to confirm whether the motor is good"],
        tools: ["Test light or multimeter"],
        safety: ["Keep hands clear of fan area at all times — it can start without warning"],
        dtcCodes: ["P0480", "P0481"],
        professionalHelp: "Fan relay is a cheap, easy fix. Failed fan motor is still a relatively simple replacement.",
      },
      result_low_refrigerant: {
        title: "Low refrigerant — most common A/C complaint",
        probability: "High",
        why: "Refrigerant leaks out slowly over years. A system that used to work but no longer gets cold is often simply low. The compressor clutch will not engage if pressure is too low.",
        firstChecks: ["Check low-side pressure with gauges — should be 25–45 psi at idle with A/C on", "Recharge kits at auto parts stores work for R-134a (pre-2021 most vehicles)", "2021+ vehicles use R-1234yf — requires professional recharge equipment", "Recharging without fixing the leak is only temporary"],
        tools: ["A/C gauge set or recharge kit (R-134a systems)"],
        safety: ["Refrigerant is pressurized — wear eye protection", "Never vent refrigerant to atmosphere — illegal and harmful", "Do not overcharge — overcharging damages the compressor"],
        dtcCodes: ["P0530"],
        professionalHelp: "For R-1234yf vehicles or if you are not comfortable with A/C work, have a shop do a leak test and recharge.",
      },
      result_cycling: {
        title: "System cycling off — likely icing from low charge",
        probability: "Medium",
        why: "A/C that gets briefly cold then goes warm may be icing the evaporator (a symptom of low refrigerant) or a pressure switch cycling the compressor off too quickly.",
        firstChecks: ["Check refrigerant pressure — low charge causes evaporator icing", "Listen for compressor clutch cycling on and off frequently", "Check that the cabin air filter is not severely clogged — restricts airflow over the evaporator"],
        tools: ["A/C gauge set"],
        safety: ["Wear eye protection when checking A/C pressure"],
        dtcCodes: ["P0530"],
        professionalHelp: "Icing diagnosis requires checking refrigerant charge and evaporator condition — a shop can do this quickly with gauges.",
      },
      result_comp_electrical: {
        title: "Compressor clutch electrical issue — relay, fuse, or pressure switch",
        probability: "Medium",
        why: "If refrigerant is known to be good but the compressor won't engage, the issue is electrical — relay, fuse, low-pressure switch, or PCM not commanding the clutch.",
        firstChecks: ["Check the A/C compressor relay and fuse", "Test for 12V at the clutch coil connector with A/C on", "Verify low-pressure switch is not open — this switch prevents engagement if refrigerant is too low"],
        tools: ["Test light or multimeter"],
        safety: [],
        dtcCodes: ["P0645"],
        professionalHelp: "If power reaches the clutch coil but it doesn't engage, the clutch coil may be burned out — requires compressor service.",
      },
    },
  },

  // ─── Battery / Charging ──────────────────────────────────────────────────────
  battery: {
    start: "q1",
    nodes: {
      q1: {
        question: "What is the main symptom?",
        options: [
          { label: "Battery or charging light on while driving",            next: "q_voltage" },
          { label: "Won't start — clicks or nothing",                       next: "result_nostart" },
          { label: "Battery keeps dying — needs frequent jump starts",       next: "q_dying" },
        ],
      },
      q_voltage: {
        question: "What is the battery voltage with the engine running? (Measure at the battery or use a scan tool)",
        options: [
          { label: "Under 13.0 V — below normal",                          next: "result_not_charging" },
          { label: "13.5–14.8 V — normal",                                 next: "result_sensor_issue" },
          { label: "Over 15.0 V — above normal",                           next: "result_overcharging" },
          { label: "Haven't measured yet",                                  next: "result_measure_first" },
        ],
      },
      q_dying: {
        question: "After a jump start and 30+ minutes of driving, does it start normally the next day?",
        options: [
          { label: "No — dead again next morning or within a day",         next: "q_parasitic" },
          { label: "Yes — holds charge for a few days but eventually dies", next: "result_weak_battery" },
        ],
      },
      q_parasitic: {
        question: "Does the battery die faster if you leave the car sitting completely unused?",
        options: [
          { label: "Yes — faster when just sitting",                        next: "result_parasitic" },
          { label: "No — holds fine sitting, dies only after short trips",  next: "result_short_trips" },
        ],
      },
    },
    results: {
      result_nostart: {
        title: "Battery too weak to start — jump and test",
        probability: "High",
        why: "A battery that won't start the vehicle is dead, too weak, or poorly connected.",
        firstChecks: ["Jump-start the vehicle", "Clean battery terminals — corrosion causes voltage drop", "Test voltage: 12.6 V = good, 12.2 V = weak, below 12 V = likely failed", "Have the battery load-tested for definitive results"],
        tools: ["Jumper cables or jump pack", "Multimeter or battery tester"],
        safety: ["Connect positive first, ground last when jump-starting"],
        dtcCodes: ["P0562"],
        professionalHelp: "Most auto parts stores test batteries for free. A battery older than 5 years that tests weak should be replaced.",
      },
      result_not_charging: {
        title: "Alternator not charging — under 13 V while running",
        probability: "High",
        why: "Normal charging voltage is 13.5–14.8 V. Below 13 V means the alternator isn't keeping up — the battery is draining while driving.",
        firstChecks: ["Check the alternator belt — intact and properly tensioned?", "Check the large cable from alternator to battery for a good connection", "Listen for a growling or whining noise from the alternator (bad bearing)", "Have the alternator tested at an auto parts store (usually free)"],
        tools: ["Multimeter"],
        safety: ["Alternator and battery carry high current — avoid short circuits"],
        dtcCodes: ["P0620"],
        professionalHelp: "A failed alternator needs replacement. Note serpentine belt routing before removal.",
      },
      result_sensor_issue: {
        title: "Charging voltage normal — sensor, wiring, or intermittent issue",
        probability: "Medium",
        why: "If charging voltage is normal but the light is on, suspect a battery current sensor, wiring fault, or an intermittent alternator problem.",
        firstChecks: ["Check battery terminal tightness and corrosion", "Inspect the large alternator output cable for damage", "Scan for charging system fault codes", "Test voltage under heavy load (headlights + A/C + blower on high)"],
        tools: ["Multimeter", "OBD-II scanner"],
        safety: [],
        dtcCodes: ["P0620", "P0562"],
        professionalHelp: "Intermittent alternator issues require live data monitoring — a shop can catch dropouts in charging voltage.",
      },
      result_overcharging: {
        title: "Overcharging — voltage regulator failure",
        probability: "High",
        why: "Over 15 V is too high. The voltage regulator inside the alternator has failed. Overcharging damages the battery, electronics, and light bulbs.",
        firstChecks: ["Confirm the reading with a known-good multimeter", "Have the alternator tested — most parts stores test off the vehicle for free", "Do not continue driving long-term — electronics damage risk"],
        tools: ["Multimeter"],
        safety: ["Overcharging can boil battery acid — keep sparks away from the battery"],
        dtcCodes: ["P0563"],
        professionalHelp: "The alternator needs replacement — internal regulators cannot be serviced on most modern units.",
      },
      result_measure_first: {
        title: "Measure voltage first — it tells you exactly where to look",
        probability: "Test required",
        why: "30 seconds with a multimeter tells you whether the problem is the battery, the alternator, or neither.",
        firstChecks: ["Key off — battery should read 12.4 V or higher", "Engine running — should read 13.5–14.8 V", "Under 13 V running = alternator problem", "Over 15 V running = regulator problem", "Auto parts stores offer free charging system tests with professional equipment"],
        tools: ["Multimeter or free test at auto parts store"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "AutoZone, O'Reilly, and NAPA all offer free battery and alternator testing — use it before buying any parts.",
      },
      result_weak_battery: {
        title: "Weak battery — not holding a full charge",
        probability: "High",
        why: "A battery that holds charge for a few days but not weeks is typically degraded internally. Age and temperature extremes accelerate this.",
        firstChecks: ["Have battery load-tested at an auto parts store (free)", "Check the date code on the battery — most batteries last 4–6 years", "Clean terminals and verify alternator is charging properly"],
        tools: ["Free test at auto parts store"],
        safety: [],
        dtcCodes: ["P0562"],
        professionalHelp: "Battery replacement is straightforward DIY. Note: some vehicles (BMW, Mazda, some Ford/GM) require programming after replacement — check first.",
      },
      result_parasitic: {
        title: "Parasitic drain — something staying on when car is off",
        probability: "High",
        why: "A battery that dies faster when the car sits means something is drawing power with the key off — a stuck relay, a module not sleeping, or an aftermarket accessory.",
        firstChecks: ["Check all interior lights, trunk light, and underhood light", "Disconnect aftermarket accessories one at a time (stereo amp, alarm)", "Measure parasitic draw in milliamps — should be under 50 mA after modules sleep (10–20 min after key off)", "Pull fuses one at a time to identify the circuit with the drain"],
        tools: ["Multimeter in milliamp mode", "Fuse puller"],
        safety: ["Do not disconnect the battery with the engine running"],
        dtcCodes: [],
        professionalHelp: "Parasitic drain diagnosis can take hours. Aftermarket alarms and subwoofer amplifiers are very common culprits. A shop with the right tools can trace this efficiently.",
      },
      result_short_trips: {
        title: "Short trip driving — alternator never fully recharges the battery",
        probability: "High",
        why: "Very short trips (under 10 minutes) don't give the alternator time to replace what the starter motor used. The battery gets progressively weaker.",
        firstChecks: ["Take a 30–45 minute highway drive to fully recharge", "Test battery condition — it may already be degraded", "Consider a trickle charger or battery maintainer if vehicle sits frequently"],
        tools: ["Battery maintainer / trickle charger"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "A battery tender plugged in at home is an inexpensive solution for primarily short-trip drivers.",
      },
    },
  },

  // ─── Brakes ──────────────────────────────────────────────────────────────────
  brakes: {
    start: "q1",
    nodes: {
      q1: {
        question: "What is the brake symptom?",
        options: [
          { label: "Squealing or squeaking noise",                          next: "result_squeal" },
          { label: "Grinding metal-on-metal noise",                         next: "result_grinding" },
          { label: "Soft or spongy brake pedal",                            next: "result_soft_pedal" },
          { label: "Pedal pulsating or vibrating during braking",           next: "result_pulsation" },
          { label: "Vehicle pulls to one side when braking",                next: "result_pull_brake" },
          { label: "ABS or brake warning light on",                         next: "result_abs_light" },
        ],
      },
    },
    results: {
      result_squeal: {
        title: "Brake wear indicator squeal — pads near the end",
        probability: "High",
        why: "Most modern brake pads have a small metal tab that contacts the rotor when the pad material is low. The resulting squeal is intentional — it is your warning.",
        firstChecks: ["Look through the wheel spokes — you can often see the pad thickness directly", "Less than 3 mm of pad = replace soon", "Squeal that stops when brakes are applied = wear indicator", "Squeal that happens during braking = glazed pads or rotor"],
        tools: ["Flashlight"],
        safety: ["Do not ignore brake squealing for more than a few days — worn pads quickly become a grinding danger"],
        dtcCodes: [],
        professionalHelp: "Brake pad replacement is DIY-friendly on most vehicles. Have rotor thickness checked at the same time.",
      },
      result_grinding: {
        title: "Pads worn completely — metal grinding on metal",
        probability: "Very high",
        why: "Grinding means the brake pad friction material is completely gone. Metal is contacting the rotor. This is a safety emergency.",
        firstChecks: ["Do not delay — this needs to be addressed immediately", "Rotors are likely already deeply scored and may need replacement"],
        tools: [],
        safety: ["⚠️ SAFETY: Severely worn brakes can fail suddenly", "Do not drive at highway speed", "Have the vehicle serviced before driving further than necessary to reach a shop"],
        dtcCodes: [],
        professionalHelp: "This requires immediate service. Metal-on-metal contact almost always means both pads AND rotors need replacement.",
      },
      result_soft_pedal: {
        title: "Soft / spongy pedal — air in brake lines or fluid leak",
        probability: "High",
        why: "Air in the brake system compresses instead of transmitting pressure — this causes a spongy pedal. This happens from a fluid leak, brake work with incomplete bleeding, or old fluid.",
        firstChecks: ["Check brake fluid level in the master cylinder reservoir", "Inspect for fluid leaks at calipers, lines, and master cylinder", "If level is low with no pad wear, there is a leak — find it before driving"],
        tools: ["Flashlight"],
        safety: ["⚠️ A pedal that sinks to the floor is a brake emergency — do not drive", "Do not drive if pedal travel is excessive"],
        dtcCodes: [],
        professionalHelp: "Brake bleeding and leak diagnosis require professional attention unless you have direct experience with brake hydraulics.",
      },
      result_pulsation: {
        title: "Pedal pulsation — warped or uneven rotors",
        probability: "High",
        why: "A pulsating pedal during braking is almost always caused by rotors that are uneven in thickness (known as thickness variation) or have slight runout.",
        firstChecks: ["Pulsation in steering wheel = front rotors; only in pedal = rear rotors", "Have rotor thickness measured with a micrometer — uneven wear causes pulsation", "Rotor resurfacing can fix minor issues; thin or heavily grooved rotors need replacement"],
        tools: ["Micrometer (shop tool) — have a shop measure if unavailable"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Many shops offer free brake inspections. Rotor thickness measurement is the definitive test.",
      },
      result_pull_brake: {
        title: "Pulling during braking — sticking caliper or collapsed brake hose",
        probability: "Medium",
        why: "Pulling to one side when braking means unequal braking force — most commonly a sticking caliper, a collapsed flexible brake hose, or a significant difference in pad thickness.",
        firstChecks: ["Touch each front wheel hub shortly after driving — a noticeably hotter hub indicates a dragging caliper", "Inspect rubber brake hoses for bulging or cracking", "Compare pad thickness side to side — uneven wear = sticking caliper"],
        tools: ["Flashlight", "Infrared thermometer (optional)"],
        safety: ["A vehicle that pulls hard during braking is a safety risk — address promptly"],
        dtcCodes: [],
        professionalHelp: "Sticking caliper and hose inspection are best done by a shop — a stuck caliper causes heat buildup and can lead to brake fade or fire.",
      },
      result_abs_light: {
        title: "ABS / brake warning light — wheel speed sensor or ABS module",
        probability: "Medium",
        why: "The ABS light means the anti-lock brake system detected a fault. Normal braking works, but ABS and stability control may not function.",
        firstChecks: ["Scan for ABS-specific codes — these are separate from engine codes", "Most common cause: faulty wheel speed sensor", "Inspect wheel speed sensor wiring at each wheel — road debris commonly damages the harness", "Check for rust on the reluctor ring (tone ring) on the axle"],
        tools: ["ABS-capable OBD-II scanner"],
        safety: ["ABS not working means longer stopping distances on slippery surfaces — adjust your driving"],
        dtcCodes: [],
        professionalHelp: "ABS diagnosis requires a scanner that reads ABS codes — not all basic scanners do this. A shop can quickly pinpoint the faulty sensor.",
      },
    },
  },

  // ─── Suspension / Noise ──────────────────────────────────────────────────────
  suspension: {
    start: "q1",
    nodes: {
      q1: {
        question: "What noise or symptom are you experiencing?",
        options: [
          { label: "Clunking over bumps",                                   next: "result_clunk" },
          { label: "Squeaking over bumps or when turning",                  next: "result_squeak_susp" },
          { label: "Humming or droning noise that changes with vehicle speed", next: "result_wheel_bearing" },
          { label: "Steering pulls to one side",                            next: "result_pull_susp" },
          { label: "Excessive bouncing — wallowing ride",                   next: "result_shocks" },
          { label: "Vibration in steering wheel at highway speed",          next: "result_balance" },
        ],
      },
    },
    results: {
      result_clunk: {
        title: "Clunking over bumps — sway bar link, strut mount, or ball joint",
        probability: "Medium to high",
        why: "A single clunk over bumps is typically a worn or loose suspension component. Sway bar end links are inexpensive and fail frequently. Ball joints are more serious.",
        firstChecks: ["Have someone rock the car side-to-side while you listen under the vehicle", "Grab each sway bar end link and try to wiggle it — loose = likely worn", "Inspect strut mounts in the engine bay (front-wheel-drive vehicles)", "Have ball joints inspected — worn ball joints are a safety concern"],
        tools: ["Flashlight", "Floor jack and jack stands for safe inspection"],
        safety: ["⚠️ Never work under a vehicle supported only by a floor jack — use jack stands", "Ball joint failure can cause sudden loss of steering control — do not ignore"],
        dtcCodes: [],
        professionalHelp: "Ball joint inspection requires lifting the vehicle and applying force to the wheel. Have a shop inspect if you are not comfortable.",
      },
      result_squeak_susp: {
        title: "Squeaking — dry bushings, springs, or ball joints",
        probability: "Medium",
        why: "Squeaking suspension noise is often dry rubber bushings, a dry ball joint, or coil spring isolators — usually not dangerous but annoying.",
        firstChecks: ["Spray white lithium grease or silicone spray on rubber bushings and ball joints", "Sway bar bushings (rubber blocks on the bar) dry out and squeak frequently", "Coil spring isolators squeak in cold weather — usually not a structural concern"],
        tools: ["White lithium grease or silicone spray"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Squeaking that doesn't respond to lubrication may indicate worn bushings that need replacement.",
      },
      result_wheel_bearing: {
        title: "Wheel bearing noise — humming or droning",
        probability: "High",
        why: "A consistent hum or drone that changes pitch with vehicle speed (not engine speed) is the classic wheel bearing sound. It often changes when you weave gently left or right at speed.",
        firstChecks: ["At 50 mph, gently weave left and right — noise gets louder when the bad bearing is loaded", "Jack up each corner and spin the wheel by hand — roughness or grinding feel = bad bearing", "Noise gets louder as the bearing degrades — do not delay"],
        tools: ["Floor jack and jack stands"],
        safety: ["⚠️ A severely worn wheel bearing can fail completely — avoid long highway trips", "Always use jack stands when lifting a vehicle"],
        dtcCodes: [],
        professionalHelp: "Wheel bearing replacement is a shop job on most modern vehicles with pressed-in or integrated hub bearings.",
      },
      result_pull_susp: {
        title: "Steering pull — alignment, tire, or sticking brake",
        probability: "Medium",
        why: "Consistent pulling to one side is most often caused by a low or defective tire, a misaligned suspension, or a dragging brake caliper.",
        firstChecks: ["Check all four tire pressures — a low tire causes a pull", "Swap front tires side-to-side — if pull changes direction, one tire is defective", "Feel front wheel hubs for heat after a short drive — a hot hub = dragging brake caliper", "Check when alignment was last done — a curb impact can knock out alignment"],
        tools: ["Tire pressure gauge"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Alignment requires a professional alignment rack. If pull persists after tire inspection, have alignment checked.",
      },
      result_shocks: {
        title: "Worn shock absorbers or struts — excessive bouncing",
        probability: "High",
        why: "Worn shocks allow the suspension to bounce excessively. A vehicle that continues bouncing 2+ times after a bump likely needs shocks or struts.",
        firstChecks: ["Bounce test: push down on each corner firmly and release — should stop in 1 bounce", "Look for oil leaks on the shock body — wet, oily streaks mean the shock is worn", "Worn struts affect alignment and accelerate tire wear"],
        tools: [],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Always get an alignment after replacing front struts — strut replacement changes alignment angles.",
      },
      result_balance: {
        title: "Wheel imbalance — vibration at speed",
        probability: "High",
        why: "Vibration in the steering wheel that appears at a specific speed (often 55–70 mph) and fades above or below is almost always a tire balance issue.",
        firstChecks: ["Have tires balanced — quick and inexpensive at any tire shop", "Check for missing wheel weights on the rims", "Inspect tires for cupping wear (scalloped pattern) — can indicate balance issue or worn shocks", "A persistent vibration at all speeds regardless of acceleration may indicate a bent rim"],
        tools: ["Professional tire balancer — shop service needed"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Tire balancing is a fast, inexpensive service. Persistent vibration after balancing may indicate a bent rim or defective tire.",
      },
    },
  },

  // ─── Transmission ────────────────────────────────────────────────────────────
  transmission: {
    start: "q1",
    nodes: {
      q1: {
        question: "What transmission symptom are you experiencing?",
        options: [
          { label: "Slipping — engine revs up but car barely accelerates",  next: "result_slip" },
          { label: "Rough, harsh, or hard shifts",                          next: "result_harsh" },
          { label: "Delayed engagement going into gear",                    next: "result_delayed" },
          { label: "Transmission warning light on",                         next: "result_trans_light" },
          { label: "Fluid leaking under the vehicle",                       next: "result_trans_leak" },
          { label: "Shuddering or vibrating at highway cruising speed",     next: "result_shudder" },
        ],
      },
    },
    results: {
      result_slip: {
        title: "Transmission slipping — check fluid immediately",
        probability: "High",
        why: "Slipping means the transmission is not transferring power effectively. Low or burnt fluid is the first thing to check — it is the most common cause and the easiest to fix.",
        firstChecks: ["Check transmission fluid level on a warm engine (if a dipstick is present)", "Note fluid color: bright red = good, dark red = old, brown = very old, black = burnt", "Smell the fluid — a strong burnt odor indicates internal damage", "Scan for transmission codes (P0730, P0731, etc.)"],
        tools: ["OBD-II scanner", "Transmission fluid"],
        safety: ["Do not tow or drive hard with a slipping transmission — damage accelerates rapidly"],
        dtcCodes: ["P0700", "P0730", "P0731", "P0740"],
        professionalHelp: "If fluid is at the correct level and not burnt but slipping persists, internal clutch pack wear is likely — requires professional rebuild or replacement.",
      },
      result_harsh: {
        title: "Harsh or rough shifts — fluid condition or shift solenoid",
        probability: "Medium",
        why: "Rough shifts can result from degraded fluid, a failing shift solenoid, or valve body wear. Fresh fluid sometimes resolves this significantly.",
        firstChecks: ["Check fluid level and condition — degraded fluid is the most common cause", "A fluid drain and refill often improves harsh shifts on high-mileage vehicles", "Scan for shift solenoid codes (P0750–P0770)", "Note if it is worse when cold vs. warm"],
        tools: ["OBD-II scanner"],
        safety: [],
        dtcCodes: ["P0700", "P0750", "P0755", "P0760"],
        professionalHelp: "Solenoid replacement or valve body service requires dropping the transmission pan — a straightforward shop job.",
      },
      result_delayed: {
        title: "Delayed engagement — fluid or torque converter",
        probability: "Medium",
        why: "A long pause before Drive or Reverse engages often indicates low fluid, degraded fluid, or a torque converter issue.",
        firstChecks: ["Check fluid level and condition immediately", "Allow the engine to fully warm up before hard use", "Scan for codes", "Note if the delay is only when cold or also when fully warm"],
        tools: ["OBD-II scanner"],
        safety: [],
        dtcCodes: ["P0700", "P0740"],
        professionalHelp: "Persistent delayed engagement after a fluid service may indicate internal wear requiring professional diagnosis.",
      },
      result_trans_light: {
        title: "Scan for transmission codes — the light alone is not enough",
        probability: "Scan required",
        why: "A transmission warning light stores codes in the TCM that are essential for accurate diagnosis. Never replace parts before reading codes.",
        firstChecks: ["Scan for transmission-specific codes — requires an enhanced scanner or a shop visit", "Basic OBD-II scanners may only show P0700 (a pointer code) — you need the underlying code", "Check fluid level and condition first", "Auto parts stores often can read transmission codes for free"],
        tools: ["Enhanced OBD-II scanner or shop visit"],
        safety: [],
        dtcCodes: ["P0700"],
        professionalHelp: "Transmission problems caught early are far cheaper to fix — do not delay diagnosis.",
      },
      result_trans_leak: {
        title: "Transmission fluid leak — identify source before driving further",
        probability: "High",
        why: "Transmission fluid is red when new, darkening with age. A leak drops fluid level, leading to slipping, overheating, and rapid internal damage.",
        firstChecks: ["Identify leak location: pan gasket (bottom), cooler lines (sides), or front/rear seals", "Check and top off fluid level if low", "Pan gasket leaks are common and relatively easy to repair", "Cooler line leaks can spray fluid onto hot exhaust — fire risk"],
        tools: ["Flashlight", "Drain pan for cleanup"],
        safety: ["Transmission fluid near hot exhaust is a fire risk", "Do not drive far with confirmed low fluid"],
        dtcCodes: [],
        professionalHelp: "Rear seal replacement requires dropping the driveshaft — shop job. Pan gasket replacement is DIY-accessible on most vehicles.",
      },
      result_shudder: {
        title: "Torque converter or CVT shudder — usually fluid-related",
        probability: "High",
        why: "Vibration or shudder at 35–50 mph that feels like driving over rumble strips is typically torque converter clutch shudder — caused by degraded fluid or a worn clutch lining.",
        firstChecks: ["A fluid drain and refill with the exact specified fluid often eliminates shudder", "Use only the correct fluid type (Mercon ULV, Dexron HP, Toyota WS, Honda CVT, etc.)", "Scan for TCC codes (P0740, P0741)", "CVT shudder on Honda and Nissan is commonly resolved with a CVT fluid change"],
        tools: ["OBD-II scanner"],
        safety: [],
        dtcCodes: ["P0740", "P0741"],
        professionalHelp: "If a fluid change doesn't resolve shudder, the torque converter may need replacement. Confirm the diagnosis before committing to that repair.",
      },
    },
  },

  // ─── Rough Idle ──────────────────────────────────────────────────────────────
  roughIdle: {
    start: "q1",
    nodes: {
      q1: {
        question: "Is the check engine light on?",
        options: [
          { label: "Yes — CEL is on",                                      next: "result_scan_first" },
          { label: "No — no warning lights",                               next: "q2" },
        ],
      },
      q2: {
        question: "When does the rough idle occur?",
        options: [
          { label: "Only when cold — smooths out when fully warm",         next: "result_cold_idle" },
          { label: "All the time — cold and warm",                         next: "q3" },
          { label: "Only after the engine is fully warm",                  next: "result_warm_idle" },
        ],
      },
      q3: {
        question: "Is the idle rough in gear (Drive/Reverse) or also in Park/Neutral?",
        options: [
          { label: "Rough in all positions including Park",                next: "result_vacuum" },
          { label: "Worse in gear than Park/Neutral",                      next: "result_engine_load" },
          { label: "Stalls at idle",                                       next: "result_stall" },
        ],
      },
    },
    results: {
      result_scan_first: {
        title: "Scan for codes before diagnosing — codes focus your repair",
        probability: "Scan required",
        why: "A rough idle with a CEL almost always has a stored code pointing to the cause. Diagnosing without scanning first leads to guessing.",
        firstChecks: ["Scan for codes at an auto parts store (free) or with your own scanner", "Note all stored AND pending codes", "P0300–P030X = misfire; P017X = lean/rich; P050X = idle control; P034X = cam/crank sensor"],
        tools: ["OBD-II scanner"],
        safety: [],
        dtcCodes: ["P0300","P0301","P0171","P0174","P0505"],
        professionalHelp: "If codes return after clearing, do not keep clearing them — the underlying issue needs to be fixed.",
        relatedProblems: ["Misfire","Check Engine Light","Vacuum Leak","Idle Air Control"],
      },
      result_cold_idle: {
        title: "Cold-start rough idle — normal range or IAC/IACV issue",
        probability: "Medium",
        why: "Cold engines run rich by design. A rough idle that clears as the engine warms is often normal for older vehicles. If it is unusually rough or lasts more than 2–3 minutes, suspect the idle air control valve or coolant temp sensor.",
        firstChecks: ["Let the engine warm up fully — note exactly when it smooths out", "Check coolant temperature sensor (a failed one gives the ECM false cold readings)", "Clean the idle air control (IAC) valve or throttle body — carbon buildup is common"],
        tools: ["Throttle body cleaner", "OBD-II scanner for live coolant temp data"],
        safety: [],
        dtcCodes: ["P0128","P0115","P0505"],
        professionalHelp: "If cleaning the IAC doesn't help, have the coolant temp sensor tested with live data to confirm it reads correctly.",
        relatedProblems: ["Coolant Temp Sensor","Throttle Body Cleaning","IAC Valve","Cold Start Enrichment"],
      },
      result_warm_idle: {
        title: "Rough idle only when warm — vacuum leak or EGR issue",
        probability: "Medium",
        why: "Idle problems that appear only when warm often indicate vacuum leaks that open up with heat, a stuck-open EGR valve, or a failing IAC that isn't compensating correctly.",
        firstChecks: ["With engine fully warm, spray carb cleaner carefully around intake seams — RPM change = vacuum leak", "Check EGR valve — a stuck-open EGR at idle causes severe roughness", "Inspect all vacuum hoses for cracks — some crack only when warm"],
        tools: ["Carb cleaner (careful near heat)", "OBD-II scanner"],
        safety: ["Keep carb cleaner spray away from hot exhaust manifold — fire risk"],
        dtcCodes: ["P0401","P0404","P0171","P0174"],
        professionalHelp: "A smoke test performed at a shop is the most reliable way to find vacuum leaks.",
        relatedProblems: ["EGR Valve","Vacuum Leak","MAF Sensor","Throttle Body"],
      },
      result_vacuum: {
        title: "Vacuum leak — rough at all RPMs in all positions",
        probability: "High",
        why: "A vacuum leak introduces unmetered air into the intake, causing a lean condition. The idle is rough because the ECM cannot fully compensate.",
        firstChecks: ["Inspect all rubber vacuum hoses for cracks, disconnections, or collapses", "Check intake manifold gaskets — listen for hissing near the intake at idle", "Check PCV hose condition", "Spray carb cleaner carefully around the intake — if idle changes, you found the leak"],
        tools: ["Carb cleaner", "OBD-II scanner (look for P0171/P0174)"],
        safety: ["Do not spray carb cleaner near hot exhaust — fire risk"],
        dtcCodes: ["P0171","P0174","P0507"],
        professionalHelp: "A shop with a smoke machine can find vacuum leaks quickly and reliably, including leaks that spraying can't find.",
        relatedProblems: ["Lean Condition","MAF Sensor","Intake Gasket","IAC Valve"],
      },
      result_engine_load: {
        title: "Rough under load — mounts, misfire, or torque converter",
        probability: "Medium",
        why: "A rough idle only in gear with the engine under load can indicate worn engine mounts transmitting vibration, a misfire under load, or torque converter shudder.",
        firstChecks: ["In Park, rev the engine — if smooth, the vibration in Drive may be from engine mounts", "Check engine mounts for cracking or separation (look for excessive engine movement)", "Scan for misfire codes under load — a live misfire counter is useful"],
        tools: ["OBD-II scanner with live data", "Flashlight for mount inspection"],
        safety: [],
        dtcCodes: ["P0300","P0740"],
        professionalHelp: "Worn engine mounts are common on high-mileage vehicles. Torque converter shudder is often resolved with a transmission fluid change.",
        relatedProblems: ["Engine Mounts","Misfire","Torque Converter","Transmission Shudder"],
      },
      result_stall: {
        title: "Stalling at idle — IAC, throttle body, or idle relearn needed",
        probability: "Medium",
        why: "An engine that stalls at idle is not maintaining enough airflow at low RPM. Common causes are a dirty or failed idle air control valve, dirty throttle body, or a vacuum leak.",
        firstChecks: ["Clean the throttle body with throttle body cleaner — carbon buildup is very common", "Clean or test the idle air control valve", "Check for vacuum leaks", "Perform a throttle relearn procedure after cleaning if recommended for your vehicle"],
        tools: ["Throttle body cleaner", "IAC cleaner"],
        safety: ["Allow engine to cool before cleaning the throttle body"],
        dtcCodes: ["P0505","P0506","P0171"],
        professionalHelp: "If cleaning and relearn procedures don't fix stalling, a shop can test the IAC with a scan tool and confirm whether it is commanding correctly.",
        relatedProblems: ["IAC Valve","Throttle Body","Vacuum Leak","Fuel Pressure"],
      },
    },
  },

  // ─── Misfire ─────────────────────────────────────────────────────────────────
  misfire: {
    start: "q_light",
    nodes: {
      q_light: {
        question: "Is the check engine light on?",
        options: [
          { label: "Yes — flashing / blinking",                            next: "result_flash_stop" },
          { label: "Yes — steady on",                                      next: "q_codes" },
          { label: "No check engine light",                                next: "q_when" },
        ],
      },
      q_codes: {
        question: "Have you scanned for codes?",
        options: [
          { label: "Yes — P0301 through P0308 (specific cylinder)",        next: "result_specific" },
          { label: "Yes — P0300 (random / multiple cylinders)",            next: "result_random" },
          { label: "Not yet — haven't scanned",                            next: "result_scan_misfire" },
        ],
      },
      q_when: {
        question: "When does the misfire happen?",
        options: [
          { label: "At idle only — smooth when driving",                   next: "result_idle_miss" },
          { label: "Only under acceleration or load",                      next: "result_load_miss" },
          { label: "All the time — idle and driving",                      next: "result_constant_miss" },
        ],
      },
    },
    results: {
      result_flash_stop: {
        title: "⚠️ STOP — Flashing CEL means active misfire damaging catalytic converter",
        probability: "Very high",
        why: "A flashing check engine light is the computer's emergency warning that unburned fuel is entering the catalytic converter. It can be destroyed in minutes at highway speed.",
        firstChecks: ["Pull over and stop driving as soon as it is safe to do so", "Do not drive at highway speeds", "Scan for codes immediately — P030X codes identify the cylinder", "Do not clear the code and keep driving"],
        tools: ["OBD-II scanner"],
        safety: ["⚠️ STOP DRIVING — catalytic converter damage and fire risk", "A hot catalytic converter is a fire hazard if parked near dry grass"],
        dtcCodes: ["P0300","P0301","P0302","P0303","P0304","P0305","P0306"],
        professionalHelp: "A flashing CEL is an emergency. Have the vehicle towed if you cannot diagnose it today.",
        relatedProblems: ["Ignition Coil","Spark Plug","Fuel Injector","Catalytic Converter"],
      },
      result_specific: {
        title: "Single-cylinder misfire — coil, plug, or injector on that cylinder",
        probability: "High",
        why: "A specific cylinder code (P0301–P0308) identifies exactly which cylinder is failing. The swap test isolates whether the fault follows the coil or stays on the cylinder.",
        firstChecks: [
          "Move the ignition coil from the misfiring cylinder to an adjacent cylinder",
          "Clear the code and test drive — if the misfire moves to the new cylinder, the coil is bad",
          "If the misfire stays on the same cylinder: inspect the spark plug — look for fouling, cracks, or worn electrode",
          "If coil and plug are fine: perform an injector balance test or listen with a mechanic's stethoscope",
        ],
        tools: ["OBD-II scanner", "Ratchet set to swap coils", "Torque wrench for plug reinstall"],
        safety: ["Allow engine to cool before removing ignition coils and plugs"],
        dtcCodes: ["P0301","P0302","P0303","P0304","P0305","P0306","P0307","P0308","P0351","P0352"],
        professionalHelp: "If swapping coil and replacing the plug doesn't fix it, an injector test or compression test is the next step — a shop can do this quickly.",
        relatedProblems: ["Ignition Coil","Spark Plug","Fuel Injector","Compression Test"],
      },
      result_random: {
        title: "Random / multiple misfire (P0300) — fuel, spark, or mechanical",
        probability: "Medium",
        why: "A P0300 random misfire without a specific cylinder is harder to isolate — it means multiple or rotating cylinders are misfiring, often from fuel delivery or an ignition system issue affecting all cylinders.",
        firstChecks: [
          "Check spark plug condition — replace if worn (check gap and electrode)",
          "Test fuel pressure — a weak pump drops under load causing random misfires",
          "Check for dirty or clogged fuel injectors",
          "Inspect ignition wires or coil-pack (distributor-style engines) for cracks",
        ],
        tools: ["OBD-II scanner with live misfire counters", "Fuel pressure gauge"],
        safety: ["Fuel pressure testing involves pressurized fuel — keep away from ignition sources"],
        dtcCodes: ["P0300","P0171","P0174"],
        professionalHelp: "If spark and fuel look good, a compression test is needed to rule out mechanical causes (timing chain, valve issues).",
        relatedProblems: ["Fuel Pressure","Spark Plugs","Fuel Injectors","Timing Chain"],
      },
      result_scan_misfire: {
        title: "Scan first — codes tell you which cylinder and guide the diagnosis",
        probability: "Scan required",
        why: "Misfire diagnosis without codes is guesswork. A free scan at AutoZone, O'Reilly, or NAPA gives you the cylinder number and any supporting codes in minutes.",
        firstChecks: ["Get a free scan at an auto parts store", "Write down all stored AND pending codes", "P030X identifies the cylinder — P0300 is random/multiple"],
        tools: ["OBD-II scanner (free at most auto parts stores)"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Scanning first saves money. Replacing parts without codes often means replacing the wrong part.",
        relatedProblems: ["Check Engine Light","Ignition Coil","Spark Plug","Fuel Injector"],
      },
      result_idle_miss: {
        title: "Idle-only misfire — vacuum leak or injector drip",
        probability: "Medium",
        why: "A misfire only at idle typically points to a vacuum leak (lean condition at low RPM), a sticking or leaking injector, or an IAC issue.",
        firstChecks: [
          "Scan for P0171 or P0174 — lean codes confirm a vacuum leak",
          "Spray carb cleaner carefully around intake seams at idle — RPM change = vacuum leak",
          "Check injector o-rings for leaks",
          "Clean the throttle body",
        ],
        tools: ["OBD-II scanner", "Carb cleaner"],
        safety: ["Keep carb cleaner away from hot exhaust — fire risk"],
        dtcCodes: ["P0300","P0171","P0174","P0505"],
        professionalHelp: "A smoke test finds vacuum leaks much faster than spray testing.",
        relatedProblems: ["Vacuum Leak","IAC Valve","Rough Idle","Fuel Injector"],
      },
      result_load_miss: {
        title: "Load/acceleration misfire — fuel delivery or worn ignition parts",
        probability: "Medium",
        why: "A misfire that appears only under load means the ignition system or fuel delivery can't keep up with demand. High-mileage spark plugs and weak fuel pumps are common causes.",
        firstChecks: [
          "Check spark plug condition and replace if worn or high mileage",
          "Test fuel pressure under load — should hold at the spec without dropping",
          "Check ignition coil output on COP (coil-on-plug) engines",
          "Scan for P0171/P0174 lean codes indicating fuel delivery weakness",
        ],
        tools: ["Fuel pressure gauge", "OBD-II scanner"],
        safety: ["Fuel testing involves pressurized fuel — keep away from ignition sources"],
        dtcCodes: ["P0300","P0171","P0174"],
        professionalHelp: "Load-testing the fuel pump and coil output requires a shop with live data capability.",
        relatedProblems: ["Fuel Pump","Spark Plugs","Ignition Coil","Lean Condition"],
      },
      result_constant_miss: {
        title: "Constant misfire — ignition coil, plug, or mechanical issue",
        probability: "High",
        why: "A misfire present at all RPMs suggests a coil or plug that has completely failed, or a mechanical issue like low compression on a cylinder.",
        firstChecks: [
          "Scan for codes — P030X will identify the cylinder",
          "Perform the coil swap test to determine if the misfire follows the coil",
          "Replace spark plug on the affected cylinder",
          "If coil and plug don't fix it, perform a compression test",
        ],
        tools: ["OBD-II scanner", "Compression tester", "Ratchet and plug socket"],
        safety: ["Engine must be warm for an accurate compression test, but cool enough to safely handle"],
        dtcCodes: ["P0300","P0301","P0302","P0303","P0304"],
        professionalHelp: "Low compression on one cylinder indicates valve or piston ring issues — requires professional engine diagnosis.",
        relatedProblems: ["Ignition Coil","Spark Plug","Compression Test","Fuel Injector"],
      },
    },
  },

  // ─── Charging System ─────────────────────────────────────────────────────────
  charging: {
    start: "q1",
    nodes: {
      q1: {
        question: "What is the main charging system symptom?",
        options: [
          { label: "Battery or ALT warning light on while driving",        next: "q_voltage" },
          { label: "Headlights dim at idle, brighten at higher RPM",       next: "result_dim_lights" },
          { label: "Battery died — won't start after normal use",          next: "result_battery_died" },
          { label: "Electronics flickering or erratic",                    next: "result_erratic" },
        ],
      },
      q_voltage: {
        question: "What does a multimeter read at the battery with the engine running?",
        options: [
          { label: "Below 13.0 V — below normal while running",           next: "result_low_charge" },
          { label: "13.5–14.8 V — normal charging range",                 next: "result_sensor_fault" },
          { label: "Above 15.0 V — above normal",                         next: "result_overcharge" },
          { label: "Haven't measured yet",                                 next: "result_measure_voltage" },
        ],
      },
    },
    results: {
      result_low_charge: {
        title: "Alternator not charging — voltage below 13 V at idle",
        probability: "High",
        why: "A healthy alternator produces 13.5–14.8 V at the battery with the engine running. Below 13 V means the alternator is not keeping up — the battery is powering the car and will eventually die.",
        firstChecks: [
          "Inspect the alternator drive belt — cracked, loose, or slipping?",
          "Check the large cable from alternator output terminal to the battery positive",
          "Listen for a growling or whining from the alternator — indicates bearing failure",
          "Have the alternator tested at an auto parts store (usually free)",
        ],
        tools: ["Multimeter", "Serpentine belt inspection"],
        safety: ["High current present — avoid shorting battery cables"],
        dtcCodes: ["P0620","P0622"],
        professionalHelp: "Alternator replacement is a straightforward shop job. Note belt routing before removal — take a photo.",
        relatedProblems: ["Serpentine Belt","Battery Replacement","Voltage Regulator","Battery Drain"],
      },
      result_sensor_fault: {
        title: "Voltage normal — sensor or intermittent alternator issue",
        probability: "Medium",
        why: "A charging light with normal voltage can indicate a battery current sensor fault, a loose connection, or an intermittent alternator issue that isn't present at the moment of testing.",
        firstChecks: [
          "Inspect battery terminals — corroded or loose terminals can trigger a false charging light",
          "Check the alternator output wire for damage or loose connections",
          "Scan for charging system codes",
          "Test voltage under full load: headlights + A/C + blower on high — voltage should stay above 13 V",
        ],
        tools: ["Multimeter", "OBD-II scanner"],
        safety: [],
        dtcCodes: ["P0620","P0562"],
        professionalHelp: "Intermittent charging issues that disappear during testing require a shop with live data monitoring to catch dropouts.",
        relatedProblems: ["Battery Terminal Cleaning","Alternator","Battery Current Sensor","Ground Cable"],
      },
      result_overcharge: {
        title: "Overcharging — voltage regulator failure inside alternator",
        probability: "High",
        why: "Over 15 V is dangerous. The internal voltage regulator has failed. Overcharging boils battery acid, damages electronics, and destroys light bulbs.",
        firstChecks: [
          "Confirm the reading with a known-good multimeter — verify the reading is real",
          "Have the alternator tested off the vehicle at an auto parts store",
          "Do not continue driving — electronics and battery damage risk",
        ],
        tools: ["Multimeter"],
        safety: ["Battery acid can boil and vent — keep sparks and flames away"],
        dtcCodes: ["P0563"],
        professionalHelp: "The alternator must be replaced — internal regulators cannot be serviced on most modern units.",
        relatedProblems: ["Alternator Replacement","Battery Replacement","ECM Damage","Fuse Inspection"],
      },
      result_dim_lights: {
        title: "Dim lights at idle — alternator output marginal or high-demand circuit",
        probability: "Medium",
        why: "Headlights that brighten as RPM rises indicate the alternator can barely keep up at idle. This is normal on some high-demand vehicles but often means a failing alternator, high battery drain, or a weak ground connection.",
        firstChecks: [
          "Measure voltage at idle with all accessories on — should be at least 13 V",
          "Check battery and alternator ground cables for corrosion",
          "Consider whether aftermarket audio equipment is drawing too much current at idle",
          "Have the alternator load-tested",
        ],
        tools: ["Multimeter"],
        safety: [],
        dtcCodes: ["P0620"],
        professionalHelp: "A high-output alternator may be needed for heavily accessorized vehicles. Have the charging system load-tested.",
        relatedProblems: ["Alternator Output","Ground Cables","Battery","Audio Accessories"],
      },
      result_battery_died: {
        title: "Battery died — determine whether alternator or battery is the cause",
        probability: "Medium",
        why: "A dead battery after normal use could mean the battery has failed, the alternator is not charging, or something is drawing power when the car is off (parasitic drain).",
        firstChecks: [
          "Jump-start and measure voltage at battery while running — under 13 V = alternator problem",
          "Have the battery load-tested — batteries older than 5 years often fail suddenly",
          "After a 30-minute drive, check whether it starts again the next day",
          "If it keeps dying, measure parasitic draw: should be under 50 mA with key off and modules asleep",
        ],
        tools: ["Jumper cables", "Multimeter"],
        safety: ["Connect jumper cables in correct order — positive first, ground last"],
        dtcCodes: ["P0562"],
        professionalHelp: "Auto parts stores test batteries and alternators for free. Use this resource before buying anything.",
        relatedProblems: ["Parasitic Drain","Alternator","Battery Age","Short Trips"],
      },
      result_erratic: {
        title: "Flickering electronics — loose connection or failing alternator",
        probability: "Medium",
        why: "Erratic, flickering, or resetting electronics while driving are a sign the electrical system voltage is fluctuating — loose alternator connections, failing voltage regulator, or a compromised battery.",
        firstChecks: [
          "Check alternator output terminal bolt — must be tight",
          "Inspect battery terminals for corrosion or looseness",
          "Measure voltage while driving — should stay 13.5–14.8 V steadily",
          "Check battery ground cable to chassis and engine",
        ],
        tools: ["Multimeter", "Torque wrench for terminal bolts"],
        safety: [],
        dtcCodes: ["P0562","P0620"],
        professionalHelp: "Voltage fluctuation that causes module resets can damage the PCM long-term. Have the charging system load-tested.",
        relatedProblems: ["Ground Cables","Alternator","Battery Terminal","PCM/ECM Issues"],
      },
      result_measure_voltage: {
        title: "Measure voltage first — 30 seconds tells you the whole story",
        probability: "Test required",
        why: "The alternator light without a voltage reading is a starting point, not a diagnosis. One multimeter test tells you everything.",
        firstChecks: [
          "Key off — battery should read 12.4 V or higher",
          "Engine running — should read 13.5–14.8 V",
          "Under 13 V running = alternator not charging",
          "Over 15 V running = regulator failure",
          "Free charging system tests available at AutoZone, O'Reilly, and NAPA",
        ],
        tools: ["Multimeter (or free test at auto parts store)"],
        safety: [],
        dtcCodes: [],
        professionalHelp: "Free charging system tests at auto parts stores use professional load-testing equipment — use it before buying any parts.",
        relatedProblems: ["Alternator Test","Battery Test","Charging Light","Voltage Regulator"],
      },
    },
  },
};

// ── Related Problems Map ──────────────────────────────────────────────────────
// Used in the wizard result screen to suggest related issues to explore.
export const RELATED_PROBLEMS = {
  noStart:      ["Battery / Charging", "Fuel Pump Failure", "Cam / Crank Sensor", "Ignition Switch", "Security / Immobilizer"],
  checkEngine:  ["Misfire", "Rough Idle", "Catalytic Converter (P0420)", "Evap Leak (P0455)", "O2 Sensor"],
  overheat:     ["Cooling Fan Failure", "Thermostat Stuck Closed", "Water Pump", "Head Gasket Leak", "Low Coolant Level"],
  acNotCold:    ["Compressor Clutch Failure", "Condenser Fan", "Refrigerant Leak", "Blend Door Actuator", "Cabin Air Filter"],
  battery:      ["Charging System", "Parasitic Drain", "Alternator Belt", "Battery Age", "Short Trip Charging"],
  brakes:       ["ABS Sensor", "Brake Fluid Flush", "Rotor Thickness", "Caliper Piston Sticking", "Brake Line Inspection"],
  suspension:   ["Wheel Bearing", "Ball Joint", "Tie Rod End", "Strut Mount", "Wheel Alignment"],
  transmission: ["Transmission Fluid Change", "Shift Solenoid", "Torque Converter", "Speed Sensor", "Valve Body"],
  roughIdle:    ["Misfire", "Vacuum Leak", "Throttle Body Cleaning", "IAC Valve", "MAF Sensor"],
  misfire:      ["Rough Idle", "Check Engine Light", "Ignition Coil", "Spark Plugs", "Fuel Pressure"],
  charging:     ["Battery Replacement", "Alternator Belt", "Parasitic Drain", "Ground Cables", "Voltage Regulator"],
};
