// HoundMoto Vehicle Directory — recognition-only database (~1950–present)
// Used to confirm a vehicle exists even when detailed specs are unavailable.
// Fields: make, model, yearStart, yearEnd, type (car/truck/suv/van/hybrid/ev)

export const vehicleDirectory = [
  // ── Ford ──────────────────────────────────────────────────────────────────
  { make:"Ford", model:"F-100",            yearStart:1953, yearEnd:1983, type:"truck" },
  { make:"Ford", model:"F-150",            yearStart:1975, yearEnd:2025, type:"truck", aliases:["f150","f 150"] },
  { make:"Ford", model:"F-250",            yearStart:1953, yearEnd:2025, type:"truck", aliases:["f250","f 250"] },
  { make:"Ford", model:"F-250 Super Duty", yearStart:1999, yearEnd:2025, type:"truck" },
  { make:"Ford", model:"F-350",            yearStart:1953, yearEnd:2025, type:"truck", aliases:["f350","f 350"] },
  { make:"Ford", model:"F-350 Super Duty", yearStart:1999, yearEnd:2025, type:"truck" },
  { make:"Ford", model:"F-450",            yearStart:1998, yearEnd:2025, type:"truck" },
  { make:"Ford", model:"Mustang",          yearStart:1964, yearEnd:2025, type:"car",   aliases:["stang"] },
  { make:"Ford", model:"Mustang Mach-E",   yearStart:2020, yearEnd:2025, type:"ev",    aliases:["mach-e","mach e"] },
  { make:"Ford", model:"Thunderbird",      yearStart:1955, yearEnd:2005, type:"car",   aliases:["t-bird","tbird"] },
  { make:"Ford", model:"Bronco",           yearStart:1966, yearEnd:1996, type:"suv" },
  { make:"Ford", model:"Bronco",           yearStart:2021, yearEnd:2025, type:"suv" },
  { make:"Ford", model:"Bronco Sport",     yearStart:2020, yearEnd:2025, type:"suv" },
  { make:"Ford", model:"Explorer",         yearStart:1990, yearEnd:2025, type:"suv" },
  { make:"Ford", model:"Expedition",       yearStart:1996, yearEnd:2025, type:"suv" },
  { make:"Ford", model:"Edge",             yearStart:2006, yearEnd:2024, type:"suv" },
  { make:"Ford", model:"Escape",           yearStart:2000, yearEnd:2025, type:"suv" },
  { make:"Ford", model:"EcoSport",         yearStart:2018, yearEnd:2022, type:"suv" },
  { make:"Ford", model:"Focus",            yearStart:1998, yearEnd:2018, type:"car" },
  { make:"Ford", model:"Fusion",           yearStart:2005, yearEnd:2020, type:"car" },
  { make:"Ford", model:"Taurus",           yearStart:1986, yearEnd:2019, type:"car" },
  { make:"Ford", model:"Maverick",         yearStart:1969, yearEnd:1977, type:"car" },
  { make:"Ford", model:"Maverick",         yearStart:2021, yearEnd:2025, type:"truck" },
  { make:"Ford", model:"Ranger",           yearStart:1982, yearEnd:2025, type:"truck" },
  { make:"Ford", model:"Sport Trac",       yearStart:2000, yearEnd:2010, type:"truck" },
  { make:"Ford", model:"Transit",          yearStart:2014, yearEnd:2025, type:"van" },
  { make:"Ford", model:"Transit Connect",  yearStart:2010, yearEnd:2025, type:"van" },
  { make:"Ford", model:"E-Series",         yearStart:1961, yearEnd:2014, type:"van",   aliases:["econoline","e150","e250","e350"] },
  { make:"Ford", model:"Crown Victoria",   yearStart:1991, yearEnd:2011, type:"car",   aliases:["crown vic"] },
  { make:"Ford", model:"LTD Crown Victoria",yearStart:1983, yearEnd:1991,type:"car" },
  { make:"Ford", model:"LTD",              yearStart:1965, yearEnd:1986, type:"car" },
  { make:"Ford", model:"Fairlane",         yearStart:1955, yearEnd:1970, type:"car" },
  { make:"Ford", model:"Galaxie",          yearStart:1958, yearEnd:1974, type:"car" },
  { make:"Ford", model:"Torino",           yearStart:1968, yearEnd:1976, type:"car" },
  { make:"Ford", model:"Pinto",            yearStart:1971, yearEnd:1980, type:"car" },
  { make:"Ford", model:"Granada",          yearStart:1975, yearEnd:1982, type:"car" },
  { make:"Ford", model:"Tempo",            yearStart:1984, yearEnd:1994, type:"car" },
  { make:"Ford", model:"Probe",            yearStart:1988, yearEnd:1997, type:"car" },
  { make:"Ford", model:"Aerostar",         yearStart:1985, yearEnd:1997, type:"van" },
  { make:"Ford", model:"Windstar",         yearStart:1994, yearEnd:2003, type:"van" },
  { make:"Ford", model:"Freestar",         yearStart:2004, yearEnd:2007, type:"van" },
  { make:"Ford", model:"Flex",             yearStart:2008, yearEnd:2019, type:"suv" },
  { make:"Ford", model:"Five Hundred",     yearStart:2004, yearEnd:2007, type:"car" },
  { make:"Ford", model:"Freestyle",        yearStart:2004, yearEnd:2007, type:"suv" },
  { make:"Ford", model:"Contour",          yearStart:1994, yearEnd:2000, type:"car" },
  { make:"Ford", model:"Aspire",           yearStart:1993, yearEnd:1997, type:"car" },
  { make:"Ford", model:"Festiva",          yearStart:1987, yearEnd:1993, type:"car" },
  { make:"Ford", model:"Escort",           yearStart:1981, yearEnd:2003, type:"car" },
  { make:"Ford", model:"Bronco II",        yearStart:1983, yearEnd:1990, type:"suv" },

  // ── Chevrolet ─────────────────────────────────────────────────────────────
  { make:"Chevrolet", model:"Silverado 1500",   yearStart:1999, yearEnd:2025, type:"truck", aliases:["silverado","chevy silverado"] },
  { make:"Chevrolet", model:"Silverado 2500HD", yearStart:1999, yearEnd:2025, type:"truck" },
  { make:"Chevrolet", model:"Silverado 3500HD", yearStart:2001, yearEnd:2025, type:"truck" },
  { make:"Chevrolet", model:"C10",              yearStart:1960, yearEnd:1987, type:"truck", aliases:["c-10"] },
  { make:"Chevrolet", model:"K10",              yearStart:1960, yearEnd:1987, type:"truck" },
  { make:"Chevrolet", model:"C/K",              yearStart:1960, yearEnd:1998, type:"truck" },
  { make:"Chevrolet", model:"Camaro",           yearStart:1966, yearEnd:2024, type:"car" },
  { make:"Chevrolet", model:"Corvette",         yearStart:1953, yearEnd:2025, type:"car" },
  { make:"Chevrolet", model:"Impala",           yearStart:1958, yearEnd:2020, type:"car" },
  { make:"Chevrolet", model:"Caprice",          yearStart:1965, yearEnd:1996, type:"car" },
  { make:"Chevrolet", model:"Malibu",           yearStart:1964, yearEnd:1983, type:"car" },
  { make:"Chevrolet", model:"Malibu",           yearStart:1997, yearEnd:2024, type:"car" },
  { make:"Chevrolet", model:"Suburban",         yearStart:1935, yearEnd:2025, type:"suv",   aliases:["chevy suburban"] },
  { make:"Chevrolet", model:"Tahoe",            yearStart:1994, yearEnd:2025, type:"suv",   aliases:["chevy tahoe"] },
  { make:"Chevrolet", model:"Blazer",           yearStart:1969, yearEnd:1994, type:"suv" },
  { make:"Chevrolet", model:"S-10 Blazer",      yearStart:1983, yearEnd:2005, type:"suv",   aliases:["s10 blazer"] },
  { make:"Chevrolet", model:"Blazer",           yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Chevrolet", model:"TrailBlazer",      yearStart:2001, yearEnd:2009, type:"suv" },
  { make:"Chevrolet", model:"TrailBlazer",      yearStart:2020, yearEnd:2025, type:"suv" },
  { make:"Chevrolet", model:"Colorado",         yearStart:2003, yearEnd:2025, type:"truck" },
  { make:"Chevrolet", model:"S-10",             yearStart:1981, yearEnd:2004, type:"truck",  aliases:["s10"] },
  { make:"Chevrolet", model:"Corvair",          yearStart:1960, yearEnd:1969, type:"car" },
  { make:"Chevrolet", model:"Nova",             yearStart:1962, yearEnd:1979, type:"car" },
  { make:"Chevrolet", model:"Chevelle",         yearStart:1964, yearEnd:1977, type:"car" },
  { make:"Chevrolet", model:"Monte Carlo",      yearStart:1970, yearEnd:2007, type:"car" },
  { make:"Chevrolet", model:"El Camino",        yearStart:1959, yearEnd:1987, type:"truck" },
  { make:"Chevrolet", model:"Cavalier",         yearStart:1982, yearEnd:2005, type:"car" },
  { make:"Chevrolet", model:"Cobalt",           yearStart:2004, yearEnd:2010, type:"car" },
  { make:"Chevrolet", model:"Cruze",            yearStart:2010, yearEnd:2019, type:"car" },
  { make:"Chevrolet", model:"Equinox",          yearStart:2004, yearEnd:2025, type:"suv" },
  { make:"Chevrolet", model:"Traverse",         yearStart:2008, yearEnd:2025, type:"suv" },
  { make:"Chevrolet", model:"Trax",             yearStart:2013, yearEnd:2025, type:"suv" },
  { make:"Chevrolet", model:"Trailblazer",      yearStart:2020, yearEnd:2025, type:"suv" },
  { make:"Chevrolet", model:"Sonic",            yearStart:2011, yearEnd:2020, type:"car" },
  { make:"Chevrolet", model:"Spark",            yearStart:2012, yearEnd:2022, type:"car" },
  { make:"Chevrolet", model:"Volt",             yearStart:2010, yearEnd:2019, type:"hybrid" },
  { make:"Chevrolet", model:"Bolt EV",          yearStart:2016, yearEnd:2025, type:"ev",     aliases:["bolt"] },
  { make:"Chevrolet", model:"Bolt EUV",         yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Chevrolet", model:"Equinox EV",       yearStart:2024, yearEnd:2025, type:"ev" },
  { make:"Chevrolet", model:"Astro",            yearStart:1985, yearEnd:2005, type:"van" },
  { make:"Chevrolet", model:"Express",          yearStart:1996, yearEnd:2025, type:"van" },
  { make:"Chevrolet", model:"Bel Air",          yearStart:1950, yearEnd:1975, type:"car" },
  { make:"Chevrolet", model:"Biscayne",         yearStart:1958, yearEnd:1972, type:"car" },
  { make:"Chevrolet", model:"HHR",              yearStart:2005, yearEnd:2011, type:"car" },
  { make:"Chevrolet", model:"Aveo",             yearStart:2003, yearEnd:2011, type:"car" },
  { make:"Chevrolet", model:"Lumina",           yearStart:1989, yearEnd:2001, type:"car" },
  { make:"Chevrolet", model:"Celebrity",        yearStart:1982, yearEnd:1990, type:"car" },
  { make:"Chevrolet", model:"Citation",         yearStart:1980, yearEnd:1985, type:"car" },
  { make:"Chevrolet", model:"Vega",             yearStart:1970, yearEnd:1977, type:"car" },
  { make:"Chevrolet", model:"Nomad",            yearStart:1955, yearEnd:1961, type:"car" },
  { make:"Chevrolet", model:"Monza",            yearStart:1975, yearEnd:1980, type:"car" },
  { make:"Chevrolet", model:"Laguna",           yearStart:1973, yearEnd:1976, type:"car" },

  // ── GMC ───────────────────────────────────────────────────────────────────
  { make:"GMC", model:"Sierra 1500",   yearStart:1999, yearEnd:2025, type:"truck", aliases:["gmc sierra","sierra"] },
  { make:"GMC", model:"Sierra 2500HD", yearStart:1999, yearEnd:2025, type:"truck" },
  { make:"GMC", model:"Sierra 3500HD", yearStart:2001, yearEnd:2025, type:"truck" },
  { make:"GMC", model:"C/K",           yearStart:1960, yearEnd:1998, type:"truck" },
  { make:"GMC", model:"Canyon",        yearStart:2003, yearEnd:2025, type:"truck" },
  { make:"GMC", model:"Yukon",         yearStart:1991, yearEnd:2025, type:"suv",   aliases:["gmc yukon"] },
  { make:"GMC", model:"Yukon XL",      yearStart:1999, yearEnd:2025, type:"suv",   aliases:["yukon xl"] },
  { make:"GMC", model:"Terrain",       yearStart:2009, yearEnd:2025, type:"suv" },
  { make:"GMC", model:"Acadia",        yearStart:2006, yearEnd:2025, type:"suv" },
  { make:"GMC", model:"Envoy",         yearStart:1998, yearEnd:2009, type:"suv" },
  { make:"GMC", model:"Jimmy",         yearStart:1969, yearEnd:2005, type:"suv" },
  { make:"GMC", model:"S-15",          yearStart:1982, yearEnd:1990, type:"truck" },
  { make:"GMC", model:"Sonoma",        yearStart:1990, yearEnd:2004, type:"truck" },
  { make:"GMC", model:"Typhoon",       yearStart:1991, yearEnd:1993, type:"suv" },
  { make:"GMC", model:"Syclone",       yearStart:1991, yearEnd:1991, type:"truck" },
  { make:"GMC", model:"Safari",        yearStart:1985, yearEnd:2005, type:"van" },
  { make:"GMC", model:"Savana",        yearStart:1995, yearEnd:2025, type:"van" },
  { make:"GMC", model:"Hummer EV",     yearStart:2021, yearEnd:2025, type:"ev",   aliases:["hummer ev"] },
  { make:"GMC", model:"Envista",       yearStart:2024, yearEnd:2025, type:"suv" },

  // ── Dodge ─────────────────────────────────────────────────────────────────
  { make:"Dodge", model:"Ram 1500",      yearStart:1981, yearEnd:2011, type:"truck", aliases:["dodge ram","ram"] },
  { make:"Dodge", model:"Ram 2500",      yearStart:1981, yearEnd:2011, type:"truck" },
  { make:"Dodge", model:"Ram 3500",      yearStart:1981, yearEnd:2011, type:"truck" },
  { make:"Dodge", model:"D-Series",      yearStart:1948, yearEnd:1980, type:"truck", aliases:["d100","d200","d300"] },
  { make:"Dodge", model:"Challenger",    yearStart:1969, yearEnd:1974, type:"car" },
  { make:"Dodge", model:"Challenger",    yearStart:2008, yearEnd:2023, type:"car" },
  { make:"Dodge", model:"Charger",       yearStart:1966, yearEnd:1978, type:"car" },
  { make:"Dodge", model:"Charger",       yearStart:2005, yearEnd:2025, type:"car" },
  { make:"Dodge", model:"Dart",          yearStart:1959, yearEnd:1976, type:"car" },
  { make:"Dodge", model:"Dart",          yearStart:2012, yearEnd:2016, type:"car" },
  { make:"Dodge", model:"Viper",         yearStart:1991, yearEnd:2017, type:"car" },
  { make:"Dodge", model:"Durango",       yearStart:1997, yearEnd:2025, type:"suv" },
  { make:"Dodge", model:"Journey",       yearStart:2008, yearEnd:2020, type:"suv" },
  { make:"Dodge", model:"Avenger",       yearStart:2007, yearEnd:2014, type:"car" },
  { make:"Dodge", model:"Caliber",       yearStart:2006, yearEnd:2012, type:"car" },
  { make:"Dodge", model:"Neon",          yearStart:1994, yearEnd:2005, type:"car" },
  { make:"Dodge", model:"Stratus",       yearStart:1994, yearEnd:2006, type:"car" },
  { make:"Dodge", model:"Intrepid",      yearStart:1992, yearEnd:2004, type:"car" },
  { make:"Dodge", model:"Grand Caravan", yearStart:1984, yearEnd:2020, type:"van" },
  { make:"Dodge", model:"Caravan",       yearStart:1984, yearEnd:2007, type:"van" },
  { make:"Dodge", model:"Magnum",        yearStart:2004, yearEnd:2008, type:"car" },
  { make:"Dodge", model:"Nitro",         yearStart:2006, yearEnd:2011, type:"suv" },
  { make:"Dodge", model:"Dakota",        yearStart:1986, yearEnd:2011, type:"truck" },
  { make:"Dodge", model:"Coronet",       yearStart:1949, yearEnd:1976, type:"car" },
  { make:"Dodge", model:"Polara",        yearStart:1960, yearEnd:1973, type:"car" },
  { make:"Dodge", model:"Monaco",        yearStart:1965, yearEnd:1978, type:"car" },
  { make:"Dodge", model:"Super Bee",     yearStart:1968, yearEnd:1971, type:"car" },
  { make:"Dodge", model:"Shadow",        yearStart:1987, yearEnd:1994, type:"car" },
  { make:"Dodge", model:"Omni",          yearStart:1978, yearEnd:1990, type:"car" },
  { make:"Dodge", model:"Colt",          yearStart:1970, yearEnd:1994, type:"car" },
  { make:"Dodge", model:"Rampage",       yearStart:1981, yearEnd:1984, type:"truck" },
  { make:"Dodge", model:"ProMaster",     yearStart:2013, yearEnd:2025, type:"van" },
  { make:"Dodge", model:"Hornet",        yearStart:2022, yearEnd:2025, type:"suv" },

  // ── Ram ───────────────────────────────────────────────────────────────────
  { make:"Ram", model:"1500",          yearStart:2010, yearEnd:2025, type:"truck", aliases:["ram 1500"] },
  { make:"Ram", model:"2500",          yearStart:2010, yearEnd:2025, type:"truck" },
  { make:"Ram", model:"3500",          yearStart:2010, yearEnd:2025, type:"truck" },
  { make:"Ram", model:"ProMaster",     yearStart:2013, yearEnd:2025, type:"van" },
  { make:"Ram", model:"ProMaster City",yearStart:2015, yearEnd:2022, type:"van" },
  { make:"Ram", model:"1500 Classic",  yearStart:2019, yearEnd:2021, type:"truck" },

  // ── Jeep ──────────────────────────────────────────────────────────────────
  { make:"Jeep", model:"Wrangler",       yearStart:1986, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"CJ-5",           yearStart:1954, yearEnd:1983, type:"suv",  aliases:["cj5"] },
  { make:"Jeep", model:"CJ-7",           yearStart:1976, yearEnd:1986, type:"suv",  aliases:["cj7"] },
  { make:"Jeep", model:"Cherokee",       yearStart:1974, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"Grand Cherokee", yearStart:1992, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"Grand Wagoneer", yearStart:1962, yearEnd:1993, type:"suv" },
  { make:"Jeep", model:"Grand Wagoneer", yearStart:2021, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"Wagoneer",       yearStart:1962, yearEnd:1993, type:"suv" },
  { make:"Jeep", model:"Wagoneer",       yearStart:2021, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"Compass",        yearStart:2006, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"Renegade",       yearStart:2014, yearEnd:2025, type:"suv" },
  { make:"Jeep", model:"Liberty",        yearStart:2001, yearEnd:2012, type:"suv" },
  { make:"Jeep", model:"Gladiator",      yearStart:2019, yearEnd:2025, type:"truck" },
  { make:"Jeep", model:"Commander",      yearStart:2005, yearEnd:2010, type:"suv" },
  { make:"Jeep", model:"Patriot",        yearStart:2006, yearEnd:2017, type:"suv" },
  { make:"Jeep", model:"Scrambler",      yearStart:1981, yearEnd:1985, type:"truck", aliases:["cj-8","cj8"] },

  // ── Chrysler ──────────────────────────────────────────────────────────────
  { make:"Chrysler", model:"300",           yearStart:2004, yearEnd:2025, type:"car" },
  { make:"Chrysler", model:"300C",          yearStart:2005, yearEnd:2010, type:"car" },
  { make:"Chrysler", model:"300 Letter Series", yearStart:1955, yearEnd:1965, type:"car" },
  { make:"Chrysler", model:"Pacifica",      yearStart:2017, yearEnd:2025, type:"van" },
  { make:"Chrysler", model:"PT Cruiser",    yearStart:2000, yearEnd:2010, type:"car" },
  { make:"Chrysler", model:"Sebring",       yearStart:1994, yearEnd:2010, type:"car" },
  { make:"Chrysler", model:"200",           yearStart:2011, yearEnd:2017, type:"car" },
  { make:"Chrysler", model:"Town & Country",yearStart:1990, yearEnd:2016, type:"van" },
  { make:"Chrysler", model:"Concorde",      yearStart:1992, yearEnd:2004, type:"car" },
  { make:"Chrysler", model:"LHS",           yearStart:1994, yearEnd:2001, type:"car" },
  { make:"Chrysler", model:"New Yorker",    yearStart:1940, yearEnd:1996, type:"car" },
  { make:"Chrysler", model:"Imperial",      yearStart:1954, yearEnd:1983, type:"car" },
  { make:"Chrysler", model:"Crossfire",     yearStart:2003, yearEnd:2008, type:"car" },
  { make:"Chrysler", model:"Fifth Avenue",  yearStart:1979, yearEnd:1993, type:"car" },
  { make:"Chrysler", model:"Newport",       yearStart:1940, yearEnd:1981, type:"car" },
  { make:"Chrysler", model:"Cordoba",       yearStart:1975, yearEnd:1983, type:"car" },
  { make:"Chrysler", model:"Le Baron",      yearStart:1977, yearEnd:1995, type:"car" },
  { make:"Chrysler", model:"Aspen",         yearStart:2006, yearEnd:2008, type:"suv" },
  { make:"Chrysler", model:"Voyager",       yearStart:2019, yearEnd:2023, type:"van" },
  { make:"Chrysler", model:"300M",          yearStart:1999, yearEnd:2004, type:"car" },

  // ── Buick ─────────────────────────────────────────────────────────────────
  { make:"Buick", model:"LeSabre",    yearStart:1959, yearEnd:2005, type:"car" },
  { make:"Buick", model:"Riviera",    yearStart:1963, yearEnd:1999, type:"car" },
  { make:"Buick", model:"Electra",    yearStart:1959, yearEnd:1990, type:"car" },
  { make:"Buick", model:"Skylark",    yearStart:1953, yearEnd:1998, type:"car" },
  { make:"Buick", model:"Century",    yearStart:1936, yearEnd:2005, type:"car" },
  { make:"Buick", model:"Regal",      yearStart:1973, yearEnd:2025, type:"car" },
  { make:"Buick", model:"Park Avenue",yearStart:1991, yearEnd:2005, type:"car" },
  { make:"Buick", model:"LaCrosse",   yearStart:2004, yearEnd:2019, type:"car" },
  { make:"Buick", model:"Enclave",    yearStart:2007, yearEnd:2025, type:"suv" },
  { make:"Buick", model:"Encore",     yearStart:2012, yearEnd:2025, type:"suv" },
  { make:"Buick", model:"Encore GX",  yearStart:2020, yearEnd:2025, type:"suv" },
  { make:"Buick", model:"Verano",     yearStart:2011, yearEnd:2017, type:"car" },
  { make:"Buick", model:"Envision",   yearStart:2015, yearEnd:2025, type:"suv" },
  { make:"Buick", model:"Rainier",    yearStart:2003, yearEnd:2007, type:"suv" },
  { make:"Buick", model:"Rendezvous", yearStart:2001, yearEnd:2007, type:"suv" },
  { make:"Buick", model:"Terraza",    yearStart:2004, yearEnd:2007, type:"van" },
  { make:"Buick", model:"Lucerne",    yearStart:2005, yearEnd:2011, type:"car" },
  { make:"Buick", model:"Cascada",    yearStart:2015, yearEnd:2019, type:"car" },
  { make:"Buick", model:"Reatta",     yearStart:1987, yearEnd:1991, type:"car" },
  { make:"Buick", model:"Somerset",   yearStart:1985, yearEnd:1987, type:"car" },
  { make:"Buick", model:"Wildcat",    yearStart:1962, yearEnd:1970, type:"car" },
  { make:"Buick", model:"Special",    yearStart:1955, yearEnd:1972, type:"car" },
  { make:"Buick", model:"Gran Sport", yearStart:1965, yearEnd:1972, type:"car" },
  { make:"Buick", model:"Envista",    yearStart:2024, yearEnd:2025, type:"suv" },

  // ── Cadillac ──────────────────────────────────────────────────────────────
  { make:"Cadillac", model:"DeVille",     yearStart:1949, yearEnd:2005, type:"car",  aliases:["deville"] },
  { make:"Cadillac", model:"DTS",         yearStart:2005, yearEnd:2011, type:"car" },
  { make:"Cadillac", model:"Escalade",    yearStart:1998, yearEnd:2025, type:"suv" },
  { make:"Cadillac", model:"Escalade ESV",yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Cadillac", model:"SRX",         yearStart:2003, yearEnd:2016, type:"suv" },
  { make:"Cadillac", model:"XT5",         yearStart:2016, yearEnd:2025, type:"suv" },
  { make:"Cadillac", model:"XT4",         yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Cadillac", model:"XT6",         yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Cadillac", model:"CTS",         yearStart:2002, yearEnd:2019, type:"car" },
  { make:"Cadillac", model:"CT5",         yearStart:2019, yearEnd:2025, type:"car" },
  { make:"Cadillac", model:"ATS",         yearStart:2012, yearEnd:2019, type:"car" },
  { make:"Cadillac", model:"CT4",         yearStart:2019, yearEnd:2025, type:"car" },
  { make:"Cadillac", model:"CT6",         yearStart:2015, yearEnd:2023, type:"car" },
  { make:"Cadillac", model:"Fleetwood",   yearStart:1984, yearEnd:1996, type:"car" },
  { make:"Cadillac", model:"Eldorado",    yearStart:1952, yearEnd:2002, type:"car" },
  { make:"Cadillac", model:"Seville",     yearStart:1975, yearEnd:2004, type:"car" },
  { make:"Cadillac", model:"XLR",         yearStart:2003, yearEnd:2009, type:"car" },
  { make:"Cadillac", model:"Catera",      yearStart:1996, yearEnd:2001, type:"car" },
  { make:"Cadillac", model:"Allante",     yearStart:1986, yearEnd:1993, type:"car" },
  { make:"Cadillac", model:"Cimarron",    yearStart:1981, yearEnd:1988, type:"car" },
  { make:"Cadillac", model:"ELR",         yearStart:2013, yearEnd:2016, type:"hybrid" },
  { make:"Cadillac", model:"Lyriq",       yearStart:2022, yearEnd:2025, type:"ev" },

  // ── Pontiac ───────────────────────────────────────────────────────────────
  { make:"Pontiac", model:"GTO",         yearStart:1964, yearEnd:2006, type:"car" },
  { make:"Pontiac", model:"Firebird",    yearStart:1967, yearEnd:2002, type:"car" },
  { make:"Pontiac", model:"Trans Am",    yearStart:1969, yearEnd:2002, type:"car" },
  { make:"Pontiac", model:"Grand Prix",  yearStart:1962, yearEnd:2008, type:"car" },
  { make:"Pontiac", model:"Grand Am",    yearStart:1973, yearEnd:2005, type:"car" },
  { make:"Pontiac", model:"Bonneville",  yearStart:1957, yearEnd:2005, type:"car" },
  { make:"Pontiac", model:"Catalina",    yearStart:1950, yearEnd:1981, type:"car" },
  { make:"Pontiac", model:"Tempest",     yearStart:1960, yearEnd:1970, type:"car" },
  { make:"Pontiac", model:"LeMans",      yearStart:1962, yearEnd:1981, type:"car" },
  { make:"Pontiac", model:"Sunbird",     yearStart:1975, yearEnd:1994, type:"car" },
  { make:"Pontiac", model:"Sunfire",     yearStart:1994, yearEnd:2005, type:"car" },
  { make:"Pontiac", model:"Aztek",       yearStart:2000, yearEnd:2005, type:"suv" },
  { make:"Pontiac", model:"Montana",     yearStart:1999, yearEnd:2005, type:"van" },
  { make:"Pontiac", model:"Trans Sport", yearStart:1990, yearEnd:1999, type:"van" },
  { make:"Pontiac", model:"Vibe",        yearStart:2002, yearEnd:2010, type:"car" },
  { make:"Pontiac", model:"Torrent",     yearStart:2005, yearEnd:2009, type:"suv" },
  { make:"Pontiac", model:"Solstice",    yearStart:2005, yearEnd:2009, type:"car" },
  { make:"Pontiac", model:"G6",          yearStart:2004, yearEnd:2010, type:"car" },
  { make:"Pontiac", model:"G5",          yearStart:2007, yearEnd:2010, type:"car" },
  { make:"Pontiac", model:"G8",          yearStart:2007, yearEnd:2009, type:"car" },
  { make:"Pontiac", model:"Fiero",       yearStart:1984, yearEnd:1988, type:"car" },
  { make:"Pontiac", model:"Safari",      yearStart:1954, yearEnd:1979, type:"car" },
  { make:"Pontiac", model:"Star Chief",  yearStart:1954, yearEnd:1966, type:"car" },
  { make:"Pontiac", model:"Ventura",     yearStart:1971, yearEnd:1977, type:"car" },
  { make:"Pontiac", model:"Phoenix",     yearStart:1977, yearEnd:1984, type:"car" },

  // ── Oldsmobile ────────────────────────────────────────────────────────────
  { make:"Oldsmobile", model:"Cutlass Supreme", yearStart:1966, yearEnd:1997, type:"car" },
  { make:"Oldsmobile", model:"Cutlass Ciera",   yearStart:1982, yearEnd:1996, type:"car" },
  { make:"Oldsmobile", model:"442",             yearStart:1964, yearEnd:1980, type:"car" },
  { make:"Oldsmobile", model:"Delta 88",        yearStart:1949, yearEnd:1999, type:"car" },
  { make:"Oldsmobile", model:"98",              yearStart:1949, yearEnd:1996, type:"car" },
  { make:"Oldsmobile", model:"Toronado",        yearStart:1966, yearEnd:1992, type:"car" },
  { make:"Oldsmobile", model:"Bravada",         yearStart:1991, yearEnd:2004, type:"suv" },
  { make:"Oldsmobile", model:"Silhouette",      yearStart:1989, yearEnd:2004, type:"van" },
  { make:"Oldsmobile", model:"Alero",           yearStart:1999, yearEnd:2004, type:"car" },
  { make:"Oldsmobile", model:"Intrigue",        yearStart:1997, yearEnd:2002, type:"car" },
  { make:"Oldsmobile", model:"Aurora",          yearStart:1994, yearEnd:2003, type:"car" },
  { make:"Oldsmobile", model:"Achieva",         yearStart:1991, yearEnd:1998, type:"car" },
  { make:"Oldsmobile", model:"Calais",          yearStart:1985, yearEnd:1991, type:"car" },
  { make:"Oldsmobile", model:"F-85",            yearStart:1961, yearEnd:1972, type:"car" },
  { make:"Oldsmobile", model:"Vista Cruiser",   yearStart:1964, yearEnd:1977, type:"car" },
  { make:"Oldsmobile", model:"Starfire",        yearStart:1975, yearEnd:1980, type:"car" },
  { make:"Oldsmobile", model:"Omega",           yearStart:1973, yearEnd:1984, type:"car" },
  { make:"Oldsmobile", model:"Custom Cruiser",  yearStart:1971, yearEnd:1992, type:"car" },

  // ── Mercury ───────────────────────────────────────────────────────────────
  { make:"Mercury", model:"Grand Marquis", yearStart:1983, yearEnd:2011, type:"car" },
  { make:"Mercury", model:"Villager",      yearStart:1992, yearEnd:2002, type:"van" },
  { make:"Mercury", model:"Mountaineer",   yearStart:1997, yearEnd:2010, type:"suv" },
  { make:"Mercury", model:"Marquis",       yearStart:1979, yearEnd:1986, type:"car" },
  { make:"Mercury", model:"Cougar",        yearStart:1967, yearEnd:2002, type:"car" },
  { make:"Mercury", model:"Capri",         yearStart:1970, yearEnd:1986, type:"car" },
  { make:"Mercury", model:"Montego",       yearStart:1968, yearEnd:2007, type:"car" },
  { make:"Mercury", model:"Mystique",      yearStart:1994, yearEnd:2000, type:"car" },
  { make:"Mercury", model:"Sable",         yearStart:1986, yearEnd:2009, type:"car" },
  { make:"Mercury", model:"Tracer",        yearStart:1987, yearEnd:1999, type:"car" },
  { make:"Mercury", model:"Topaz",         yearStart:1983, yearEnd:1994, type:"car" },
  { make:"Mercury", model:"Comet",         yearStart:1960, yearEnd:1977, type:"car" },
  { make:"Mercury", model:"Cyclone",       yearStart:1964, yearEnd:1971, type:"car" },
  { make:"Mercury", model:"Colony Park",   yearStart:1957, yearEnd:1991, type:"car" },
  { make:"Mercury", model:"Bobcat",        yearStart:1974, yearEnd:1980, type:"car" },
  { make:"Mercury", model:"Lynx",          yearStart:1981, yearEnd:1987, type:"car" },
  { make:"Mercury", model:"Zephyr",        yearStart:1978, yearEnd:1983, type:"car" },
  { make:"Mercury", model:"Park Lane",     yearStart:1958, yearEnd:1960, type:"car" },

  // ── Lincoln ───────────────────────────────────────────────────────────────
  { make:"Lincoln", model:"Town Car",       yearStart:1981, yearEnd:2011, type:"car" },
  { make:"Lincoln", model:"Continental",    yearStart:1939, yearEnd:2020, type:"car" },
  { make:"Lincoln", model:"Navigator",      yearStart:1997, yearEnd:2025, type:"suv" },
  { make:"Lincoln", model:"MKS",            yearStart:2008, yearEnd:2016, type:"car" },
  { make:"Lincoln", model:"MKZ",            yearStart:2005, yearEnd:2020, type:"car" },
  { make:"Lincoln", model:"Zephyr",         yearStart:2006, yearEnd:2006, type:"car" },
  { make:"Lincoln", model:"MKX",            yearStart:2006, yearEnd:2018, type:"suv" },
  { make:"Lincoln", model:"Nautilus",       yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Lincoln", model:"MKC",            yearStart:2014, yearEnd:2019, type:"suv" },
  { make:"Lincoln", model:"Corsair",        yearStart:2020, yearEnd:2025, type:"suv" },
  { make:"Lincoln", model:"Aviator",        yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Lincoln", model:"Mark III",       yearStart:1968, yearEnd:1971, type:"car" },
  { make:"Lincoln", model:"Mark IV",        yearStart:1972, yearEnd:1976, type:"car" },
  { make:"Lincoln", model:"Mark V",         yearStart:1977, yearEnd:1979, type:"car" },
  { make:"Lincoln", model:"Mark VI",        yearStart:1980, yearEnd:1983, type:"car" },
  { make:"Lincoln", model:"Mark VII",       yearStart:1984, yearEnd:1992, type:"car" },
  { make:"Lincoln", model:"Mark VIII",      yearStart:1992, yearEnd:1998, type:"car" },
  { make:"Lincoln", model:"Versailles",     yearStart:1977, yearEnd:1980, type:"car" },
  { make:"Lincoln", model:"Blackwood",      yearStart:2001, yearEnd:2002, type:"truck" },
  { make:"Lincoln", model:"Star",           yearStart:2021, yearEnd:2025, type:"suv" },

  // ── Plymouth ──────────────────────────────────────────────────────────────
  { make:"Plymouth", model:"Barracuda",  yearStart:1964, yearEnd:1974, type:"car" },
  { make:"Plymouth", model:"Road Runner",yearStart:1968, yearEnd:1975, type:"car" },
  { make:"Plymouth", model:"GTX",        yearStart:1967, yearEnd:1971, type:"car" },
  { make:"Plymouth", model:"Belvedere",  yearStart:1951, yearEnd:1970, type:"car" },
  { make:"Plymouth", model:"Fury",       yearStart:1956, yearEnd:1978, type:"car" },
  { make:"Plymouth", model:"Valiant",    yearStart:1960, yearEnd:1976, type:"car" },
  { make:"Plymouth", model:"Duster",     yearStart:1970, yearEnd:1976, type:"car" },
  { make:"Plymouth", model:"Satellite",  yearStart:1965, yearEnd:1974, type:"car" },
  { make:"Plymouth", model:"Voyager",    yearStart:1974, yearEnd:2000, type:"van" },
  { make:"Plymouth", model:"Neon",       yearStart:1994, yearEnd:2001, type:"car" },
  { make:"Plymouth", model:"Breeze",     yearStart:1995, yearEnd:2000, type:"car" },
  { make:"Plymouth", model:"Prowler",    yearStart:1997, yearEnd:2002, type:"car" },
  { make:"Plymouth", model:"Acclaim",    yearStart:1989, yearEnd:1995, type:"car" },
  { make:"Plymouth", model:"Gran Fury",  yearStart:1974, yearEnd:1989, type:"car" },
  { make:"Plymouth", model:"Horizon",    yearStart:1977, yearEnd:1990, type:"car" },
  { make:"Plymouth", model:"Reliant",    yearStart:1981, yearEnd:1989, type:"car" },
  { make:"Plymouth", model:"Sundance",   yearStart:1986, yearEnd:1994, type:"car" },
  { make:"Plymouth", model:"Colt",       yearStart:1970, yearEnd:1994, type:"car" },
  { make:"Plymouth", model:"Cuda",       yearStart:1970, yearEnd:1974, type:"car" },

  // ── AMC ───────────────────────────────────────────────────────────────────
  { make:"AMC", model:"Javelin",    yearStart:1967, yearEnd:1974, type:"car" },
  { make:"AMC", model:"AMX",        yearStart:1968, yearEnd:1974, type:"car" },
  { make:"AMC", model:"Gremlin",    yearStart:1970, yearEnd:1978, type:"car" },
  { make:"AMC", model:"Pacer",      yearStart:1975, yearEnd:1980, type:"car" },
  { make:"AMC", model:"Hornet",     yearStart:1970, yearEnd:1977, type:"car" },
  { make:"AMC", model:"Spirit",     yearStart:1979, yearEnd:1983, type:"car" },
  { make:"AMC", model:"Eagle",      yearStart:1979, yearEnd:1987, type:"car" },
  { make:"AMC", model:"Ambassador", yearStart:1957, yearEnd:1974, type:"car" },
  { make:"AMC", model:"Concord",    yearStart:1977, yearEnd:1983, type:"car" },
  { make:"AMC", model:"Rebel",      yearStart:1967, yearEnd:1970, type:"car" },
  { make:"AMC", model:"Matador",    yearStart:1971, yearEnd:1978, type:"car" },
  { make:"AMC", model:"Rambler",    yearStart:1950, yearEnd:1969, type:"car" },

  // ── Toyota ────────────────────────────────────────────────────────────────
  { make:"Toyota", model:"Camry",       yearStart:1982, yearEnd:2025, type:"car" },
  { make:"Toyota", model:"Corolla",     yearStart:1966, yearEnd:2025, type:"car" },
  { make:"Toyota", model:"Prius",       yearStart:1997, yearEnd:2025, type:"hybrid" },
  { make:"Toyota", model:"Prius V",     yearStart:2011, yearEnd:2018, type:"hybrid" },
  { make:"Toyota", model:"Prius C",     yearStart:2011, yearEnd:2019, type:"hybrid" },
  { make:"Toyota", model:"Prius Prime", yearStart:2016, yearEnd:2025, type:"hybrid" },
  { make:"Toyota", model:"RAV4",        yearStart:1994, yearEnd:2025, type:"suv" },
  { make:"Toyota", model:"RAV4 Prime",  yearStart:2020, yearEnd:2025, type:"hybrid" },
  { make:"Toyota", model:"Highlander",  yearStart:2000, yearEnd:2025, type:"suv" },
  { make:"Toyota", model:"4Runner",     yearStart:1984, yearEnd:2025, type:"suv" },
  { make:"Toyota", model:"Tacoma",      yearStart:1995, yearEnd:2025, type:"truck" },
  { make:"Toyota", model:"Tundra",      yearStart:1999, yearEnd:2025, type:"truck" },
  { make:"Toyota", model:"Sequoia",     yearStart:2000, yearEnd:2025, type:"suv" },
  { make:"Toyota", model:"Sienna",      yearStart:1997, yearEnd:2025, type:"van" },
  { make:"Toyota", model:"Avalon",      yearStart:1994, yearEnd:2022, type:"car" },
  { make:"Toyota", model:"Venza",       yearStart:2008, yearEnd:2021, type:"suv" },
  { make:"Toyota", model:"Venza",       yearStart:2020, yearEnd:2025, type:"hybrid" },
  { make:"Toyota", model:"Land Cruiser",yearStart:1951, yearEnd:2025, type:"suv",  aliases:["landcruiser","lc"] },
  { make:"Toyota", model:"FJ Cruiser",  yearStart:2006, yearEnd:2014, type:"suv",  aliases:["fj"] },
  { make:"Toyota", model:"Matrix",      yearStart:2002, yearEnd:2014, type:"car" },
  { make:"Toyota", model:"Celica",      yearStart:1970, yearEnd:2006, type:"car" },
  { make:"Toyota", model:"Supra",       yearStart:1979, yearEnd:2002, type:"car" },
  { make:"Toyota", model:"Supra",       yearStart:2019, yearEnd:2025, type:"car" },
  { make:"Toyota", model:"MR2",         yearStart:1984, yearEnd:2007, type:"car" },
  { make:"Toyota", model:"Tercel",      yearStart:1978, yearEnd:1999, type:"car" },
  { make:"Toyota", model:"Echo",        yearStart:1999, yearEnd:2005, type:"car" },
  { make:"Toyota", model:"Yaris",       yearStart:1999, yearEnd:2020, type:"car" },
  { make:"Toyota", model:"C-HR",        yearStart:2016, yearEnd:2023, type:"suv" },
  { make:"Toyota", model:"Cressida",    yearStart:1976, yearEnd:1992, type:"car" },
  { make:"Toyota", model:"Crown",       yearStart:1955, yearEnd:2025, type:"car" },
  { make:"Toyota", model:"Mirai",       yearStart:2014, yearEnd:2025, type:"ev",    aliases:["hydrogen"] },
  { make:"Toyota", model:"bZ4X",        yearStart:2022, yearEnd:2025, type:"ev",    aliases:["bz4x"] },
  { make:"Toyota", model:"Camry Solara",yearStart:1998, yearEnd:2008, type:"car" },
  { make:"Toyota", model:"Paseo",       yearStart:1991, yearEnd:1999, type:"car" },
  { make:"Toyota", model:"T100",        yearStart:1992, yearEnd:1998, type:"truck" },
  { make:"Toyota", model:"Truck",       yearStart:1969, yearEnd:1995, type:"truck",  aliases:["hilux pickup","toyota pickup"] },
  { make:"Toyota", model:"Crown Signia",yearStart:2024, yearEnd:2025, type:"hybrid" },
  { make:"Toyota", model:"GR86",        yearStart:2021, yearEnd:2025, type:"car",    aliases:["gr 86"] },
  { make:"Toyota", model:"GR Corolla",  yearStart:2022, yearEnd:2025, type:"car" },
  { make:"Toyota", model:"GR Supra",    yearStart:2019, yearEnd:2025, type:"car" },

  // ── Honda ─────────────────────────────────────────────────────────────────
  { make:"Honda", model:"Accord",      yearStart:1976, yearEnd:2025, type:"car" },
  { make:"Honda", model:"Civic",       yearStart:1972, yearEnd:2025, type:"car" },
  { make:"Honda", model:"CR-V",        yearStart:1995, yearEnd:2025, type:"suv" },
  { make:"Honda", model:"Pilot",       yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Honda", model:"Odyssey",     yearStart:1994, yearEnd:2025, type:"van" },
  { make:"Honda", model:"Ridgeline",   yearStart:2005, yearEnd:2025, type:"truck" },
  { make:"Honda", model:"HR-V",        yearStart:1998, yearEnd:2025, type:"suv" },
  { make:"Honda", model:"Passport",    yearStart:1993, yearEnd:2002, type:"suv" },
  { make:"Honda", model:"Passport",    yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Honda", model:"Fit",         yearStart:2001, yearEnd:2020, type:"car",  aliases:["jazz"] },
  { make:"Honda", model:"Element",     yearStart:2002, yearEnd:2011, type:"suv" },
  { make:"Honda", model:"Insight",     yearStart:1999, yearEnd:2006, type:"hybrid" },
  { make:"Honda", model:"Insight",     yearStart:2018, yearEnd:2022, type:"hybrid" },
  { make:"Honda", model:"Clarity",     yearStart:2016, yearEnd:2021, type:"hybrid" },
  { make:"Honda", model:"Prelude",     yearStart:1978, yearEnd:2001, type:"car" },
  { make:"Honda", model:"Crosstour",   yearStart:2009, yearEnd:2015, type:"suv" },
  { make:"Honda", model:"CR-Z",        yearStart:2010, yearEnd:2016, type:"hybrid" },
  { make:"Honda", model:"S2000",       yearStart:1999, yearEnd:2009, type:"car" },
  { make:"Honda", model:"del Sol",     yearStart:1992, yearEnd:1997, type:"car" },
  { make:"Honda", model:"CRX",         yearStart:1983, yearEnd:1991, type:"car" },
  { make:"Honda", model:"Integra",     yearStart:1985, yearEnd:2001, type:"car" },
  { make:"Honda", model:"Integra",     yearStart:2022, yearEnd:2025, type:"car" },
  { make:"Honda", model:"Prologue",    yearStart:2024, yearEnd:2025, type:"ev" },
  { make:"Honda", model:"Breeze",      yearStart:2022, yearEnd:2025, type:"suv" },
  { make:"Honda", model:"ZR-V",        yearStart:2022, yearEnd:2025, type:"suv" },
  { make:"Honda", model:"Accord Hybrid",yearStart:2014, yearEnd:2025, type:"hybrid" },
  { make:"Honda", model:"CR-V Hybrid", yearStart:2019, yearEnd:2025, type:"hybrid" },

  // ── Nissan / Datsun ───────────────────────────────────────────────────────
  { make:"Nissan", model:"Altima",     yearStart:1992, yearEnd:2025, type:"car" },
  { make:"Nissan", model:"Sentra",     yearStart:1982, yearEnd:2025, type:"car" },
  { make:"Nissan", model:"Maxima",     yearStart:1980, yearEnd:2023, type:"car" },
  { make:"Nissan", model:"Frontier",   yearStart:1997, yearEnd:2025, type:"truck", aliases:["nissan pickup","hardbody"] },
  { make:"Nissan", model:"720",        yearStart:1979, yearEnd:1986, type:"truck", aliases:["datsun 720"] },
  { make:"Nissan", model:"Titan",      yearStart:2003, yearEnd:2025, type:"truck" },
  { make:"Nissan", model:"Pathfinder", yearStart:1986, yearEnd:2025, type:"suv" },
  { make:"Nissan", model:"Murano",     yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Nissan", model:"Rogue",      yearStart:2007, yearEnd:2025, type:"suv" },
  { make:"Nissan", model:"Rogue Sport", yearStart:2017, yearEnd:2023, type:"suv" },
  { make:"Nissan", model:"Xterra",     yearStart:1999, yearEnd:2015, type:"suv" },
  { make:"Nissan", model:"Armada",     yearStart:2003, yearEnd:2025, type:"suv" },
  { make:"Nissan", model:"350Z",       yearStart:2002, yearEnd:2009, type:"car",  aliases:["350-z"] },
  { make:"Nissan", model:"370Z",       yearStart:2009, yearEnd:2022, type:"car",  aliases:["370-z"] },
  { make:"Nissan", model:"Z",          yearStart:2022, yearEnd:2025, type:"car",  aliases:["nissan z"] },
  { make:"Nissan", model:"GT-R",       yearStart:2007, yearEnd:2022, type:"car",  aliases:["gtr"] },
  { make:"Nissan", model:"240Z",       yearStart:1969, yearEnd:1973, type:"car",  aliases:["datsun 240z"] },
  { make:"Nissan", model:"260Z",       yearStart:1974, yearEnd:1975, type:"car" },
  { make:"Nissan", model:"280Z",       yearStart:1975, yearEnd:1978, type:"car" },
  { make:"Nissan", model:"280ZX",      yearStart:1979, yearEnd:1983, type:"car" },
  { make:"Nissan", model:"300ZX",      yearStart:1983, yearEnd:1996, type:"car" },
  { make:"Nissan", model:"Versa",      yearStart:2006, yearEnd:2025, type:"car" },
  { make:"Nissan", model:"Juke",       yearStart:2010, yearEnd:2020, type:"suv" },
  { make:"Nissan", model:"Kicks",      yearStart:2016, yearEnd:2025, type:"suv" },
  { make:"Nissan", model:"Quest",      yearStart:1992, yearEnd:2017, type:"van" },
  { make:"Nissan", model:"Cube",       yearStart:2002, yearEnd:2019, type:"car" },
  { make:"Nissan", model:"Leaf",       yearStart:2010, yearEnd:2025, type:"ev" },
  { make:"Nissan", model:"Ariya",      yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Nissan", model:"NV",         yearStart:2010, yearEnd:2021, type:"van" },
  { make:"Nissan", model:"Stanza",     yearStart:1977, yearEnd:1992, type:"car" },
  { make:"Nissan", model:"Pulsar",     yearStart:1982, yearEnd:1994, type:"car" },
  { make:"Nissan", model:"Datsun 510", yearStart:1967, yearEnd:1973, type:"car", aliases:["510","bluebird"] },
  { make:"Nissan", model:"Datsun B210",yearStart:1973, yearEnd:1978, type:"car", aliases:["b210","honey bee"] },
  { make:"Nissan", model:"Datsun 610", yearStart:1972, yearEnd:1977, type:"car", aliases:["610"] },

  // ── Mazda ─────────────────────────────────────────────────────────────────
  { make:"Mazda", model:"CX-5",       yearStart:2012, yearEnd:2025, type:"suv" },
  { make:"Mazda", model:"CX-9",       yearStart:2006, yearEnd:2023, type:"suv" },
  { make:"Mazda", model:"CX-90",      yearStart:2023, yearEnd:2025, type:"suv" },
  { make:"Mazda", model:"CX-50",      yearStart:2022, yearEnd:2025, type:"suv" },
  { make:"Mazda", model:"CX-30",      yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Mazda", model:"CX-3",       yearStart:2015, yearEnd:2023, type:"suv" },
  { make:"Mazda", model:"Mazda3",     yearStart:2003, yearEnd:2025, type:"car",  aliases:["3","mazda 3"] },
  { make:"Mazda", model:"Mazda6",     yearStart:2002, yearEnd:2021, type:"car",  aliases:["6","mazda 6"] },
  { make:"Mazda", model:"Mazda2",     yearStart:2007, yearEnd:2015, type:"car",  aliases:["2","mazda 2"] },
  { make:"Mazda", model:"MX-5 Miata", yearStart:1989, yearEnd:2025, type:"car",  aliases:["miata","mx5","mx-5"] },
  { make:"Mazda", model:"RX-7",       yearStart:1978, yearEnd:2002, type:"car",  aliases:["rx7"] },
  { make:"Mazda", model:"RX-8",       yearStart:2003, yearEnd:2012, type:"car",  aliases:["rx8"] },
  { make:"Mazda", model:"626",        yearStart:1979, yearEnd:2002, type:"car" },
  { make:"Mazda", model:"323",        yearStart:1963, yearEnd:2003, type:"car",  aliases:["familia","protege"] },
  { make:"Mazda", model:"B-Series",   yearStart:1961, yearEnd:2010, type:"truck", aliases:["b2000","b2200","b2600","b3000","b4000"] },
  { make:"Mazda", model:"MPV",        yearStart:1988, yearEnd:2006, type:"van" },
  { make:"Mazda", model:"Tribute",    yearStart:2000, yearEnd:2011, type:"suv" },
  { make:"Mazda", model:"Mazda5",     yearStart:2005, yearEnd:2015, type:"van" },
  { make:"Mazda", model:"929",        yearStart:1987, yearEnd:1995, type:"car" },
  { make:"Mazda", model:"Millenia",   yearStart:1994, yearEnd:2002, type:"car" },
  { make:"Mazda", model:"GLC",        yearStart:1977, yearEnd:1985, type:"car" },
  { make:"Mazda", model:"MX-3",       yearStart:1991, yearEnd:1998, type:"car" },
  { make:"Mazda", model:"MX-6",       yearStart:1987, yearEnd:1997, type:"car" },
  { make:"Mazda", model:"CX-60",      yearStart:2022, yearEnd:2025, type:"suv" },
  { make:"Mazda", model:"MX-30",      yearStart:2020, yearEnd:2025, type:"ev" },

  // ── Subaru ────────────────────────────────────────────────────────────────
  { make:"Subaru", model:"Outback",    yearStart:1994, yearEnd:2025, type:"suv" },
  { make:"Subaru", model:"Forester",   yearStart:1997, yearEnd:2025, type:"suv" },
  { make:"Subaru", model:"Impreza",    yearStart:1992, yearEnd:2025, type:"car" },
  { make:"Subaru", model:"Legacy",     yearStart:1989, yearEnd:2025, type:"car" },
  { make:"Subaru", model:"WRX",        yearStart:1992, yearEnd:2025, type:"car" },
  { make:"Subaru", model:"WRX STI",    yearStart:2004, yearEnd:2022, type:"car",  aliases:["sti"] },
  { make:"Subaru", model:"BRZ",        yearStart:2012, yearEnd:2025, type:"car" },
  { make:"Subaru", model:"Crosstrek",  yearStart:2012, yearEnd:2025, type:"suv",  aliases:["xv","xv crosstrek"] },
  { make:"Subaru", model:"Ascent",     yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Subaru", model:"Baja",       yearStart:2002, yearEnd:2006, type:"truck" },
  { make:"Subaru", model:"Brat",       yearStart:1977, yearEnd:1994, type:"truck" },
  { make:"Subaru", model:"Justy",      yearStart:1984, yearEnd:1994, type:"car" },
  { make:"Subaru", model:"SVX",        yearStart:1991, yearEnd:1997, type:"car" },
  { make:"Subaru", model:"Leone",      yearStart:1971, yearEnd:1994, type:"car" },
  { make:"Subaru", model:"Tribeca",    yearStart:2005, yearEnd:2014, type:"suv" },
  { make:"Subaru", model:"Solterra",   yearStart:2022, yearEnd:2025, type:"ev" },

  // ── Mitsubishi ────────────────────────────────────────────────────────────
  { make:"Mitsubishi", model:"Eclipse",        yearStart:1989, yearEnd:2011, type:"car" },
  { make:"Mitsubishi", model:"Eclipse Cross",  yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"Mitsubishi", model:"Lancer",         yearStart:1973, yearEnd:2017, type:"car" },
  { make:"Mitsubishi", model:"Lancer Evolution",yearStart:1992, yearEnd:2016, type:"car", aliases:["evo","lancer evo"] },
  { make:"Mitsubishi", model:"Outlander",      yearStart:2001, yearEnd:2025, type:"suv" },
  { make:"Mitsubishi", model:"Outlander Sport",yearStart:2010, yearEnd:2023, type:"suv", aliases:["asx","rvr"] },
  { make:"Mitsubishi", model:"Galant",         yearStart:1969, yearEnd:2012, type:"car" },
  { make:"Mitsubishi", model:"Diamante",       yearStart:1990, yearEnd:2004, type:"car" },
  { make:"Mitsubishi", model:"3000GT",         yearStart:1990, yearEnd:2000, type:"car",  aliases:["gto","3000 gt"] },
  { make:"Mitsubishi", model:"Montero",        yearStart:1982, yearEnd:2006, type:"suv",  aliases:["pajero"] },
  { make:"Mitsubishi", model:"Raider",         yearStart:2006, yearEnd:2009, type:"truck" },
  { make:"Mitsubishi", model:"Endeavor",       yearStart:2003, yearEnd:2011, type:"suv" },
  { make:"Mitsubishi", model:"Mirage",         yearStart:1978, yearEnd:2025, type:"car" },
  { make:"Mitsubishi", model:"Mighty Max",     yearStart:1979, yearEnd:1996, type:"truck" },
  { make:"Mitsubishi", model:"Starion",        yearStart:1982, yearEnd:1989, type:"car" },
  { make:"Mitsubishi", model:"Precis",         yearStart:1985, yearEnd:1994, type:"car" },
  { make:"Mitsubishi", model:"Eclipse Spyder", yearStart:1996, yearEnd:2011, type:"car" },
  { make:"Mitsubishi", model:"Sigma",          yearStart:1990, yearEnd:1996, type:"car" },
  { make:"Mitsubishi", model:"PHEV",           yearStart:2018, yearEnd:2025, type:"hybrid", aliases:["outlander phev"] },

  // ── Isuzu ─────────────────────────────────────────────────────────────────
  { make:"Isuzu", model:"Trooper",    yearStart:1981, yearEnd:2002, type:"suv" },
  { make:"Isuzu", model:"Amigo",      yearStart:1989, yearEnd:2001, type:"suv" },
  { make:"Isuzu", model:"VehiCROSS",  yearStart:1998, yearEnd:2001, type:"suv" },
  { make:"Isuzu", model:"Rodeo",      yearStart:1989, yearEnd:2004, type:"suv" },
  { make:"Isuzu", model:"Passport",   yearStart:1994, yearEnd:2002, type:"suv" },
  { make:"Isuzu", model:"Hombre",     yearStart:1995, yearEnd:2000, type:"truck" },
  { make:"Isuzu", model:"Axiom",      yearStart:2001, yearEnd:2004, type:"suv" },
  { make:"Isuzu", model:"Ascender",   yearStart:2002, yearEnd:2008, type:"suv" },
  { make:"Isuzu", model:"i-Series",   yearStart:2005, yearEnd:2008, type:"truck", aliases:["isuzu i290","i370"] },
  { make:"Isuzu", model:"Pickup",     yearStart:1972, yearEnd:2001, type:"truck", aliases:["p'up","pup"] },
  { make:"Isuzu", model:"I-Mark",     yearStart:1985, yearEnd:1993, type:"car",  aliases:["gemini","stylus"] },
  { make:"Isuzu", model:"Impulse",    yearStart:1983, yearEnd:1993, type:"car",  aliases:["piazza"] },
  { make:"Isuzu", model:"Oasis",      yearStart:1996, yearEnd:1999, type:"van" },

  // ── Suzuki ────────────────────────────────────────────────────────────────
  { make:"Suzuki", model:"Samurai",     yearStart:1985, yearEnd:1995, type:"suv" },
  { make:"Suzuki", model:"Sidekick",    yearStart:1988, yearEnd:1998, type:"suv" },
  { make:"Suzuki", model:"Grand Vitara",yearStart:1997, yearEnd:2013, type:"suv" },
  { make:"Suzuki", model:"Vitara",      yearStart:1988, yearEnd:1997, type:"suv" },
  { make:"Suzuki", model:"Swift",       yearStart:1984, yearEnd:2001, type:"car" },
  { make:"Suzuki", model:"Forenza",     yearStart:2003, yearEnd:2008, type:"car" },
  { make:"Suzuki", model:"Reno",        yearStart:2004, yearEnd:2008, type:"car" },
  { make:"Suzuki", model:"Aerio",       yearStart:2001, yearEnd:2007, type:"car" },
  { make:"Suzuki", model:"XL-7",        yearStart:2001, yearEnd:2009, type:"suv" },
  { make:"Suzuki", model:"Kizashi",     yearStart:2009, yearEnd:2013, type:"car" },
  { make:"Suzuki", model:"Esteem",      yearStart:1994, yearEnd:2002, type:"car" },
  { make:"Suzuki", model:"X-90",        yearStart:1995, yearEnd:1998, type:"suv" },
  { make:"Suzuki", model:"Equator",     yearStart:2009, yearEnd:2012, type:"truck" },

  // ── Volkswagen ────────────────────────────────────────────────────────────
  { make:"Volkswagen", model:"Beetle",       yearStart:1950, yearEnd:2019, type:"car",  aliases:["bug","vw bug","vw beetle"] },
  { make:"Volkswagen", model:"Golf",         yearStart:1974, yearEnd:2025, type:"car",  aliases:["rabbit","vw golf"] },
  { make:"Volkswagen", model:"GTI",          yearStart:1975, yearEnd:2025, type:"car",  aliases:["vw gti"] },
  { make:"Volkswagen", model:"Jetta",        yearStart:1979, yearEnd:2025, type:"car",  aliases:["vw jetta"] },
  { make:"Volkswagen", model:"Passat",       yearStart:1973, yearEnd:2022, type:"car",  aliases:["vw passat"] },
  { make:"Volkswagen", model:"Tiguan",       yearStart:2007, yearEnd:2025, type:"suv" },
  { make:"Volkswagen", model:"Atlas",        yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"Volkswagen", model:"Atlas Cross Sport",yearStart:2020, yearEnd:2025, type:"suv" },
  { make:"Volkswagen", model:"Taos",         yearStart:2021, yearEnd:2025, type:"suv" },
  { make:"Volkswagen", model:"ID.4",         yearStart:2020, yearEnd:2025, type:"ev",   aliases:["id4","id 4"] },
  { make:"Volkswagen", model:"ID.Buzz",      yearStart:2022, yearEnd:2025, type:"ev",   aliases:["id buzz"] },
  { make:"Volkswagen", model:"Scirocco",     yearStart:1974, yearEnd:1992, type:"car" },
  { make:"Volkswagen", model:"Corrado",      yearStart:1988, yearEnd:1995, type:"car" },
  { make:"Volkswagen", model:"Phaeton",      yearStart:2002, yearEnd:2006, type:"car" },
  { make:"Volkswagen", model:"Touareg",      yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Volkswagen", model:"Routan",       yearStart:2008, yearEnd:2012, type:"van" },
  { make:"Volkswagen", model:"CC",           yearStart:2008, yearEnd:2017, type:"car" },
  { make:"Volkswagen", model:"Arteon",       yearStart:2017, yearEnd:2025, type:"car" },
  { make:"Volkswagen", model:"Eos",          yearStart:2006, yearEnd:2016, type:"car" },
  { make:"Volkswagen", model:"Cabriolet",    yearStart:1979, yearEnd:2002, type:"car" },
  { make:"Volkswagen", model:"Fox",          yearStart:1987, yearEnd:1993, type:"car" },
  { make:"Volkswagen", model:"Quantum",      yearStart:1982, yearEnd:1988, type:"car" },
  { make:"Volkswagen", model:"Vanagon",      yearStart:1980, yearEnd:1991, type:"van",  aliases:["t3","vw van"] },
  { make:"Volkswagen", model:"Eurovan",      yearStart:1992, yearEnd:2003, type:"van",  aliases:["t4"] },
  { make:"Volkswagen", model:"Golf SportWagen",yearStart:2010, yearEnd:2019, type:"car" },
  { make:"Volkswagen", model:"Alltrack",     yearStart:2016, yearEnd:2019, type:"car" },
  { make:"Volkswagen", model:"R32",          yearStart:2003, yearEnd:2008, type:"car" },
  { make:"Volkswagen", model:"Type 2",       yearStart:1950, yearEnd:1979, type:"van",  aliases:["microbus","bus","kombi","vw bus"] },
  { make:"Volkswagen", model:"Karmann-Ghia", yearStart:1955, yearEnd:1974, type:"car" },

  // ── BMW ───────────────────────────────────────────────────────────────────
  { make:"BMW", model:"1 Series",  yearStart:2004, yearEnd:2025, type:"car" },
  { make:"BMW", model:"2 Series",  yearStart:2013, yearEnd:2025, type:"car" },
  { make:"BMW", model:"3 Series",  yearStart:1975, yearEnd:2025, type:"car",  aliases:["e30","e36","e46","e90","f30","g20"] },
  { make:"BMW", model:"4 Series",  yearStart:2013, yearEnd:2025, type:"car" },
  { make:"BMW", model:"5 Series",  yearStart:1972, yearEnd:2025, type:"car",  aliases:["e28","e34","e39","e60","f10","g30"] },
  { make:"BMW", model:"6 Series",  yearStart:2003, yearEnd:2018, type:"car" },
  { make:"BMW", model:"7 Series",  yearStart:1977, yearEnd:2025, type:"car",  aliases:["e23","e32","e38","e65","f01","g11"] },
  { make:"BMW", model:"8 Series",  yearStart:1989, yearEnd:1999, type:"car" },
  { make:"BMW", model:"8 Series",  yearStart:2018, yearEnd:2025, type:"car" },
  { make:"BMW", model:"X1",        yearStart:2009, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"X2",        yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"X3",        yearStart:2003, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"X4",        yearStart:2014, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"X5",        yearStart:1999, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"X6",        yearStart:2007, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"X7",        yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"BMW", model:"Z3",        yearStart:1995, yearEnd:2002, type:"car" },
  { make:"BMW", model:"Z4",        yearStart:2002, yearEnd:2025, type:"car" },
  { make:"BMW", model:"Z8",        yearStart:1999, yearEnd:2003, type:"car" },
  { make:"BMW", model:"M3",        yearStart:1985, yearEnd:2025, type:"car" },
  { make:"BMW", model:"M4",        yearStart:2014, yearEnd:2025, type:"car" },
  { make:"BMW", model:"M5",        yearStart:1984, yearEnd:2025, type:"car" },
  { make:"BMW", model:"i3",        yearStart:2013, yearEnd:2021, type:"ev" },
  { make:"BMW", model:"i4",        yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"BMW", model:"iX",        yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"BMW", model:"i8",        yearStart:2014, yearEnd:2020, type:"hybrid" },
  { make:"BMW", model:"2002",      yearStart:1968, yearEnd:1976, type:"car" },
  { make:"BMW", model:"Bavaria",   yearStart:1968, yearEnd:1977, type:"car" },
  { make:"BMW", model:"M2",        yearStart:2015, yearEnd:2025, type:"car" },
  { make:"BMW", model:"M6",        yearStart:1983, yearEnd:2018, type:"car" },

  // ── Mercedes-Benz ─────────────────────────────────────────────────────────
  { make:"Mercedes-Benz", model:"C-Class",    yearStart:1993, yearEnd:2025, type:"car",  aliases:["c class","c200","c300","c63","190e","190"] },
  { make:"Mercedes-Benz", model:"E-Class",    yearStart:1984, yearEnd:2025, type:"car",  aliases:["e class","e300","e320","e350","e500","w123","w124"] },
  { make:"Mercedes-Benz", model:"S-Class",    yearStart:1972, yearEnd:2025, type:"car",  aliases:["s class","s500","s550","s600","450sel","560sel"] },
  { make:"Mercedes-Benz", model:"G-Class",    yearStart:1979, yearEnd:2025, type:"suv",  aliases:["g wagon","gwagon","g63","g550"] },
  { make:"Mercedes-Benz", model:"GLC",        yearStart:2015, yearEnd:2025, type:"suv",  aliases:["glk","glk250","glk350","glc300"] },
  { make:"Mercedes-Benz", model:"GLE",        yearStart:1997, yearEnd:2025, type:"suv",  aliases:["ml","ml320","ml350","ml500","ml63","gle350"] },
  { make:"Mercedes-Benz", model:"GLS",        yearStart:2006, yearEnd:2025, type:"suv",  aliases:["gl","gl450","gl550","gls450"] },
  { make:"Mercedes-Benz", model:"GLA",        yearStart:2013, yearEnd:2025, type:"suv",  aliases:["gla250"] },
  { make:"Mercedes-Benz", model:"GLB",        yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Mercedes-Benz", model:"CLA",        yearStart:2013, yearEnd:2025, type:"car",  aliases:["cla250"] },
  { make:"Mercedes-Benz", model:"A-Class",    yearStart:1997, yearEnd:2025, type:"car",  aliases:["a class","a220"] },
  { make:"Mercedes-Benz", model:"B-Class",    yearStart:2005, yearEnd:2019, type:"car" },
  { make:"Mercedes-Benz", model:"SL",         yearStart:1954, yearEnd:2025, type:"car",  aliases:["sl500","sl550","300sl","230sl","280sl"] },
  { make:"Mercedes-Benz", model:"SLK",        yearStart:1996, yearEnd:2015, type:"car",  aliases:["slk230","slk250","slk350"] },
  { make:"Mercedes-Benz", model:"SLC",        yearStart:2015, yearEnd:2020, type:"car" },
  { make:"Mercedes-Benz", model:"CLK",        yearStart:1997, yearEnd:2009, type:"car",  aliases:["clk320","clk430"] },
  { make:"Mercedes-Benz", model:"CLS",        yearStart:2004, yearEnd:2025, type:"car" },
  { make:"Mercedes-Benz", model:"AMG GT",     yearStart:2014, yearEnd:2025, type:"car" },
  { make:"Mercedes-Benz", model:"EQS",        yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Mercedes-Benz", model:"EQE",        yearStart:2022, yearEnd:2025, type:"ev" },
  { make:"Mercedes-Benz", model:"EQB",        yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Mercedes-Benz", model:"Sprinter",   yearStart:1995, yearEnd:2025, type:"van" },
  { make:"Mercedes-Benz", model:"Metris",     yearStart:2015, yearEnd:2023, type:"van" },
  { make:"Mercedes-Benz", model:"240D",       yearStart:1974, yearEnd:1983, type:"car" },
  { make:"Mercedes-Benz", model:"300D",       yearStart:1977, yearEnd:1985, type:"car" },
  { make:"Mercedes-Benz", model:"300E",       yearStart:1985, yearEnd:1993, type:"car" },
  { make:"Mercedes-Benz", model:"GLC Coupe",  yearStart:2016, yearEnd:2025, type:"suv" },
  { make:"Mercedes-Benz", model:"GLE Coupe",  yearStart:2015, yearEnd:2025, type:"suv" },

  // ── Audi ──────────────────────────────────────────────────────────────────
  { make:"Audi", model:"A3",       yearStart:1996, yearEnd:2025, type:"car" },
  { make:"Audi", model:"A4",       yearStart:1972, yearEnd:2025, type:"car",  aliases:["80","90"] },
  { make:"Audi", model:"A5",       yearStart:2007, yearEnd:2025, type:"car" },
  { make:"Audi", model:"A6",       yearStart:1968, yearEnd:2025, type:"car",  aliases:["100","5000"] },
  { make:"Audi", model:"A7",       yearStart:2010, yearEnd:2025, type:"car" },
  { make:"Audi", model:"A8",       yearStart:1994, yearEnd:2025, type:"car" },
  { make:"Audi", model:"Q3",       yearStart:2011, yearEnd:2025, type:"suv" },
  { make:"Audi", model:"Q5",       yearStart:2008, yearEnd:2025, type:"suv" },
  { make:"Audi", model:"Q7",       yearStart:2005, yearEnd:2025, type:"suv" },
  { make:"Audi", model:"Q8",       yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Audi", model:"TT",       yearStart:1998, yearEnd:2023, type:"car" },
  { make:"Audi", model:"R8",       yearStart:2006, yearEnd:2024, type:"car" },
  { make:"Audi", model:"e-tron",   yearStart:2018, yearEnd:2025, type:"ev",   aliases:["etron"] },
  { make:"Audi", model:"e-tron GT",yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Audi", model:"Q4 e-tron",yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Audi", model:"Allroad",  yearStart:2000, yearEnd:2025, type:"car" },
  { make:"Audi", model:"Fox",      yearStart:1973, yearEnd:1979, type:"car" },
  { make:"Audi", model:"4000",     yearStart:1979, yearEnd:1987, type:"car" },
  { make:"Audi", model:"5000",     yearStart:1977, yearEnd:1988, type:"car" },
  { make:"Audi", model:"Quattro",  yearStart:1980, yearEnd:1991, type:"car" },
  { make:"Audi", model:"S4",       yearStart:1991, yearEnd:2025, type:"car" },
  { make:"Audi", model:"S5",       yearStart:2007, yearEnd:2025, type:"car" },
  { make:"Audi", model:"S6",       yearStart:1994, yearEnd:2025, type:"car" },
  { make:"Audi", model:"S8",       yearStart:1994, yearEnd:2025, type:"car" },
  { make:"Audi", model:"RS5",      yearStart:2010, yearEnd:2025, type:"car" },
  { make:"Audi", model:"RS7",      yearStart:2013, yearEnd:2025, type:"car" },
  { make:"Audi", model:"SQ5",      yearStart:2013, yearEnd:2025, type:"suv" },
  { make:"Audi", model:"Q2",       yearStart:2016, yearEnd:2025, type:"suv" },

  // ── Porsche ───────────────────────────────────────────────────────────────
  { make:"Porsche", model:"911",       yearStart:1963, yearEnd:2025, type:"car",  aliases:["996","997","991","992"] },
  { make:"Porsche", model:"944",       yearStart:1982, yearEnd:1991, type:"car" },
  { make:"Porsche", model:"928",       yearStart:1977, yearEnd:1995, type:"car" },
  { make:"Porsche", model:"968",       yearStart:1991, yearEnd:1995, type:"car" },
  { make:"Porsche", model:"Boxster",   yearStart:1996, yearEnd:2025, type:"car",  aliases:["986","987","981","718"] },
  { make:"Porsche", model:"Cayman",    yearStart:2005, yearEnd:2025, type:"car" },
  { make:"Porsche", model:"Cayenne",   yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Porsche", model:"Macan",     yearStart:2014, yearEnd:2025, type:"suv" },
  { make:"Porsche", model:"Panamera",  yearStart:2009, yearEnd:2025, type:"car" },
  { make:"Porsche", model:"Taycan",    yearStart:2019, yearEnd:2025, type:"ev" },
  { make:"Porsche", model:"356",       yearStart:1950, yearEnd:1965, type:"car" },
  { make:"Porsche", model:"912",       yearStart:1965, yearEnd:1969, type:"car" },
  { make:"Porsche", model:"914",       yearStart:1969, yearEnd:1976, type:"car" },
  { make:"Porsche", model:"924",       yearStart:1976, yearEnd:1988, type:"car" },

  // ── Hyundai ───────────────────────────────────────────────────────────────
  { make:"Hyundai", model:"Elantra",  yearStart:1990, yearEnd:2025, type:"car" },
  { make:"Hyundai", model:"Sonata",   yearStart:1985, yearEnd:2025, type:"car" },
  { make:"Hyundai", model:"Tucson",   yearStart:2004, yearEnd:2025, type:"suv" },
  { make:"Hyundai", model:"Santa Fe", yearStart:2000, yearEnd:2025, type:"suv" },
  { make:"Hyundai", model:"Accent",   yearStart:1994, yearEnd:2025, type:"car" },
  { make:"Hyundai", model:"Veloster", yearStart:2011, yearEnd:2022, type:"car" },
  { make:"Hyundai", model:"Ioniq",    yearStart:2016, yearEnd:2022, type:"hybrid" },
  { make:"Hyundai", model:"Ioniq 5",  yearStart:2021, yearEnd:2025, type:"ev",    aliases:["ioniq5"] },
  { make:"Hyundai", model:"Ioniq 6",  yearStart:2022, yearEnd:2025, type:"ev",    aliases:["ioniq6"] },
  { make:"Hyundai", model:"Palisade", yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Hyundai", model:"Kona",     yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"Hyundai", model:"Kona Electric",yearStart:2018, yearEnd:2025, type:"ev" },
  { make:"Hyundai", model:"Venue",    yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Hyundai", model:"Santa Cruz",yearStart:2021, yearEnd:2025, type:"truck" },
  { make:"Hyundai", model:"Azera",    yearStart:2005, yearEnd:2017, type:"car" },
  { make:"Hyundai", model:"XG350",    yearStart:2003, yearEnd:2005, type:"car",  aliases:["xg300"] },
  { make:"Hyundai", model:"Entourage",yearStart:2006, yearEnd:2009, type:"van" },
  { make:"Hyundai", model:"Veracruz", yearStart:2006, yearEnd:2012, type:"suv" },
  { make:"Hyundai", model:"Excel",    yearStart:1985, yearEnd:1994, type:"car" },
  { make:"Hyundai", model:"Tiburon",  yearStart:1996, yearEnd:2008, type:"car" },
  { make:"Hyundai", model:"Scoupe",   yearStart:1990, yearEnd:1995, type:"car" },
  { make:"Hyundai", model:"Tucson Plug-in Hybrid",yearStart:2021, yearEnd:2025, type:"hybrid" },
  { make:"Hyundai", model:"Santa Fe Hybrid",      yearStart:2021, yearEnd:2025, type:"hybrid" },
  { make:"Hyundai", model:"Nexo",     yearStart:2018, yearEnd:2025, type:"ev",    aliases:["nexo fcev"] },
  { make:"Hyundai", model:"Staria",   yearStart:2021, yearEnd:2025, type:"van" },

  // ── Kia ───────────────────────────────────────────────────────────────────
  { make:"Kia", model:"Forte",     yearStart:2009, yearEnd:2025, type:"car" },
  { make:"Kia", model:"Optima",    yearStart:2000, yearEnd:2020, type:"car" },
  { make:"Kia", model:"K5",        yearStart:2020, yearEnd:2025, type:"car" },
  { make:"Kia", model:"Sportage",  yearStart:1993, yearEnd:2025, type:"suv" },
  { make:"Kia", model:"Sorento",   yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Kia", model:"Soul",      yearStart:2009, yearEnd:2025, type:"car" },
  { make:"Kia", model:"Telluride", yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Kia", model:"Stinger",   yearStart:2017, yearEnd:2023, type:"car" },
  { make:"Kia", model:"Carnival",  yearStart:2021, yearEnd:2025, type:"van",  aliases:["sedona"] },
  { make:"Kia", model:"Sedona",    yearStart:2014, yearEnd:2021, type:"van" },
  { make:"Kia", model:"EV6",       yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Kia", model:"EV9",       yearStart:2023, yearEnd:2025, type:"ev" },
  { make:"Kia", model:"Niro",      yearStart:2016, yearEnd:2025, type:"hybrid" },
  { make:"Kia", model:"Niro EV",   yearStart:2018, yearEnd:2025, type:"ev" },
  { make:"Kia", model:"Seltos",    yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Kia", model:"Sephia",    yearStart:1992, yearEnd:2001, type:"car" },
  { make:"Kia", model:"Spectra",   yearStart:2000, yearEnd:2009, type:"car" },
  { make:"Kia", model:"Rio",       yearStart:2000, yearEnd:2025, type:"car" },
  { make:"Kia", model:"Rondo",     yearStart:2006, yearEnd:2019, type:"car" },
  { make:"Kia", model:"Cadenza",   yearStart:2013, yearEnd:2020, type:"car" },
  { make:"Kia", model:"K900",      yearStart:2014, yearEnd:2021, type:"car" },
  { make:"Kia", model:"Borrego",   yearStart:2008, yearEnd:2010, type:"suv" },
  { make:"Kia", model:"Sorento Plug-in Hybrid",yearStart:2021, yearEnd:2025, type:"hybrid" },

  // ── Acura ─────────────────────────────────────────────────────────────────
  { make:"Acura", model:"TL",    yearStart:1995, yearEnd:2014, type:"car" },
  { make:"Acura", model:"TSX",   yearStart:2003, yearEnd:2014, type:"car" },
  { make:"Acura", model:"ILX",   yearStart:2012, yearEnd:2022, type:"car" },
  { make:"Acura", model:"TLX",   yearStart:2014, yearEnd:2025, type:"car" },
  { make:"Acura", model:"Integra",yearStart:2022, yearEnd:2025, type:"car" },
  { make:"Acura", model:"RL",    yearStart:1996, yearEnd:2012, type:"car" },
  { make:"Acura", model:"RLX",   yearStart:2013, yearEnd:2020, type:"car" },
  { make:"Acura", model:"Legend",yearStart:1986, yearEnd:1995, type:"car" },
  { make:"Acura", model:"MDX",   yearStart:2000, yearEnd:2025, type:"suv" },
  { make:"Acura", model:"RDX",   yearStart:2006, yearEnd:2025, type:"suv" },
  { make:"Acura", model:"ZDX",   yearStart:2009, yearEnd:2013, type:"suv" },
  { make:"Acura", model:"ZDX",   yearStart:2023, yearEnd:2025, type:"ev" },
  { make:"Acura", model:"NSX",   yearStart:1990, yearEnd:2005, type:"car" },
  { make:"Acura", model:"NSX",   yearStart:2016, yearEnd:2022, type:"hybrid" },
  { make:"Acura", model:"CL",    yearStart:1996, yearEnd:2003, type:"car" },
  { make:"Acura", model:"EL",    yearStart:1997, yearEnd:2005, type:"car" },
  { make:"Acura", model:"RSX",   yearStart:2001, yearEnd:2006, type:"car" },
  { make:"Acura", model:"SLX",   yearStart:1996, yearEnd:1999, type:"suv" },
  { make:"Acura", model:"Vigor", yearStart:1991, yearEnd:1994, type:"car" },

  // ── Lexus ─────────────────────────────────────────────────────────────────
  { make:"Lexus", model:"IS",      yearStart:1998, yearEnd:2025, type:"car" },
  { make:"Lexus", model:"ES",      yearStart:1989, yearEnd:2025, type:"car" },
  { make:"Lexus", model:"LS",      yearStart:1989, yearEnd:2025, type:"car" },
  { make:"Lexus", model:"GS",      yearStart:1991, yearEnd:2020, type:"car" },
  { make:"Lexus", model:"RC",      yearStart:2014, yearEnd:2025, type:"car" },
  { make:"Lexus", model:"LC",      yearStart:2017, yearEnd:2025, type:"car" },
  { make:"Lexus", model:"SC",      yearStart:1991, yearEnd:2010, type:"car" },
  { make:"Lexus", model:"RX",      yearStart:1997, yearEnd:2025, type:"suv" },
  { make:"Lexus", model:"NX",      yearStart:2014, yearEnd:2025, type:"suv" },
  { make:"Lexus", model:"UX",      yearStart:2018, yearEnd:2025, type:"suv" },
  { make:"Lexus", model:"GX",      yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Lexus", model:"LX",      yearStart:1995, yearEnd:2025, type:"suv" },
  { make:"Lexus", model:"TX",      yearStart:2023, yearEnd:2025, type:"suv" },
  { make:"Lexus", model:"RZ",      yearStart:2022, yearEnd:2025, type:"ev" },
  { make:"Lexus", model:"UX 300e", yearStart:2020, yearEnd:2025, type:"ev" },
  { make:"Lexus", model:"CT 200h",yearStart:2010, yearEnd:2021, type:"hybrid" },

  // ── Infiniti ──────────────────────────────────────────────────────────────
  { make:"Infiniti", model:"G35",  yearStart:2002, yearEnd:2008, type:"car" },
  { make:"Infiniti", model:"G37",  yearStart:2007, yearEnd:2013, type:"car" },
  { make:"Infiniti", model:"Q50",  yearStart:2013, yearEnd:2025, type:"car" },
  { make:"Infiniti", model:"Q60",  yearStart:2013, yearEnd:2025, type:"car" },
  { make:"Infiniti", model:"Q70",  yearStart:2011, yearEnd:2019, type:"car",  aliases:["m35","m37","m56"] },
  { make:"Infiniti", model:"Q45",  yearStart:1989, yearEnd:2006, type:"car" },
  { make:"Infiniti", model:"FX35", yearStart:2002, yearEnd:2013, type:"suv",  aliases:["fx37","fx45","fx50","fx"] },
  { make:"Infiniti", model:"QX60", yearStart:2012, yearEnd:2025, type:"suv",  aliases:["jx35"] },
  { make:"Infiniti", model:"QX50", yearStart:2012, yearEnd:2025, type:"suv",  aliases:["ex35","ex37"] },
  { make:"Infiniti", model:"QX80", yearStart:2010, yearEnd:2025, type:"suv",  aliases:["qx56"] },
  { make:"Infiniti", model:"QX70", yearStart:2013, yearEnd:2017, type:"suv" },
  { make:"Infiniti", model:"QX30", yearStart:2016, yearEnd:2019, type:"suv" },
  { make:"Infiniti", model:"J30",  yearStart:1992, yearEnd:1997, type:"car" },
  { make:"Infiniti", model:"I30",  yearStart:1995, yearEnd:2001, type:"car" },
  { make:"Infiniti", model:"M30",  yearStart:1990, yearEnd:1992, type:"car" },

  // ── Volvo ─────────────────────────────────────────────────────────────────
  { make:"Volvo", model:"240",   yearStart:1974, yearEnd:1993, type:"car" },
  { make:"Volvo", model:"740",   yearStart:1982, yearEnd:1992, type:"car" },
  { make:"Volvo", model:"760",   yearStart:1982, yearEnd:1990, type:"car" },
  { make:"Volvo", model:"850",   yearStart:1991, yearEnd:1997, type:"car" },
  { make:"Volvo", model:"S40",   yearStart:1995, yearEnd:2012, type:"car" },
  { make:"Volvo", model:"S60",   yearStart:2000, yearEnd:2025, type:"car" },
  { make:"Volvo", model:"S70",   yearStart:1996, yearEnd:2000, type:"car" },
  { make:"Volvo", model:"S80",   yearStart:1998, yearEnd:2016, type:"car" },
  { make:"Volvo", model:"S90",   yearStart:1996, yearEnd:1998, type:"car" },
  { make:"Volvo", model:"S90",   yearStart:2016, yearEnd:2025, type:"car" },
  { make:"Volvo", model:"V40",   yearStart:1995, yearEnd:2019, type:"car" },
  { make:"Volvo", model:"V50",   yearStart:2003, yearEnd:2012, type:"car" },
  { make:"Volvo", model:"V60",   yearStart:2010, yearEnd:2025, type:"car" },
  { make:"Volvo", model:"V70",   yearStart:1996, yearEnd:2016, type:"car" },
  { make:"Volvo", model:"V90",   yearStart:1996, yearEnd:1998, type:"car" },
  { make:"Volvo", model:"V90",   yearStart:2016, yearEnd:2025, type:"car" },
  { make:"Volvo", model:"C30",   yearStart:2006, yearEnd:2012, type:"car" },
  { make:"Volvo", model:"C40",   yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Volvo", model:"C70",   yearStart:1996, yearEnd:2013, type:"car" },
  { make:"Volvo", model:"XC40",  yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"Volvo", model:"XC60",  yearStart:2008, yearEnd:2025, type:"suv" },
  { make:"Volvo", model:"XC70",  yearStart:1997, yearEnd:2016, type:"suv" },
  { make:"Volvo", model:"XC90",  yearStart:2002, yearEnd:2025, type:"suv" },
  { make:"Volvo", model:"EX30",  yearStart:2023, yearEnd:2025, type:"ev" },
  { make:"Volvo", model:"EX40",  yearStart:2023, yearEnd:2025, type:"ev" },
  { make:"Volvo", model:"EX90",  yearStart:2023, yearEnd:2025, type:"ev" },
  { make:"Volvo", model:"144",   yearStart:1966, yearEnd:1974, type:"car" },
  { make:"Volvo", model:"145",   yearStart:1967, yearEnd:1974, type:"car" },
  { make:"Volvo", model:"164",   yearStart:1968, yearEnd:1975, type:"car" },

  // ── Saab ──────────────────────────────────────────────────────────────────
  { make:"Saab", model:"900",   yearStart:1978, yearEnd:1998, type:"car" },
  { make:"Saab", model:"9000",  yearStart:1984, yearEnd:1998, type:"car" },
  { make:"Saab", model:"9-3",   yearStart:1998, yearEnd:2011, type:"car" },
  { make:"Saab", model:"9-5",   yearStart:1997, yearEnd:2011, type:"car" },
  { make:"Saab", model:"9-2X",  yearStart:2004, yearEnd:2006, type:"car" },
  { make:"Saab", model:"9-7X",  yearStart:2004, yearEnd:2009, type:"suv" },
  { make:"Saab", model:"9-4X",  yearStart:2011, yearEnd:2011, type:"suv" },
  { make:"Saab", model:"96",    yearStart:1960, yearEnd:1980, type:"car" },
  { make:"Saab", model:"99",    yearStart:1968, yearEnd:1984, type:"car" },
  { make:"Saab", model:"Sonett",yearStart:1955, yearEnd:1974, type:"car" },

  // ── Land Rover ────────────────────────────────────────────────────────────
  { make:"Land Rover", model:"Range Rover",         yearStart:1969, yearEnd:2025, type:"suv", aliases:["range rover"] },
  { make:"Land Rover", model:"Range Rover Sport",   yearStart:2005, yearEnd:2025, type:"suv" },
  { make:"Land Rover", model:"Range Rover Evoque",  yearStart:2011, yearEnd:2025, type:"suv" },
  { make:"Land Rover", model:"Range Rover Velar",   yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"Land Rover", model:"Discovery",           yearStart:1989, yearEnd:2025, type:"suv" },
  { make:"Land Rover", model:"Discovery Sport",     yearStart:2014, yearEnd:2025, type:"suv" },
  { make:"Land Rover", model:"LR2",                 yearStart:2006, yearEnd:2014, type:"suv", aliases:["freelander"] },
  { make:"Land Rover", model:"LR3",                 yearStart:2004, yearEnd:2009, type:"suv" },
  { make:"Land Rover", model:"LR4",                 yearStart:2009, yearEnd:2016, type:"suv" },
  { make:"Land Rover", model:"Defender",            yearStart:1983, yearEnd:2016, type:"suv" },
  { make:"Land Rover", model:"Defender",            yearStart:2019, yearEnd:2025, type:"suv" },
  { make:"Land Rover", model:"Freelander",          yearStart:1997, yearEnd:2006, type:"suv" },

  // ── Jaguar ────────────────────────────────────────────────────────────────
  { make:"Jaguar", model:"E-Type",  yearStart:1961, yearEnd:1975, type:"car", aliases:["xke"] },
  { make:"Jaguar", model:"XJ",      yearStart:1968, yearEnd:2019, type:"car", aliases:["xj6","xj8","xjl"] },
  { make:"Jaguar", model:"XJS",     yearStart:1975, yearEnd:1996, type:"car", aliases:["xj-s"] },
  { make:"Jaguar", model:"XK",      yearStart:1996, yearEnd:2014, type:"car", aliases:["xk8","xkr"] },
  { make:"Jaguar", model:"S-Type",  yearStart:1999, yearEnd:2008, type:"car" },
  { make:"Jaguar", model:"X-Type",  yearStart:2001, yearEnd:2009, type:"car" },
  { make:"Jaguar", model:"F-Type",  yearStart:2012, yearEnd:2025, type:"car" },
  { make:"Jaguar", model:"XE",      yearStart:2014, yearEnd:2025, type:"car" },
  { make:"Jaguar", model:"XF",      yearStart:2007, yearEnd:2025, type:"car" },
  { make:"Jaguar", model:"F-Pace",  yearStart:2016, yearEnd:2025, type:"suv" },
  { make:"Jaguar", model:"E-Pace",  yearStart:2017, yearEnd:2025, type:"suv" },
  { make:"Jaguar", model:"I-Pace",  yearStart:2018, yearEnd:2025, type:"ev" },

  // ── Tesla ─────────────────────────────────────────────────────────────────
  { make:"Tesla", model:"Model S",    yearStart:2012, yearEnd:2025, type:"ev" },
  { make:"Tesla", model:"Model 3",    yearStart:2017, yearEnd:2025, type:"ev" },
  { make:"Tesla", model:"Model X",    yearStart:2015, yearEnd:2025, type:"ev" },
  { make:"Tesla", model:"Model Y",    yearStart:2020, yearEnd:2025, type:"ev" },
  { make:"Tesla", model:"Cybertruck", yearStart:2023, yearEnd:2025, type:"ev" },
  { make:"Tesla", model:"Roadster",   yearStart:2008, yearEnd:2012, type:"ev" },

  // ── Rivian ────────────────────────────────────────────────────────────────
  { make:"Rivian", model:"R1T", yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Rivian", model:"R1S", yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Rivian", model:"R2",  yearStart:2025, yearEnd:2026, type:"ev" },

  // ── Lucid ─────────────────────────────────────────────────────────────────
  { make:"Lucid", model:"Air",     yearStart:2021, yearEnd:2025, type:"ev" },
  { make:"Lucid", model:"Gravity", yearStart:2024, yearEnd:2025, type:"ev" },

  // ── Polestar ──────────────────────────────────────────────────────────────
  { make:"Polestar", model:"1", yearStart:2019, yearEnd:2021, type:"hybrid" },
  { make:"Polestar", model:"2", yearStart:2019, yearEnd:2025, type:"ev" },
  { make:"Polestar", model:"3", yearStart:2022, yearEnd:2025, type:"ev" },
  { make:"Polestar", model:"4", yearStart:2023, yearEnd:2025, type:"ev" },

  // ── Fisker ────────────────────────────────────────────────────────────────
  { make:"Fisker", model:"Ocean", yearStart:2022, yearEnd:2025, type:"ev" },
  { make:"Fisker", model:"Karma", yearStart:2011, yearEnd:2012, type:"hybrid" },

  // ── Hummer ────────────────────────────────────────────────────────────────
  { make:"Hummer", model:"H1",     yearStart:1992, yearEnd:2006, type:"suv" },
  { make:"Hummer", model:"H2",     yearStart:2002, yearEnd:2009, type:"suv" },
  { make:"Hummer", model:"H3",     yearStart:2005, yearEnd:2010, type:"suv" },
  { make:"Hummer", model:"H3T",    yearStart:2008, yearEnd:2010, type:"truck" },
];

const YEAR_RE_D = /\b(19|20)\d{2}\b/;

function cleanD(v) {
  return String(v || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

const SKIP_WORDS = new Set([
  "oil","coolant","antifreeze","fluid","capacity","type","size","tire",
  "wiper","filter","change","flush","transmission","specs","spec",
]);

const MAKE_NORM_D = {
  chevy:"chevrolet", chev:"chevrolet", gm:"gmc",
  vw:"volkswagen", merc:"mercury", benz:"mercedes-benz",
  mercedes:"mercedes-benz",
};

export function matchDirectory(rawQuery) {
  if (!rawQuery) return [];
  const lower = rawQuery.toLowerCase().replace(/\s*-\s*/g, " ").trim();
  const tokens = lower.split(/\s+/).map((t) => MAKE_NORM_D[t] || t);
  const queryYear = (rawQuery.match(YEAR_RE_D) || [])[0];
  const yearNum = queryYear ? parseInt(queryYear, 10) : null;

  const idTokens = tokens.filter((t) => !SKIP_WORDS.has(t) && !YEAR_RE_D.test(t));
  if (idTokens.length === 0) return [];

  const cleanQ = cleanD(idTokens.join(" "));

  return vehicleDirectory.filter((entry) => {
    // Year range check
    if (yearNum !== null) {
      if (yearNum < entry.yearStart || yearNum > entry.yearEnd) return false;
    }

    const identityParts = [entry.make, entry.model, ...(entry.aliases || [])];
    const identityClean = cleanD(identityParts.join(" "));

    // Full clean match
    if (identityClean.includes(cleanQ)) return true;

    // Every token present
    if (idTokens.every((t) => identityClean.includes(cleanD(t)))) return true;

    return false;
  });
}
