// HoundMoto Vehicle Coverage Database
// Generation-based records used when no exact year match exists in vehicleSpecs.
// Each entry covers one production generation (yearStart–yearEnd).
// All specs are ESTIMATED for the generation — always verify against owner's manual.

export const vehicleCoverage = [

  // ─── Nissan Sentra ────────────────────────────────────────────────────────────
  {
    make: "Nissan", model: "Sentra",
    aliases: ["sentra", "nissan sentra"],
    yearStart: 2000, yearEnd: 2006, generation: "B15",
    engine: "1.8L I4",
    oilType: "5W-30", oilCapacity: "3.5 quarts with filter",
    coolantCapacity: "About 6.3 quarts",
    transmissionFluid: "Nissan Matic-D (auto) or Nissan MTF (manual)",
    transmissionCapacity: "About 7.7 quarts full fill (auto)",
    tireSize: "195/60R15 common, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "22 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Coolant temp sensor, cam position sensor (P0340), catalytic converter failure, idle air control valve, rear wheel bearings",
    dtcNotes: "P0340 cam sensor, P0420 catalyst efficiency, P0507 idle control high, P0011 cam timing",
    maintenanceNotes: "Oil change every 3,750–5,000 mi with conventional oil. Manual trans fluid change every 30k. Inspect CVT fluid condition at every oil change — dark or burnt smell is a warning sign.",
    notes: "Generation estimate for 2000–2006 Nissan Sentra. Specs vary by trim. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Nissan", model: "Sentra",
    aliases: ["sentra", "nissan sentra"],
    yearStart: 2007, yearEnd: 2012, generation: "B16",
    engine: "2.0L I4",
    oilType: "5W-30", oilCapacity: "4.2 quarts with filter",
    coolantCapacity: "About 6.3 quarts",
    transmissionFluid: "Nissan Matic-S (auto) or MTF (manual)",
    transmissionCapacity: "About 7.4 quarts full fill (auto)",
    tireSize: "195/65R15 or 205/55R16, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "22 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "CVT transmission issues, cam sensor, throttle body, rear wheel bearings, timing chain noise",
    dtcNotes: "P0340 cam sensor, P0300 misfires, CVT codes (P17F0/P17F2), P0507 idle control",
    maintenanceNotes: "CVT fluid change every 30k recommended even if Nissan says lifetime — neglected CVT fluid is the leading cause of early CVT failure on this generation.",
    notes: "Generation estimate for 2007–2012 Nissan Sentra. Specs vary by trim. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Nissan", model: "Sentra",
    aliases: ["sentra", "nissan sentra"],
    yearStart: 2013, yearEnd: 2019, generation: "B17",
    engine: "1.8L I4",
    oilType: "5W-30", oilCapacity: "4.3 quarts with filter",
    coolantCapacity: "About 7.2 quarts",
    transmissionFluid: "Nissan CVT NS-3",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "205/55R16, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "26 inch driver / 16 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "CVT fluid degradation causing shudder, cam sensor, catalytic converter, brake booster vacuum leaks",
    dtcNotes: "P0014/P0011 cam timing, P0340 cam sensor, CVT shudder codes, P0420 catalyst",
    maintenanceNotes: "Nissan CVT NS-3 fluid change every 30k prevents shudder and extends CVT life significantly. Use only NS-3 — other fluids cause shudder and seal damage.",
    notes: "Generation estimate for 2013–2019 Nissan Sentra. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Nissan Altima ────────────────────────────────────────────────────────────
  {
    make: "Nissan", model: "Altima",
    aliases: ["altima", "nissan altima"],
    yearStart: 2002, yearEnd: 2006, generation: "L31",
    engine: "2.5L I4 or 3.5L V6",
    oilType: "5W-30", oilCapacity: "4.4 quarts (2.5L) or 4.2 quarts (3.5L) with filter",
    coolantCapacity: "About 7.4 quarts",
    transmissionFluid: "Nissan Matic-S",
    transmissionCapacity: "About 7.6 quarts full fill",
    tireSize: "205/65R16, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "22 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Intake manifold gaskets, cam sensor, catalytic converter, steering column lock failure (ignition), crankshaft position sensor",
    dtcNotes: "P0340 cam sensor, P0420 catalyst, P0335 crank sensor, P0300 misfires",
    maintenanceNotes: "The 2.5L QR25DE had timing chain issues — check for rattle at startup. Use fresh 5W-30 to keep chain and tensioner properly oiled.",
    notes: "Generation estimate for 2002–2006 Nissan Altima. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Nissan", model: "Altima",
    aliases: ["altima", "nissan altima"],
    yearStart: 2007, yearEnd: 2012, generation: "L32",
    engine: "2.5L I4 or 3.5L V6",
    oilType: "5W-30", oilCapacity: "4.4 quarts (2.5L) or 4.2 quarts (3.5L) with filter",
    coolantCapacity: "About 7.4 quarts",
    transmissionFluid: "Nissan CVT NS-2",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "215/60R16 or 215/55R17, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "26 inch driver / 17 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "CVT shudder and failure (critical: change fluid), timing chain rattle, cam sensor, brake switch",
    dtcNotes: "CVT codes, P0340 cam sensor, P0014 cam timing, P0300 misfires",
    maintenanceNotes: "CVT fluid is the single most critical service item. Change every 30k with Nissan NS-2. Neglect is the leading cause of CVT failure on this generation.",
    notes: "Generation estimate for 2007–2012 Nissan Altima. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Nissan", model: "Altima",
    aliases: ["altima", "nissan altima"],
    yearStart: 2013, yearEnd: 2018, generation: "L33",
    engine: "2.5L I4 or 3.5L V6",
    oilType: "5W-30", oilCapacity: "4.4 quarts (2.5L) or 5.1 quarts (3.5L) with filter",
    coolantCapacity: "About 7.4 quarts",
    transmissionFluid: "Nissan CVT NS-3",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "215/60R16 or 215/55R17, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "26 inch driver / 17 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "CVT shudder, cam sensor, brake booster, AC compressor",
    dtcNotes: "CVT fault codes, P0014 cam timing, P0340 cam sensor, P0420 catalyst",
    maintenanceNotes: "CVT NS-3 fluid change every 30k is strongly recommended. Nissan extended warranty on some CVTs — check if your VIN is covered.",
    notes: "Generation estimate for 2013–2018 Nissan Altima. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Nissan Rogue ─────────────────────────────────────────────────────────────
  {
    make: "Nissan", model: "Rogue",
    aliases: ["rogue", "nissan rogue"],
    yearStart: 2008, yearEnd: 2013, generation: "S35",
    engine: "2.5L I4",
    oilType: "5W-30", oilCapacity: "4.8 quarts with filter",
    coolantCapacity: "About 6.5 quarts",
    transmissionFluid: "Nissan CVT NS-2",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "225/65R17, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "26 inch driver / 16 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "CVT shudder and failure, cam sensor, AC compressor, wheel bearings",
    dtcNotes: "CVT codes, P0340 cam sensor, P0014 cam timing, P0420 catalyst",
    maintenanceNotes: "CVT fluid change every 30k with NS-2 is mandatory to prevent shudder and failure.",
    notes: "Generation estimate for 2008–2013 Nissan Rogue. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Nissan", model: "Rogue",
    aliases: ["rogue", "nissan rogue"],
    yearStart: 2014, yearEnd: 2020, generation: "T32",
    engine: "2.5L I4",
    oilType: "5W-30", oilCapacity: "5.1 quarts with filter",
    coolantCapacity: "About 7.3 quarts",
    transmissionFluid: "Nissan CVT NS-3",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "225/65R17 or 225/60R17, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "26 inch driver / 16 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "CVT shudder, engine oil consumption (QR25DE), AC compressor, power steering noise, front struts",
    dtcNotes: "CVT fault codes, P0420 catalyst, P0011 cam timing, oil consumption codes",
    maintenanceNotes: "CVT NS-3 change every 30k. Some 2014-2016 models have oil consumption issues — check level between changes and top off as needed.",
    notes: "Generation estimate for 2014–2020 Nissan Rogue. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Chevrolet Malibu ─────────────────────────────────────────────────────────
  {
    make: "Chevrolet", model: "Malibu",
    aliases: ["malibu", "chevy malibu"],
    yearStart: 2008, yearEnd: 2012, generation: "7th Gen",
    engine: "2.4L I4 or 3.6L V6",
    oilType: "5W-30", oilCapacity: "5.0 quarts with filter",
    coolantCapacity: "About 9 quarts (Dex-Cool)",
    transmissionFluid: "Dexron VI",
    transmissionCapacity: "About 11.5 quarts full fill",
    tireSize: "225/55R17, verify door sticker",
    batteryGroup: "Group H5 or H6 commonly used",
    wipers: "24 inch driver / 17 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Intake manifold carbon buildup (3.6L direct injection), thermostat housing leaks, power steering motor noise, fuel pump",
    dtcNotes: "P0420 catalyst, P0300 misfires, P0128 thermostat, P0017 cam/crank correlation",
    maintenanceNotes: "3.6L V6 direct injection benefits from walnut blasting intake valves every 60-80k. Thermostat housing is plastic and prone to cracking — check for coolant loss.",
    notes: "Generation estimate for 2008–2012 Chevrolet Malibu. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Chevrolet", model: "Malibu",
    aliases: ["malibu", "chevy malibu"],
    yearStart: 2013, yearEnd: 2015, generation: "8th Gen",
    engine: "2.5L I4 or 2.0L Turbo",
    oilType: "5W-30", oilCapacity: "5.0 quarts (2.5L) or 5.5 quarts (2.0T) with filter",
    coolantCapacity: "About 9 quarts (Dex-Cool)",
    transmissionFluid: "Dexron VI",
    transmissionCapacity: "About 12 quarts full fill",
    tireSize: "225/55R17, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "24 inch driver / 17 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "2.0T turbocharger hose connections, carbon buildup, electric power steering faults",
    dtcNotes: "P0171/P0174 lean (turbo boost leak on 2.0T), P0300 misfires, P0128 thermostat",
    maintenanceNotes: "2.0T EcoTec requires fresh 5W-30 and timely oil changes to prevent turbo sludge. Oil change every 5k strongly recommended over extended intervals.",
    notes: "Generation estimate for 2013–2015 Chevrolet Malibu. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Chevrolet", model: "Malibu",
    aliases: ["malibu", "chevy malibu"],
    yearStart: 2016, yearEnd: 2024, generation: "9th Gen",
    engine: "1.5L Turbo or 2.0L Turbo",
    oilType: "5W-30", oilCapacity: "4.5 quarts (1.5T) or 5.5 quarts (2.0T) with filter",
    coolantCapacity: "About 7.5 quarts (Dex-Cool)",
    transmissionFluid: "Dexron HP",
    transmissionCapacity: "About 7 quarts service fill",
    tireSize: "225/55R17 or 235/40R19, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "24 inch driver / 17 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "1.5T turbo coolant passage issues (check TSB), transmission solenoid issues, electric power steering faults",
    dtcNotes: "P0171 lean, P0128 thermostat, P0300 misfires, transmission P0700/P07XX codes",
    maintenanceNotes: "1.5T has a known coolant intrusion issue on some builds — check for coolant in oil (milky dipstick). Transmission uses Dexron HP — critical to use correct fluid.",
    notes: "Generation estimate for 2016–2024 Chevrolet Malibu. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Chevrolet Impala ─────────────────────────────────────────────────────────
  {
    make: "Chevrolet", model: "Impala",
    aliases: ["impala", "chevy impala"],
    yearStart: 2000, yearEnd: 2005, generation: "8th Gen",
    engine: "3.4L V6 or 3.8L V6",
    oilType: "5W-30", oilCapacity: "4.5 quarts with filter",
    coolantCapacity: "About 12 quarts (Dex-Cool)",
    transmissionFluid: "Dexron III or Dexron VI",
    transmissionCapacity: "About 12 quarts full fill",
    tireSize: "225/60R16, verify door sticker",
    batteryGroup: "Group 75 or 78 commonly used",
    wipers: "24 inch driver / 21 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Intake manifold gaskets (3.4L and 3.8L common issue), lower intake coolant leak, throttle position sensor, transmission pressure control solenoid",
    dtcNotes: "P0300 misfires, P0128 thermostat, P0420 catalyst, P1626 antitheft, P0741 TCC solenoid",
    maintenanceNotes: "3.4L and 3.8L both have intake manifold gasket failures that cause coolant leaks into the intake. This is a known issue — inspect gaskets and check oil for coolant contamination.",
    notes: "Generation estimate for 2000–2005 Chevrolet Impala. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Chevrolet", model: "Impala",
    aliases: ["impala", "chevy impala"],
    yearStart: 2006, yearEnd: 2013, generation: "9th Gen",
    engine: "3.5L V6 or 3.9L V6",
    oilType: "5W-30", oilCapacity: "4.0 quarts with filter",
    coolantCapacity: "About 11 quarts (Dex-Cool)",
    transmissionFluid: "Dexron VI",
    transmissionCapacity: "About 12 quarts full fill",
    tireSize: "225/60R16 or P235/50R18, verify door sticker",
    batteryGroup: "Group 78 commonly used",
    wipers: "24 inch driver / 21 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Ignition switch electrical issues, power steering motor, passlock security system, wheel bearings",
    dtcNotes: "P0300 misfires, P1626 antitheft/passlock, P0420 catalyst, P0012/P0014 cam timing",
    maintenanceNotes: "Passlock security issues can cause no-start conditions — symptom is security light staying on. Relearn procedure available. Inspect strut mounts at 60k.",
    notes: "Generation estimate for 2006–2013 Chevrolet Impala. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Chevrolet", model: "Impala",
    aliases: ["impala", "chevy impala"],
    yearStart: 2014, yearEnd: 2020, generation: "10th Gen",
    engine: "2.5L I4 or 3.6L V6",
    oilType: "0W-20 (2.5L) or 5W-30 (3.6L)", oilCapacity: "5.0 quarts with filter",
    coolantCapacity: "About 9 quarts (Dex-Cool)",
    transmissionFluid: "Dexron VI",
    transmissionCapacity: "About 12 quarts full fill",
    tireSize: "235/50R18 or 245/45R20, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "22 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "3.6L V6 timing chain and cam phaser wear, electronic parking brake issues, infotainment screen failures",
    dtcNotes: "P0014/P0017 cam/crank correlation (3.6L), P0300 misfires, electronic parking brake codes",
    maintenanceNotes: "3.6L V6: Timing chain and cam phasers are sensitive to oil quality. Use correct viscosity and change oil every 5k. Oil sludge is a common cause of cam timing codes.",
    notes: "Generation estimate for 2014–2020 Chevrolet Impala. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Chevrolet Silverado 1500 (filling 2000–2011 and 2015–2021 gaps) ──────────
  {
    make: "Chevrolet", model: "Silverado 1500",
    aliases: ["silverado", "chevy silverado", "silverado 1500"],
    yearStart: 2007, yearEnd: 2013, generation: "2nd Gen",
    engine: "4.8L V8, 5.3L V8, or 6.0L V8",
    oilType: "5W-30", oilCapacity: "6 quarts with filter",
    coolantCapacity: "About 15 quarts (Dex-Cool)",
    transmissionFluid: "Dexron VI",
    transmissionCapacity: "About 11.5 quarts service fill",
    tireSize: "Varies by trim, verify door sticker",
    batteryGroup: "Group 78 or H7 commonly used",
    wipers: "22 inch driver / 22 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "AFM (Active Fuel Management) lifter failures on 5.3L, oil consumption from AFM, front wheel bearings, door handles, tailgate latch cables",
    dtcNotes: "P0300 misfires (AFM lifters), P0449 EVAP vent valve, P0128 thermostat, P0017 cam/crank",
    maintenanceNotes: "5.3L AFM lifter failures are the biggest known issue on this generation. Many owners use an AFM Disabler device ($50–$80) to prevent lifter collapse. Transmission flush at 50k. Use Dex-Cool — do not mix coolant types.",
    notes: "Generation estimate for 2007–2013 Silverado 1500. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Chevrolet", model: "Silverado 1500",
    aliases: ["silverado", "chevy silverado", "silverado 1500"],
    yearStart: 2015, yearEnd: 2018, generation: "3rd Gen Late",
    engine: "4.3L V6, 5.3L V8, or 6.2L V8",
    oilType: "0W-20", oilCapacity: "6 quarts (4.3L) or 8 quarts (5.3L/6.2L) with filter",
    coolantCapacity: "About 14 quarts (Dex-Cool)",
    transmissionFluid: "Dexron VI",
    transmissionCapacity: "About 10 quarts service fill",
    tireSize: "Varies by trim, verify door sticker",
    batteryGroup: "Group H7 / 94R commonly used",
    wipers: "22 inch driver / 22 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "AFM lifter failure (5.3L/6.2L), oil pressure loss from AFM, transfer case actuator, power window regulators",
    dtcNotes: "P0300 (AFM lifters), P0449 EVAP, P0016/P0017 cam/crank correlation",
    maintenanceNotes: "0W-20 is required for AFM operation — do not use heavier oil. AFM disable worth considering at 60k+ miles as preventive maintenance.",
    notes: "Generation estimate for 2015–2018 Silverado 1500. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Ford Escape ──────────────────────────────────────────────────────────────
  {
    make: "Ford", model: "Escape",
    aliases: ["escape", "ford escape"],
    yearStart: 2001, yearEnd: 2007, generation: "1st Gen",
    engine: "2.0L I4 or 2.3L I4",
    oilType: "5W-20", oilCapacity: "4.5 quarts with filter",
    coolantCapacity: "About 7 quarts",
    transmissionFluid: "Mercon V",
    transmissionCapacity: "About 8 quarts full fill",
    tireSize: "215/70R16, verify door sticker",
    batteryGroup: "Group 58R or 65 commonly used",
    wipers: "22 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Intake manifold runner control (IMRC), coolant leaks from crossover tube, throttle position sensor, front wheel bearings",
    dtcNotes: "P0171/P0174 lean (vacuum leaks), P0300 misfires, P0128 thermostat",
    maintenanceNotes: "Inspect coolant crossover hose regularly — prone to cracking and causing coolant loss. Spark plugs every 60k.",
    notes: "Generation estimate for 2001–2007 Ford Escape. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Ford", model: "Escape",
    aliases: ["escape", "ford escape"],
    yearStart: 2008, yearEnd: 2012, generation: "2nd Gen",
    engine: "2.5L I4 or 3.0L V6",
    oilType: "5W-20", oilCapacity: "5.0 quarts with filter",
    coolantCapacity: "About 8 quarts",
    transmissionFluid: "Mercon V",
    transmissionCapacity: "About 10 quarts full fill",
    tireSize: "225/65R17 or 235/70R16, verify door sticker",
    batteryGroup: "Group 65 or H6 commonly used",
    wipers: "22 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Throttle body, spark plugs (3.0L is difficult), front wheel bearings, PCM communication errors",
    dtcNotes: "P0171/P0174 lean, P0300 misfires, P0302 (3.0L rear bank hard to access), P0128 thermostat",
    maintenanceNotes: "3.0L V6 rear spark plugs are very difficult to access — often neglected. Address at every tune-up.",
    notes: "Generation estimate for 2008–2012 Ford Escape. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Ford", model: "Escape",
    aliases: ["escape", "ford escape"],
    yearStart: 2013, yearEnd: 2019, generation: "3rd Gen",
    engine: "1.5L EcoBoost, 1.6L EcoBoost, or 2.0L EcoBoost",
    oilType: "5W-20", oilCapacity: "5.0 quarts with filter",
    coolantCapacity: "About 8 quarts",
    transmissionFluid: "Mercon LV",
    transmissionCapacity: "About 10 quarts full fill",
    tireSize: "225/60R17 or 235/50R18, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "24 inch driver / 18 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "1.6L EcoBoost engine coolant intrusion (recall — check your VIN), turbo hose connections, coolant level loss, door lock actuators",
    dtcNotes: "P0087 fuel pressure, P0171 lean (boost leak), P0300 misfires, P0420 catalyst",
    maintenanceNotes: "1.6L EcoBoost had a CRITICAL engine coolant intrusion recall — verify if your VIN is covered. Carbon buildup on EcoBoost intake valves — walnut blast every 60-80k.",
    notes: "Generation estimate for 2013–2019 Ford Escape. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Ford Fusion ──────────────────────────────────────────────────────────────
  {
    make: "Ford", model: "Fusion",
    aliases: ["fusion", "ford fusion"],
    yearStart: 2006, yearEnd: 2012, generation: "1st Gen",
    engine: "2.3L I4 or 2.5L I4 or 3.0L V6",
    oilType: "5W-20", oilCapacity: "4.5 quarts (I4) or 6.0 quarts (V6) with filter",
    coolantCapacity: "About 7 quarts",
    transmissionFluid: "Mercon V",
    transmissionCapacity: "About 10 quarts full fill",
    tireSize: "215/60R16 or 225/50R17, verify door sticker",
    batteryGroup: "Group 58 or 65 commonly used",
    wipers: "24 inch driver / 19 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Throttle body (P2111), door lock actuators, front wheel bearings, sync module issues",
    dtcNotes: "P0171/P0174 lean, P2111 throttle actuator, P0300 misfires, P0128 thermostat",
    maintenanceNotes: "Throttle body cleaning every 30k helps prevent P2111 codes and stall issues. Spark plugs every 60k.",
    notes: "Generation estimate for 2006–2012 Ford Fusion. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Ford", model: "Fusion",
    aliases: ["fusion", "ford fusion"],
    yearStart: 2013, yearEnd: 2020, generation: "2nd Gen",
    engine: "1.5L EcoBoost, 1.6L EcoBoost, 2.0L EcoBoost, or 2.5L I4",
    oilType: "5W-20", oilCapacity: "5.0 quarts (EcoBoost) or 4.5 quarts (2.5L) with filter",
    coolantCapacity: "About 8 quarts",
    transmissionFluid: "Mercon LV",
    transmissionCapacity: "About 10 quarts full fill",
    tireSize: "235/50R17 or 235/45R18, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "26 inch driver / 20 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "1.5/1.6T coolant loss and engine damage (TSB/recall — check VIN), Sync 3 infotainment, door handle cables, front wheel bearings",
    dtcNotes: "P0171 lean (boost leaks on turbo), P0087 fuel pressure, P0300 misfires, P0420 catalyst",
    maintenanceNotes: "1.6L EcoBoost had a CRITICAL coolant intrusion recall — check your VIN immediately if equipped. EcoBoost carbon buildup on intake valves is common.",
    notes: "Generation estimate for 2013–2020 Ford Fusion. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Ford Crown Victoria ──────────────────────────────────────────────────────
  {
    make: "Ford", model: "Crown Victoria",
    aliases: ["crown victoria", "crown vic", "ford crown vic", "cvpi"],
    yearStart: 1998, yearEnd: 2011, generation: "P71/P73",
    engine: "4.6L V8",
    oilType: "5W-20", oilCapacity: "5.0 quarts with filter",
    coolantCapacity: "About 13 quarts",
    transmissionFluid: "Mercon V",
    transmissionCapacity: "About 12 quarts full fill",
    tireSize: "P225/60R16, verify door sticker",
    batteryGroup: "Group 65 commonly used",
    wipers: "22 inch driver / 22 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Throttle position sensor, EGR valve, ball joints, fuel pressure regulator, rear air suspension (if equipped)",
    dtcNotes: "P0402 EGR flow (very common), P0171/P0174 lean, P0300 misfires, air suspension codes",
    maintenanceNotes: "EGR valve cleaning or replacement at 100k is common preventive maintenance. Rear air suspension bags fail and many owners convert to coil springs. Solid and reliable platform overall.",
    notes: "Generation estimate for 1998–2011 Ford Crown Victoria. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Mercury Grand Marquis (broader coverage than base) ───────────────────────
  {
    make: "Mercury", model: "Grand Marquis",
    aliases: ["grand marquis", "marquis", "mercury grand marquis"],
    yearStart: 2003, yearEnd: 2011, generation: "MN12 Late",
    engine: "4.6L V8",
    oilType: "5W-20", oilCapacity: "5.0 quarts with filter",
    coolantCapacity: "About 12 quarts",
    transmissionFluid: "Mercon V",
    transmissionCapacity: "About 12 quarts full fill",
    tireSize: "P225/60R16, verify door sticker",
    batteryGroup: "Group 65 commonly used",
    wipers: "22 inch driver / 22 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "EGR valve and passage carbon buildup (P0402 very common), throttle body, front ball joints, rear air suspension leaks",
    dtcNotes: "P0402 EGR flow (very common), P0171/P0174 lean, P0300 misfires, rear air suspension codes",
    maintenanceNotes: "EGR system maintenance at 100k is standard. Rear air suspension bags commonly fail at 100-150k — conversion kit to coil springs is a popular fix. Mechanically identical to Crown Victoria.",
    notes: "Generation estimate for 2003–2011 Mercury Grand Marquis. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Jeep Grand Cherokee ──────────────────────────────────────────────────────
  {
    make: "Jeep", model: "Grand Cherokee",
    aliases: ["grand cherokee", "jeep grand cherokee", "jgc"],
    yearStart: 1999, yearEnd: 2004, generation: "WJ",
    engine: "4.0L I6 or 4.7L V8",
    oilType: "5W-30", oilCapacity: "6.0 quarts (4.0L) or 5.0 quarts (4.7L) with filter",
    coolantCapacity: "About 10 quarts (4.0L) or 13 quarts (4.7L)",
    transmissionFluid: "ATF+4",
    transmissionCapacity: "About 9 quarts full fill",
    tireSize: "225/75R16 or 235/70R16, verify door sticker",
    batteryGroup: "Group 34 commonly used",
    wipers: "20 inch driver / 20 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Crankshaft position sensor (4.0L common no-start), front axle actuator 4WD, rear main seal, head gasket (4.0L high-mileage), lift support struts",
    dtcNotes: "P0320 crank sensor (4.0L common), P0300 misfires, P0740 TCC, 4WD transfer case codes",
    maintenanceNotes: "4.0L I6 is extremely reliable if maintained. Crank sensor failure is the most common no-start cause — relatively easy DIY fix. Transfer case fluid change every 30k.",
    notes: "Generation estimate for 1999–2004 Jeep Grand Cherokee. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Jeep", model: "Grand Cherokee",
    aliases: ["grand cherokee", "jeep grand cherokee", "jgc"],
    yearStart: 2005, yearEnd: 2010, generation: "WK",
    engine: "3.7L V6, 4.7L V8, or 5.7L Hemi",
    oilType: "5W-20", oilCapacity: "5.0 qt (3.7L) or 6.0 qt (4.7L) or 7.0 qt (5.7L) with filter",
    coolantCapacity: "About 13 quarts",
    transmissionFluid: "ATF+4",
    transmissionCapacity: "About 9 quarts full fill",
    tireSize: "265/60R18 or 245/65R17, verify door sticker",
    batteryGroup: "Group 34 commonly used",
    wipers: "22 inch driver / 20 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Front differential noise (3.7L and 4.7L), rear axle bearings, HVAC blend door actuator, lift gate struts, throttle body",
    dtcNotes: "P0300 misfires, P0128 thermostat, P0455 EVAP, front diff codes",
    maintenanceNotes: "5.7L Hemi MDS cylinder deactivation can cause lifter issues at high mileage — similar to GM AFM. Transfer case and front diff fluid change every 30k.",
    notes: "Generation estimate for 2005–2010 Jeep Grand Cherokee. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Jeep", model: "Grand Cherokee",
    aliases: ["grand cherokee", "jeep grand cherokee", "jgc"],
    yearStart: 2011, yearEnd: 2021, generation: "WK2",
    engine: "3.6L V6 or 5.7L Hemi",
    oilType: "5W-20 (3.6L) or 5W-20 (5.7L)", oilCapacity: "5.9 quarts (3.6L) or 7.0 quarts (5.7L) with filter",
    coolantCapacity: "About 12 quarts",
    transmissionFluid: "ATF+4",
    transmissionCapacity: "About 9 quarts full fill",
    tireSize: "255/65R18 or 265/60R18, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "24 inch driver / 18 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "3.6L oil leaks from rear main seal and cam phaser leaks, EVAP purge valve, HVAC blend door actuator, power tailgate issues",
    dtcNotes: "P0014/P0017 cam timing (3.6L), P0455 EVAP, P0300 misfires, P0128 thermostat",
    maintenanceNotes: "3.6L Pentastar is reliable but watch for cam phaser noise at startup — indicates oil pressure or timing wear. Oil changes every 5k with the correct spec oil.",
    notes: "Generation estimate for 2011–2021 Jeep Grand Cherokee. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Jeep Cherokee (XJ) ───────────────────────────────────────────────────────
  {
    make: "Jeep", model: "Cherokee",
    aliases: ["cherokee", "jeep cherokee", "xj", "jeep xj"],
    yearStart: 1984, yearEnd: 2001, generation: "XJ",
    engine: "4.0L I6",
    oilType: "5W-30", oilCapacity: "6.0 quarts with filter",
    coolantCapacity: "About 9 quarts",
    transmissionFluid: "ATF+3 (auto) or Jeep/Dana manual gear lube",
    transmissionCapacity: "About 8 quarts full fill",
    tireSize: "225/75R15 or 235/75R15, verify door sticker",
    batteryGroup: "Group 34 commonly used",
    wipers: "20 inch driver / 18 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Crankshaft position sensor (no-start, P0320), head gasket at high mileage, cooling fan, front axle U-joints, rear main seal",
    dtcNotes: "P0320 crank sensor (very common no-start), P0300 misfires, crank/cam sensor codes",
    maintenanceNotes: "The 4.0L AMC I6 is one of the most reliable engines ever made if maintained. Crank sensor failure causes sudden no-start — cheap and easy fix. Coolant flush every 30k to prevent corrosion.",
    notes: "Generation estimate for 1984–2001 Jeep Cherokee XJ. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Jeep Cherokee (KL, 2014+) ───────────────────────────────────────────────
  {
    make: "Jeep", model: "Cherokee",
    aliases: ["cherokee", "jeep cherokee", "kl"],
    yearStart: 2014, yearEnd: 2023, generation: "KL",
    engine: "2.4L I4 or 3.2L V6",
    oilType: "0W-20 (2.4L) or 5W-20 (3.2L)", oilCapacity: "5.5 quarts (2.4L) or 5.9 quarts (3.2L) with filter",
    coolantCapacity: "About 8 quarts",
    transmissionFluid: "ATF+4 (9-speed) or ZF LifeguardFluid 8",
    transmissionCapacity: "About 8 quarts full fill",
    tireSize: "225/60R17, verify door sticker",
    batteryGroup: "Group H6 / 48 commonly used",
    wipers: "24 inch driver / 16 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "9-speed transmission hesitation and harsh shifts (TSBs available), 3.2L cam phaser noise, EVAP valve, door lock actuators",
    dtcNotes: "9-speed trans codes (P0700 series), P0014/P0017 cam timing (3.2L), P0455 EVAP",
    maintenanceNotes: "9-speed ZF transmission has software updates available that improve shift quality — ask dealer. 3.2L Pentastar cam phaser noise at cold start is a known issue.",
    notes: "Generation estimate for 2014–2023 Jeep Cherokee (KL). Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Toyota Camry 2012–2017 (fills test case gap) ────────────────────────────
  {
    make: "Toyota", model: "Camry",
    aliases: ["camry", "toyota camry"],
    yearStart: 2012, yearEnd: 2017, generation: "XV50",
    engine: "2.5L I4 or 3.5L V6",
    oilType: "0W-20", oilCapacity: "4.8 quarts (2.5L) or 6.4 quarts (3.5L) with filter",
    coolantCapacity: "About 6.3 quarts (2.5L) or 7.6 quarts (3.5L)",
    transmissionFluid: "Toyota WS",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "205/65R16 or 215/55R17, verify door sticker",
    batteryGroup: "Group H5 or 35 commonly used",
    wipers: "26 inch driver / 18 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "2.5L oil consumption (some owners report), parking sensor faults, SRS airbag squib connector recall, infotainment screen issues",
    dtcNotes: "P0013/P0014 cam timing (rare), P0420 catalyst, P0300 misfires (usually ignition coil)",
    maintenanceNotes: "0W-20 is specified — do not substitute heavier oil. Check oil level between oil changes — some 2.5L units have higher consumption. Toyota WS transmission fluid is lifetime-fill per Toyota but many shops recommend changing at 60-90k.",
    notes: "Generation estimate for 2012–2017 Toyota Camry (XV50). Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Honda Civic 2001–2005 (fills test case gap) ──────────────────────────────
  {
    make: "Honda", model: "Civic",
    aliases: ["civic", "honda civic"],
    yearStart: 2001, yearEnd: 2005, generation: "7th Gen",
    engine: "1.7L I4",
    oilType: "5W-20", oilCapacity: "3.5 quarts with filter",
    coolantCapacity: "About 5.6 quarts",
    transmissionFluid: "Honda ATF-Z1 (auto) or MTF (manual)",
    transmissionCapacity: "About 6.5 quarts full fill (auto)",
    tireSize: "185/70R14 or 195/65R15, verify door sticker",
    batteryGroup: "Group 51R commonly used",
    wipers: "24 inch driver / 18 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Ignition coils and spark plugs, power door lock actuators, manual transmission synchros, catalytic converter",
    dtcNotes: "P0301-P0304 cylinder misfires (coil issues), P0420 catalyst, P1457 EVAP (common)",
    maintenanceNotes: "1.7L VTEC/non-VTEC: Iridium spark plugs at 60k. Honda ATF-Z1 for automatic only — do not substitute generic ATF. Manual: Honda MTF or equivalent only.",
    notes: "Generation estimate for 2001–2005 Honda Civic. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Toyota RAV4 additional coverage ─────────────────────────────────────────
  {
    make: "Toyota", model: "RAV4",
    aliases: ["rav4", "toyota rav4", "rav 4"],
    yearStart: 2013, yearEnd: 2018, generation: "XA40",
    engine: "2.5L I4",
    oilType: "0W-20", oilCapacity: "4.8 quarts with filter",
    coolantCapacity: "About 6.9 quarts",
    transmissionFluid: "Toyota WS",
    transmissionCapacity: "About 7.4 quarts full fill",
    tireSize: "225/65R17, verify door sticker",
    batteryGroup: "Group 35 commonly used",
    wipers: "28 inch driver / 16 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "Rear differential fluid (AWD models needs separate service), AC compressor, timing chain noise at startup, trunk struts",
    dtcNotes: "P0014/P0013 cam timing, P0420 catalyst, P0300 misfires",
    maintenanceNotes: "AWD models need rear differential fluid change every 30k. Toyota WS ATF: Toyota recommends lifetime, shops recommend changing at 60-90k to prevent shudder.",
    notes: "Generation estimate for 2013–2018 Toyota RAV4 (XA40). Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Honda CR-V additional coverage ──────────────────────────────────────────
  {
    make: "Honda", model: "CR-V",
    aliases: ["crv", "cr-v", "honda crv", "honda cr-v"],
    yearStart: 2007, yearEnd: 2011, generation: "3rd Gen",
    engine: "2.4L I4",
    oilType: "5W-20", oilCapacity: "4.4 quarts with filter",
    coolantCapacity: "About 6.6 quarts",
    transmissionFluid: "Honda ATF DW-1",
    transmissionCapacity: "About 7.0 quarts full fill",
    tireSize: "215/70R16, verify door sticker",
    batteryGroup: "Group 51R commonly used",
    wipers: "26 inch driver / 14 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "AC compressor, front wheel bearings, rear differential (AWD units need Honda Dual Pump fluid), power window regulators",
    dtcNotes: "P0300 misfires, P0420 catalyst, P1457 EVAP (common on older Honda)",
    maintenanceNotes: "AWD rear differential requires Honda Dual Pump Fluid II — do not substitute. Honda ATF DW-1 for automatic only. Oil change every 5k.",
    notes: "Generation estimate for 2007–2011 Honda CR-V. Verify before service.",
    confidenceLevel: "estimated",
  },
  {
    make: "Honda", model: "CR-V",
    aliases: ["crv", "cr-v", "honda crv", "honda cr-v"],
    yearStart: 2017, yearEnd: 2022, generation: "5th Gen",
    engine: "1.5L Turbo",
    oilType: "0W-20", oilCapacity: "3.7 quarts with filter",
    coolantCapacity: "About 5.0 quarts",
    transmissionFluid: "Honda CVT Fluid",
    transmissionCapacity: "About 6.5 quarts full fill",
    tireSize: "225/65R17 or 235/60R18, verify door sticker",
    batteryGroup: "Group 51R commonly used",
    wipers: "26 inch driver / 14 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "1.5T oil dilution with fuel (cold climate issue, TSB available), AWD rear fluid, infotainment screen",
    dtcNotes: "P0087 fuel pressure, P0300 misfires, oil dilution codes, AWD system codes",
    maintenanceNotes: "1.5T oil dilution: If you make short trips in cold weather, check oil level and smell. Dilution raises oil level. Honda extended oil change interval is NOT recommended on affected builds — change every 5k.",
    notes: "Generation estimate for 2017–2022 Honda CR-V. Verify before service.",
    confidenceLevel: "estimated",
  },

  // ─── Ram 1500 additional coverage ─────────────────────────────────────────────
  {
    make: "Ram", model: "1500",
    aliases: ["ram 1500", "ram pickup", "dodge ram", "ram truck"],
    yearStart: 2009, yearEnd: 2018, generation: "DS",
    engine: "4.7L V8 or 5.7L Hemi",
    oilType: "5W-20", oilCapacity: "5.9 quarts (4.7L) or 7.0 quarts (5.7L) with filter",
    coolantCapacity: "About 14 quarts",
    transmissionFluid: "ATF+4",
    transmissionCapacity: "About 9.5 quarts full fill",
    tireSize: "Varies by trim, verify door sticker",
    batteryGroup: "Group H7 or 34 commonly used",
    wipers: "22 inch driver / 22 inch passenger",
    bulbs: "Verify by trim",
    commonFailures: "5.7L MDS cylinder deactivation lifter issues (similar to GM AFM), exhaust manifold bolts breaking, HVAC blend door, power window regulator clips, rear differential",
    dtcNotes: "P0300 misfires (MDS lifters), P0128 thermostat, P0455 EVAP, P0740 TCC solenoid",
    maintenanceNotes: "5.7L MDS: same basic risk as GM AFM — cylinder deactivation can cause lifter issues at high mileage. MDS can be disabled with tuning. ATF+4 flush at 30-60k.",
    notes: "Generation estimate for 2009–2018 Ram 1500. Verify before service.",
    confidenceLevel: "estimated",
  },

];
